namespace B2bOrder.Resources.ShareCore
{
    /// <summary>
    /// NotificationCommunicationDB V2 Shared Core Schema
    /// 支援 Email、簡訊、LINE、App 推播、站內通知、Webhook、範本、收件端點、偏好、同意、發送佇列、重試、退信、退訂、摘要與KPI。
    /// nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼。
    /// avalible：Y可用；W停用；D刪除。
    /// 適用 MySQL 8.x / InnoDB / utf8mb4。
    /// </summary>
    internal static class NotificationCommunicationDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS nc_channel_provider (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通訊供應商序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    provider_code VARCHAR(100) NOT NULL COMMENT '供應商代碼',
    provider_name VARCHAR(300) NOT NULL COMMENT '供應商名稱',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;OTHER',
    provider_type VARCHAR(30) NOT NULL COMMENT 'SMTP;API;FCM;APNS;LINE_MESSAGING;SMS_GATEWAY;WEBHOOK;OTHER',
    endpoint_url VARCHAR(1000) NULL COMMENT 'API或Webhook端點',
    credential_reference_sid VARCHAR(32) NULL COMMENT 'SecretVaultDB憑證參照序號',
    sender_identity VARCHAR(300) NULL COMMENT '預設寄件者或發送帳號',
    callback_url VARCHAR(1000) NULL COMMENT '狀態回呼網址',
    rate_limit_per_minute INT NULL COMMENT '每分鐘發送上限',
    daily_limit INT NULL COMMENT '每日發送上限',
    retry_policy_sid VARCHAR(32) NULL COMMENT '重試政策序號',
    provider_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用;MAINTENANCE維護;DISABLED停權',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_ncp_provider_code UNIQUE (provider_code),
    INDEX idx_ncp_channel_type (channel_type),
    INDEX idx_ncp_provider_type (provider_type),
    INDEX idx_ncp_status (provider_status),
    CHECK (rate_limit_per_minute IS NULL OR rate_limit_per_minute > 0),
    CHECK (daily_limit IS NULL OR daily_limit > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Email、簡訊、LINE、推播與Webhook供應商';

CREATE TABLE IF NOT EXISTS nc_retry_policy (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知重試政策序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    policy_code VARCHAR(100) NOT NULL COMMENT '重試政策代碼',
    policy_name VARCHAR(300) NOT NULL COMMENT '重試政策名稱',
    max_attempts INT NOT NULL DEFAULT 3 COMMENT '最大嘗試次數',
    initial_delay_seconds INT NOT NULL DEFAULT 60 COMMENT '首次延遲秒數',
    backoff_type VARCHAR(20) NOT NULL DEFAULT 'EXPONENTIAL' COMMENT 'FIXED固定;LINEAR線性;EXPONENTIAL指數',
    backoff_multiplier DECIMAL(10,4) NOT NULL DEFAULT 2 COMMENT '退避倍數',
    max_delay_seconds INT NOT NULL DEFAULT 3600 COMMENT '最大延遲秒數',
    retryable_error_codes JSON NULL COMMENT '可重試錯誤代碼',
    non_retryable_error_codes JSON NULL COMMENT '不可重試錯誤代碼',
    policy_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_nrp_policy_code UNIQUE (policy_code),
    INDEX idx_nrp_status (policy_status),
    CHECK (max_attempts > 0),
    CHECK (initial_delay_seconds >= 0),
    CHECK (backoff_multiplier > 0),
    CHECK (max_delay_seconds >= initial_delay_seconds)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知發送失敗重試與退避政策';

CREATE TABLE IF NOT EXISTS nc_template (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知範本序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    template_code VARCHAR(100) NOT NULL COMMENT '範本代碼',
    template_name VARCHAR(300) NOT NULL COMMENT '範本名稱',
    company_sid VARCHAR(32) NULL COMMENT '公司序號，NULL代表共用範本',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    message_category VARCHAR(50) NOT NULL COMMENT 'SYSTEM系統;TRANSACTION交易;PAYMENT付款;PROJECT專案;WORKFLOW流程;MARKETING行銷;SECURITY安全;OTHER',
    language_code VARCHAR(20) NOT NULL DEFAULT 'zh-TW' COMMENT '語系',
    subject_template VARCHAR(500) NULL COMMENT '主旨範本',
    title_template VARCHAR(500) NULL COMMENT '標題範本',
    body_template LONGTEXT NOT NULL COMMENT '內容範本',
    html_template LONGTEXT NULL COMMENT 'HTML內容範本',
    payload_template JSON NULL COMMENT 'LINE、Push或Webhook Payload範本',
    variable_schema JSON NULL COMMENT '範本變數定義',
    default_sender_identity VARCHAR(300) NULL COMMENT '預設寄件者',
    external_template_id VARCHAR(300) NULL COMMENT '外部供應商範本ID',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需審核',
    current_version INT NOT NULL DEFAULT 1 COMMENT '目前版本',
    template_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;ACTIVE生效;INACTIVE停用;ARCHIVED封存',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_nt_template_code UNIQUE (template_code),
    INDEX idx_nt_company_sid (company_sid),
    INDEX idx_nt_channel_type (channel_type),
    INDEX idx_nt_message_category (message_category),
    INDEX idx_nt_language_code (language_code),
    INDEX idx_nt_status (template_status),
    CHECK (current_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨系統通知與通訊範本';

CREATE TABLE IF NOT EXISTS nc_template_version (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '範本版本序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    template_sid VARCHAR(32) NOT NULL COMMENT '通知範本序號',
    version_no INT NOT NULL COMMENT '版本號',
    subject_template VARCHAR(500) NULL COMMENT '主旨範本',
    title_template VARCHAR(500) NULL COMMENT '標題範本',
    body_template LONGTEXT NOT NULL COMMENT '內容範本',
    html_template LONGTEXT NULL COMMENT 'HTML內容範本',
    payload_template JSON NULL COMMENT 'Payload範本',
    variable_schema JSON NULL COMMENT '變數定義',
    change_summary VARCHAR(1000) NULL COMMENT '版本變更說明',
    created_by_user_sid VARCHAR(32) NULL COMMENT '建立人員序號',
    approved_by_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    version_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;ACTIVE生效;SUPERSEDED取代;REJECTED退回',
    CONSTRAINT uk_ntv_template_version UNIQUE (template_sid, version_no),
    INDEX idx_ntv_template_sid (template_sid),
    INDEX idx_ntv_status (version_status),
    CHECK (version_no > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知範本版本歷程';

CREATE TABLE IF NOT EXISTS nc_recipient_endpoint (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '收件端點序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工;DEVICE裝置;OTHER',
    subject_sid VARCHAR(32) NOT NULL COMMENT '收件主體序號',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    endpoint_value VARCHAR(1000) NOT NULL COMMENT 'Email、電話、LINE ID、Push Token或Webhook URL',
    endpoint_hash VARCHAR(255) NULL COMMENT '端點雜湊',
    endpoint_label VARCHAR(200) NULL COMMENT '端點名稱',
    primary_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主要端點',
    verified_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已驗證',
    verified_date DATETIME NULL COMMENT '驗證時間',
    verification_method VARCHAR(30) NULL COMMENT 'OTP驗證碼;LINK連結;IMPORT匯入;ADMIN管理員;PROVIDER供應商',
    bounce_count INT NOT NULL DEFAULT 0 COMMENT '退信或失敗次數',
    last_success_date DATETIME NULL COMMENT '最後成功時間',
    last_failure_date DATETIME NULL COMMENT '最後失敗時間',
    endpoint_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;UNVERIFIED未驗證;BOUNCED退信;INVALID無效;UNSUBSCRIBED退訂;DISABLED停用',
    CONSTRAINT uk_nre_subject_channel_endpoint UNIQUE (subject_type, subject_sid, channel_type, endpoint_value(255)),
    INDEX idx_nre_subject (subject_type, subject_sid),
    INDEX idx_nre_channel_type (channel_type),
    INDEX idx_nre_endpoint_hash (endpoint_hash),
    INDEX idx_nre_primary_mark (primary_mark),
    INDEX idx_nre_status (endpoint_status),
    CHECK (bounce_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Email、電話、LINE、Push Token與Webhook端點';

CREATE TABLE IF NOT EXISTS nc_preference (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知偏好序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工',
    subject_sid VARCHAR(32) NOT NULL COMMENT '偏好主體序號',
    message_category VARCHAR(50) NOT NULL COMMENT 'SYSTEM系統;TRANSACTION交易;PAYMENT付款;PROJECT專案;WORKFLOW流程;MARKETING行銷;SECURITY安全;OTHER',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    enabled_mark TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否啟用',
    quiet_start_time TIME NULL COMMENT '勿擾開始時間',
    quiet_end_time TIME NULL COMMENT '勿擾結束時間',
    digest_mode VARCHAR(20) NOT NULL DEFAULT 'IMMEDIATE' COMMENT 'IMMEDIATE即時;HOURLY每小時;DAILY每日;WEEKLY每週',
    digest_time TIME NULL COMMENT '彙整發送時間',
    minimum_priority VARCHAR(20) NOT NULL DEFAULT 'LOW' COMMENT 'LOW低;NORMAL一般;HIGH高;URGENT緊急;CRITICAL重大',
    effective_date DATE NOT NULL DEFAULT (CURRENT_DATE) COMMENT '生效日',
    expiry_date DATE NULL COMMENT '到期日',
    preference_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;INACTIVE停用',
    CONSTRAINT uk_np_subject_category_channel UNIQUE (subject_type, subject_sid, message_category, channel_type),
    INDEX idx_np_subject (subject_type, subject_sid),
    INDEX idx_np_message_category (message_category),
    INDEX idx_np_channel_type (channel_type),
    INDEX idx_np_status (preference_status),
    CHECK (expiry_date IS NULL OR expiry_date >= effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨系統通知偏好、勿擾與摘要模式';

CREATE TABLE IF NOT EXISTS nc_consent (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通訊同意序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工',
    subject_sid VARCHAR(32) NOT NULL COMMENT '同意主體序號',
    consent_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;VOICE語音;MARKETING行銷;TRANSACTION交易',
    consent_status VARCHAR(20) NOT NULL COMMENT 'GRANTED同意;WITHDRAWN撤回;EXPIRED到期;PENDING待確認',
    consent_date DATETIME NOT NULL COMMENT '同意異動時間',
    expiry_date DATETIME NULL COMMENT '到期時間',
    source_type VARCHAR(30) NOT NULL COMMENT 'FORM表單;CONTRACT合約;PORTAL入口;APP;CALL電話;IMPORT匯入;ADMIN管理員;OTHER',
    source_reference_sid VARCHAR(32) NULL COMMENT '來源資料序號',
    consent_text_version VARCHAR(50) NULL COMMENT '同意文字版本',
    ip_address VARCHAR(50) NULL COMMENT 'IP位址',
    evidence_file_sid VARCHAR(32) NULL COMMENT 'FileDB同意證據序號',
    CONSTRAINT uk_nc_subject_type_date UNIQUE (subject_type, subject_sid, consent_type, consent_date),
    INDEX idx_nc_subject (subject_type, subject_sid),
    INDEX idx_nc_consent_type (consent_type),
    INDEX idx_nc_status (consent_status),
    INDEX idx_nc_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通訊與行銷同意、撤回及證據';

CREATE TABLE IF NOT EXISTS nc_notification_request (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知請求序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    request_no VARCHAR(100) NOT NULL COMMENT '通知請求編號',
    source_system VARCHAR(100) NOT NULL COMMENT '來源系統',
    source_module VARCHAR(100) NULL COMMENT '來源模組',
    source_entity_type VARCHAR(50) NULL COMMENT '來源實體類型',
    source_entity_sid VARCHAR(32) NULL COMMENT '來源實體序號',
    event_code VARCHAR(120) NULL COMMENT '事件代碼',
    template_sid VARCHAR(32) NULL COMMENT '通知範本序號',
    template_code VARCHAR(100) NULL COMMENT '範本代碼快照',
    message_category VARCHAR(50) NOT NULL COMMENT 'SYSTEM系統;TRANSACTION交易;PAYMENT付款;PROJECT專案;WORKFLOW流程;MARKETING行銷;SECURITY安全;OTHER',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW低;NORMAL一般;HIGH高;URGENT緊急;CRITICAL重大',
    scheduled_date DATETIME NULL COMMENT '預定處理時間',
    expires_date DATETIME NULL COMMENT '請求失效時間',
    sender_override JSON NULL COMMENT '寄件者覆寫',
    recipient_rule JSON NULL COMMENT '收件者規則',
    template_variables JSON NULL COMMENT '範本變數',
    deduplication_key VARCHAR(255) NULL COMMENT '去重鍵',
    correlation_id VARCHAR(100) NULL COMMENT '跨服務關聯識別碼',
    causation_id VARCHAR(100) NULL COMMENT '因果事件ID',
    request_status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED' COMMENT 'RECEIVED已接收;VALIDATING驗證中;QUEUED已排隊;PROCESSING處理中;PARTIAL_SUCCESS部分成功;SUCCESS成功;FAILED失敗;EXPIRED過期;CANCELLED取消',
    error_message TEXT NULL COMMENT '錯誤訊息',
    CONSTRAINT uk_nnr_request_no UNIQUE (request_no),
    UNIQUE KEY uk_nnr_deduplication_key (deduplication_key),
    INDEX idx_nnr_source (source_system, source_module),
    INDEX idx_nnr_source_entity (source_entity_type, source_entity_sid),
    INDEX idx_nnr_event_code (event_code),
    INDEX idx_nnr_template_sid (template_sid),
    INDEX idx_nnr_category (message_category),
    INDEX idx_nnr_priority (priority),
    INDEX idx_nnr_scheduled_date (scheduled_date),
    INDEX idx_nnr_correlation_id (correlation_id),
    INDEX idx_nnr_status (request_status),
    CHECK (expires_date IS NULL OR scheduled_date IS NULL OR expires_date >= scheduled_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='各系統提交的統一通知請求';

CREATE TABLE IF NOT EXISTS nc_notification_recipient (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知收件者序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    notification_request_sid VARCHAR(32) NOT NULL COMMENT '通知請求序號',
    recipient_type VARCHAR(20) NOT NULL COMMENT 'TO收件者;CC副本;BCC密件;REPLY_TO回覆;TARGET目標',
    subject_type VARCHAR(20) NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工;DEVICE裝置;OTHER',
    subject_sid VARCHAR(32) NULL COMMENT '收件主體序號',
    endpoint_sid VARCHAR(32) NULL COMMENT '收件端點序號',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    recipient_name VARCHAR(300) NULL COMMENT '收件人名稱快照',
    endpoint_value VARCHAR(1000) NOT NULL COMMENT '實際收件端點',
    language_code VARCHAR(20) NULL COMMENT '使用語系',
    timezone_code VARCHAR(50) NULL COMMENT '時區',
    personalized_variables JSON NULL COMMENT '個人化變數',
    consent_checked_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已檢查同意',
    preference_checked_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已檢查偏好',
    recipient_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;ELIGIBLE可發送;SUPPRESSED抑制;INVALID無效;UNSUBSCRIBED退訂;COMPLETED完成',
    suppression_reason VARCHAR(1000) NULL COMMENT '抑制原因',
    INDEX idx_nnrp_request_sid (notification_request_sid),
    INDEX idx_nnrp_subject (subject_type, subject_sid),
    INDEX idx_nnrp_endpoint_sid (endpoint_sid),
    INDEX idx_nnrp_channel_type (channel_type),
    INDEX idx_nnrp_status (recipient_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知收件主體、端點與偏好判定';

CREATE TABLE IF NOT EXISTS nc_message (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '實際訊息序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    notification_request_sid VARCHAR(32) NOT NULL COMMENT '通知請求序號',
    notification_recipient_sid VARCHAR(32) NOT NULL COMMENT '通知收件者序號',
    provider_sid VARCHAR(32) NULL COMMENT '通訊供應商序號',
    template_sid VARCHAR(32) NULL COMMENT '通知範本序號',
    template_version_no INT NULL COMMENT '範本版本號',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    provider_message_id VARCHAR(300) NULL COMMENT '供應商訊息ID',
    sender_identity VARCHAR(300) NULL COMMENT '寄件者',
    recipient_endpoint VARCHAR(1000) NOT NULL COMMENT '收件端點',
    subject_text VARCHAR(500) NULL COMMENT '實際主旨',
    title_text VARCHAR(500) NULL COMMENT '實際標題',
    body_text LONGTEXT NULL COMMENT '純文字內容',
    html_content LONGTEXT NULL COMMENT 'HTML內容',
    payload_data JSON NULL COMMENT 'LINE、Push或Webhook Payload',
    scheduled_date DATETIME NULL COMMENT '預定發送時間',
    queued_date DATETIME NULL COMMENT '進入佇列時間',
    sent_date DATETIME NULL COMMENT '送出時間',
    delivered_date DATETIME NULL COMMENT '送達時間',
    opened_date DATETIME NULL COMMENT '首次開啟時間',
    clicked_date DATETIME NULL COMMENT '首次點擊時間',
    acknowledged_date DATETIME NULL COMMENT '確認時間',
    expires_date DATETIME NULL COMMENT '訊息到期時間',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '發送嘗試次數',
    message_status VARCHAR(30) NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED已建立;QUEUED已排隊;SENDING發送中;SENT已送出;DELIVERED已送達;OPENED已開啟;CLICKED已點擊;ACKNOWLEDGED已確認;FAILED失敗;BOUNCED退信;EXPIRED過期;CANCELLED取消;SUPPRESSED抑制',
    last_error_code VARCHAR(100) NULL COMMENT '最後錯誤代碼',
    last_error_message TEXT NULL COMMENT '最後錯誤訊息',
    CONSTRAINT uk_nm_request_recipient_channel UNIQUE (notification_request_sid, notification_recipient_sid, channel_type),
    INDEX idx_nm_request_sid (notification_request_sid),
    INDEX idx_nm_recipient_sid (notification_recipient_sid),
    INDEX idx_nm_provider_sid (provider_sid),
    INDEX idx_nm_template_sid (template_sid),
    INDEX idx_nm_provider_message_id (provider_message_id),
    INDEX idx_nm_channel_type (channel_type),
    INDEX idx_nm_scheduled_date (scheduled_date),
    INDEX idx_nm_sent_date (sent_date),
    INDEX idx_nm_status (message_status),
    CHECK (attempt_count >= 0),
    CHECK (expires_date IS NULL OR scheduled_date IS NULL OR expires_date >= scheduled_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='實際Email、簡訊、LINE、推播與Webhook訊息';

CREATE TABLE IF NOT EXISTS nc_message_attachment (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '訊息附件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    message_sid VARCHAR(32) NOT NULL COMMENT '實際訊息序號',
    attachment_name VARCHAR(500) NOT NULL COMMENT '附件名稱',
    file_sid VARCHAR(32) NOT NULL COMMENT 'FileDB檔案序號',
    mime_type VARCHAR(200) NULL COMMENT 'MIME類型',
    file_size_bytes BIGINT UNSIGNED NULL COMMENT '檔案大小',
    inline_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否內嵌',
    content_id VARCHAR(200) NULL COMMENT '內嵌Content ID',
    INDEX idx_nma_message_sid (message_sid),
    INDEX idx_nma_file_sid (file_sid),
    CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Email與通訊訊息附件';

CREATE TABLE IF NOT EXISTS nc_outbound_queue (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '發送佇列序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    message_sid VARCHAR(32) NOT NULL COMMENT '實際訊息序號',
    provider_sid VARCHAR(32) NULL COMMENT '通訊供應商序號',
    queue_priority INT NOT NULL DEFAULT 100 COMMENT '佇列優先權，數字越小越優先',
    available_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '可處理時間',
    locked_by_worker VARCHAR(200) NULL COMMENT '鎖定Worker',
    locked_date DATETIME NULL COMMENT '鎖定時間',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '處理次數',
    max_attempts INT NOT NULL DEFAULT 3 COMMENT '最大處理次數',
    next_retry_date DATETIME NULL COMMENT '下次重試時間',
    queue_status VARCHAR(20) NOT NULL DEFAULT 'READY' COMMENT 'READY待處理;LOCKED已鎖定;PROCESSING處理中;RETRY待重試;COMPLETED完成;DEAD_LETTER死信;CANCELLED取消',
    last_error_code VARCHAR(100) NULL COMMENT '最後錯誤代碼',
    last_error_message TEXT NULL COMMENT '最後錯誤訊息',
    CONSTRAINT uk_noq_message_sid UNIQUE (message_sid),
    INDEX idx_noq_provider_sid (provider_sid),
    INDEX idx_noq_priority_available (queue_priority, available_date),
    INDEX idx_noq_locked_date (locked_date),
    INDEX idx_noq_next_retry_date (next_retry_date),
    INDEX idx_noq_status (queue_status),
    CHECK (queue_priority >= 0),
    CHECK (attempt_count >= 0),
    CHECK (max_attempts > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知發送工作佇列';

CREATE TABLE IF NOT EXISTS nc_delivery_attempt (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '訊息發送嘗試序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    message_sid VARCHAR(32) NOT NULL COMMENT '實際訊息序號',
    provider_sid VARCHAR(32) NULL COMMENT '通訊供應商序號',
    attempt_no INT NOT NULL COMMENT '嘗試次數',
    request_date DATETIME NOT NULL COMMENT '發送請求時間',
    response_date DATETIME NULL COMMENT '供應商回覆時間',
    request_payload JSON NULL COMMENT '發送請求Payload',
    response_payload JSON NULL COMMENT '供應商回覆Payload',
    http_status_code INT NULL COMMENT 'HTTP狀態碼',
    provider_status_code VARCHAR(100) NULL COMMENT '供應商狀態碼',
    provider_message_id VARCHAR(300) NULL COMMENT '供應商訊息ID',
    success_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否成功',
    retryable_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可重試',
    error_code VARCHAR(100) NULL COMMENT '錯誤代碼',
    error_message TEXT NULL COMMENT '錯誤訊息',
    duration_ms INT NULL COMMENT '處理毫秒',
    CONSTRAINT uk_nda_message_attempt UNIQUE (message_sid, attempt_no),
    INDEX idx_nda_message_sid (message_sid),
    INDEX idx_nda_provider_sid (provider_sid),
    INDEX idx_nda_request_date (request_date),
    INDEX idx_nda_provider_message_id (provider_message_id),
    INDEX idx_nda_success_mark (success_mark),
    INDEX idx_nda_retryable_mark (retryable_mark),
    CHECK (attempt_no > 0),
    CHECK (duration_ms IS NULL OR duration_ms >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='每次通知供應商發送請求與回覆';

CREATE TABLE IF NOT EXISTS nc_delivery_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '訊息送達事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    message_sid VARCHAR(32) NULL COMMENT '實際訊息序號',
    provider_sid VARCHAR(32) NULL COMMENT '通訊供應商序號',
    provider_message_id VARCHAR(300) NULL COMMENT '供應商訊息ID',
    event_type VARCHAR(30) NOT NULL COMMENT 'ACCEPTED接受;SENT送出;DELIVERED送達;OPENED開啟;CLICKED點擊;BOUNCED退信;FAILED失敗;UNSUBSCRIBED退訂;COMPLAINT申訴;ACKNOWLEDGED確認;OTHER',
    event_date DATETIME NOT NULL COMMENT '事件時間',
    endpoint_value VARCHAR(1000) NULL COMMENT '收件端點快照',
    event_data JSON NULL COMMENT '供應商事件資料',
    source_event_id VARCHAR(300) NULL COMMENT '供應商事件ID',
    processed_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已處理',
    processed_date DATETIME NULL COMMENT '處理時間',
    UNIQUE KEY uk_nde_source_event_id (source_event_id),
    INDEX idx_nde_message_sid (message_sid),
    INDEX idx_nde_provider_sid (provider_sid),
    INDEX idx_nde_provider_message_id (provider_message_id),
    INDEX idx_nde_event_type (event_type),
    INDEX idx_nde_event_date (event_date),
    INDEX idx_nde_processed_mark (processed_mark)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='送達、開啟、點擊、退信與退訂回呼事件';

CREATE TABLE IF NOT EXISTS nc_bounce_suppression (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '退信抑制序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音',
    endpoint_value VARCHAR(1000) NOT NULL COMMENT '被抑制端點',
    endpoint_hash VARCHAR(255) NOT NULL COMMENT '端點雜湊',
    suppression_type VARCHAR(30) NOT NULL COMMENT 'HARD_BOUNCE永久退信;SOFT_BOUNCE暫時退信;COMPLAINT申訴;UNSUBSCRIBED退訂;INVALID無效;MANUAL人工',
    suppression_reason VARCHAR(1000) NULL COMMENT '抑制原因',
    source_message_sid VARCHAR(32) NULL COMMENT '來源訊息序號',
    source_provider_sid VARCHAR(32) NULL COMMENT '來源供應商序號',
    effective_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效時間',
    expiry_date DATETIME NULL COMMENT '抑制到期時間',
    suppression_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE生效;EXPIRED到期;REMOVED解除',
    UNIQUE KEY uk_nbs_channel_endpoint_hash (channel_type, endpoint_hash),
    INDEX idx_nbs_suppression_type (suppression_type),
    INDEX idx_nbs_source_message_sid (source_message_sid),
    INDEX idx_nbs_expiry_date (expiry_date),
    INDEX idx_nbs_status (suppression_status),
    CHECK (expiry_date IS NULL OR expiry_date >= effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退信、申訴、退訂與無效端點抑制清單';

CREATE TABLE IF NOT EXISTS nc_unsubscribe_token (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '退訂Token序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工',
    subject_sid VARCHAR(32) NOT NULL COMMENT '退訂主體序號',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播',
    message_category VARCHAR(50) NOT NULL COMMENT 'MARKETING行銷;TRANSACTION交易;PROJECT專案;OTHER',
    token_hash VARCHAR(255) NOT NULL COMMENT '退訂Token雜湊',
    issued_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '核發時間',
    expiry_date DATETIME NULL COMMENT '到期時間',
    used_date DATETIME NULL COMMENT '使用時間',
    token_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;USED已使用;EXPIRED到期;REVOKED撤銷',
    UNIQUE KEY uk_nut_token_hash (token_hash),
    INDEX idx_nut_subject (subject_type, subject_sid),
    INDEX idx_nut_channel_type (channel_type),
    INDEX idx_nut_message_category (message_category),
    INDEX idx_nut_expiry_date (expiry_date),
    INDEX idx_nut_status (token_status),
    CHECK (expiry_date IS NULL OR expiry_date >= issued_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通訊與行銷退訂連結Token';

CREATE TABLE IF NOT EXISTS nc_webhook_subscription (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT 'Webhook訂閱序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    subscription_no VARCHAR(100) NOT NULL COMMENT '訂閱編號',
    subscriber_name VARCHAR(300) NOT NULL COMMENT '訂閱系統名稱',
    subscriber_system VARCHAR(100) NOT NULL COMMENT '訂閱系統代碼',
    endpoint_url VARCHAR(1000) NOT NULL COMMENT 'Webhook端點',
    secret_reference_sid VARCHAR(32) NULL COMMENT 'SecretVaultDB簽章密鑰參照',
    event_patterns JSON NOT NULL COMMENT '訂閱事件規則',
    header_template JSON NULL COMMENT '自訂Header',
    payload_version VARCHAR(50) NOT NULL DEFAULT '1.0' COMMENT 'Payload版本',
    retry_policy_sid VARCHAR(32) NULL COMMENT '重試政策序號',
    timeout_seconds INT NOT NULL DEFAULT 30 COMMENT '連線逾時秒數',
    effective_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效時間',
    expiry_date DATETIME NULL COMMENT '到期時間',
    subscription_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;PAUSED暫停;DISABLED停用;EXPIRED到期',
    CONSTRAINT uk_nws_subscription_no UNIQUE (subscription_no),
    INDEX idx_nws_subscriber_system (subscriber_system),
    INDEX idx_nws_retry_policy_sid (retry_policy_sid),
    INDEX idx_nws_status (subscription_status),
    CHECK (timeout_seconds > 0),
    CHECK (expiry_date IS NULL OR expiry_date >= effective_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='外部系統Webhook事件訂閱';

CREATE TABLE IF NOT EXISTS nc_webhook_delivery (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT 'Webhook投遞序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    webhook_subscription_sid VARCHAR(32) NOT NULL COMMENT 'Webhook訂閱序號',
    notification_request_sid VARCHAR(32) NULL COMMENT '通知請求序號',
    source_event_id VARCHAR(100) NOT NULL COMMENT '來源事件ID',
    event_code VARCHAR(120) NOT NULL COMMENT '事件代碼',
    payload_data JSON NOT NULL COMMENT 'Webhook Payload',
    signature_value VARCHAR(500) NULL COMMENT '簽章值',
    scheduled_date DATETIME NULL COMMENT '預定投遞時間',
    sent_date DATETIME NULL COMMENT '實際投遞時間',
    response_date DATETIME NULL COMMENT '回覆時間',
    http_status_code INT NULL COMMENT 'HTTP狀態碼',
    response_body LONGTEXT NULL COMMENT '回覆內容',
    attempt_count INT NOT NULL DEFAULT 0 COMMENT '嘗試次數',
    next_retry_date DATETIME NULL COMMENT '下次重試時間',
    delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待投遞;SENDING投遞中;SUCCESS成功;RETRY待重試;FAILED失敗;DEAD_LETTER死信;CANCELLED取消',
    CONSTRAINT uk_nwd_subscription_event UNIQUE (webhook_subscription_sid, source_event_id),
    INDEX idx_nwd_subscription_sid (webhook_subscription_sid),
    INDEX idx_nwd_notification_request_sid (notification_request_sid),
    INDEX idx_nwd_event_code (event_code),
    INDEX idx_nwd_scheduled_date (scheduled_date),
    INDEX idx_nwd_next_retry_date (next_retry_date),
    INDEX idx_nwd_status (delivery_status),
    CHECK (attempt_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Webhook事件投遞與重試';

CREATE TABLE IF NOT EXISTS nc_digest_queue (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知摘要佇列序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'USER使用者;PARTY對象;CUSTOMER客戶;PARTNER合作夥伴;EMPLOYEE員工',
    subject_sid VARCHAR(32) NOT NULL COMMENT '摘要收件主體序號',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;PORTAL站內通知',
    digest_mode VARCHAR(20) NOT NULL COMMENT 'HOURLY每小時;DAILY每日;WEEKLY每週',
    digest_period_start DATETIME NOT NULL COMMENT '摘要期間開始',
    digest_period_end DATETIME NOT NULL COMMENT '摘要期間結束',
    notification_count INT NOT NULL DEFAULT 0 COMMENT '通知數量',
    notification_request_sids JSON NOT NULL COMMENT '通知請求序號集合',
    scheduled_send_date DATETIME NOT NULL COMMENT '預定摘要發送時間',
    message_sid VARCHAR(32) NULL COMMENT '產生的實際訊息序號',
    digest_status VARCHAR(20) NOT NULL DEFAULT 'COLLECTING' COMMENT 'COLLECTING收集中;READY可發送;SENDING發送中;SENT已送出;FAILED失敗;CANCELLED取消',
    CONSTRAINT uk_ndq_subject_period UNIQUE (subject_type, subject_sid, channel_type, digest_mode, digest_period_start, digest_period_end),
    INDEX idx_ndq_subject (subject_type, subject_sid),
    INDEX idx_ndq_scheduled_send_date (scheduled_send_date),
    INDEX idx_ndq_message_sid (message_sid),
    INDEX idx_ndq_status (digest_status),
    CHECK (digest_period_end > digest_period_start),
    CHECK (notification_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='每小時、每日與每週通知摘要';

CREATE TABLE IF NOT EXISTS nc_provider_usage_daily (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '供應商每日用量序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    provider_sid VARCHAR(32) NOT NULL COMMENT '通訊供應商序號',
    usage_date DATE NOT NULL COMMENT '使用日期',
    channel_type VARCHAR(30) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音',
    request_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '請求數',
    success_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功數',
    failure_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '失敗數',
    delivered_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '送達數',
    opened_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '開啟數',
    clicked_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '點擊數',
    bounced_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '退信數',
    unsubscribed_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '退訂數',
    unit_cost DECIMAL(20,8) NOT NULL DEFAULT 0 COMMENT '單位成本',
    total_cost DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '總成本',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    average_latency_ms DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '平均延遲毫秒',
    CONSTRAINT uk_npud_provider_date_channel UNIQUE (provider_sid, usage_date, channel_type),
    INDEX idx_npud_provider_sid (provider_sid),
    INDEX idx_npud_usage_date (usage_date),
    INDEX idx_npud_channel_type (channel_type),
    CHECK (unit_cost >= 0),
    CHECK (total_cost >= 0),
    CHECK (average_latency_ms >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通訊供應商每日流量、成本與成效';

CREATE TABLE IF NOT EXISTS nc_kpi_snapshot (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知通訊KPI序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    snapshot_no VARCHAR(100) NOT NULL COMMENT '快照編號',
    company_sid VARCHAR(32) NULL COMMENT '公司序號',
    channel_type VARCHAR(30) NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;VOICE語音;PORTAL站內通知',
    period_start_date DATE NOT NULL COMMENT '期間開始日',
    period_end_date DATE NOT NULL COMMENT '期間結束日',
    request_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '通知請求數',
    message_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '訊息數',
    sent_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '送出數',
    delivered_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '送達數',
    opened_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '開啟數',
    clicked_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '點擊數',
    acknowledged_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '確認數',
    failed_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '失敗數',
    bounced_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '退信數',
    suppressed_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '抑制數',
    unsubscribe_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '退訂數',
    delivery_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '送達率',
    open_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '開啟率',
    click_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '點擊率',
    failure_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '失敗率',
    average_delivery_seconds DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '平均送達秒數',
    retry_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '重試次數',
    dead_letter_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '死信數',
    total_cost DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '總通訊成本',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    snapshot_status VARCHAR(20) NOT NULL DEFAULT 'FINAL' COMMENT 'DRAFT草稿;FINAL正式;ARCHIVED封存',
    CONSTRAINT uk_nks_snapshot_no UNIQUE (snapshot_no),
    INDEX idx_nks_company_sid (company_sid),
    INDEX idx_nks_channel_type (channel_type),
    INDEX idx_nks_period (period_start_date, period_end_date),
    INDEX idx_nks_status (snapshot_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (delivery_rate BETWEEN 0 AND 100),
    CHECK (open_rate BETWEEN 0 AND 100),
    CHECK (click_rate BETWEEN 0 AND 100),
    CHECK (failure_rate BETWEEN 0 AND 100),
    CHECK (average_delivery_seconds >= 0),
    CHECK (total_cost >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='跨管道通知送達、開啟、失敗、重試與成本KPI';

CREATE TABLE IF NOT EXISTS nc_status_history (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知通訊狀態歷程序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type VARCHAR(30) NOT NULL COMMENT 'PROVIDER;RETRY_POLICY;TEMPLATE;ENDPOINT;PREFERENCE;CONSENT;REQUEST;RECIPIENT;MESSAGE;QUEUE;SUPPRESSION;UNSUBSCRIBE;WEBHOOK_SUBSCRIPTION;WEBHOOK_DELIVERY;DIGEST',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    old_status VARCHAR(30) NULL COMMENT '原狀態',
    new_status VARCHAR(30) NOT NULL COMMENT '新狀態',
    event_code VARCHAR(100) NULL COMMENT '觸發事件代碼',
    operator_user_sid VARCHAR(32) NULL COMMENT '操作人員序號',
    reason TEXT NULL COMMENT '原因說明',
    correlation_id VARCHAR(100) NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_ncsh_entity (entity_type, entity_sid),
    INDEX idx_ncsh_new_status (new_status),
    INDEX idx_ncsh_event_code (event_code),
    INDEX idx_ncsh_operator_user_sid (operator_user_sid),
    INDEX idx_ncsh_correlation_id (correlation_id),
    INDEX idx_ncsh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知範本、發送、退信、退訂與Webhook狀態歷程';

CREATE TABLE IF NOT EXISTS nc_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '通知通訊領域事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type VARCHAR(30) NOT NULL COMMENT 'PROVIDER;TEMPLATE;ENDPOINT;PREFERENCE;CONSENT;REQUEST;RECIPIENT;MESSAGE;QUEUE;DELIVERY;SUPPRESSION;UNSUBSCRIBE;WEBHOOK;DIGEST;KPI',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    event_code VARCHAR(120) NOT NULL COMMENT '事件代碼',
    event_version INT NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data JSON NULL COMMENT '事件內容',
    source_event_id VARCHAR(100) NULL COMMENT '來源事件ID',
    correlation_id VARCHAR(100) NULL COMMENT '關聯識別碼',
    causation_id VARCHAR(100) NULL COMMENT '因果事件ID',
    outbox_event_sid VARCHAR(32) NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date DATETIME NULL COMMENT '處理時間',
    error_message TEXT NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_nce_source_event_id (source_event_id),
    INDEX idx_nce_entity (entity_type, entity_sid),
    INDEX idx_nce_event_code (event_code),
    INDEX idx_nce_correlation_id (correlation_id),
    INDEX idx_nce_outbox_event_sid (outbox_event_sid),
    INDEX idx_nce_status (process_status),
    INDEX idx_nce_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知、發送、退信、退訂與Webhook領域事件';
SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
