attrib -h *.vs
attrib -h .vs\B2bOrder\v17\.suo
del/Q .vs\B2bOrder\v17\INI\*.*
del/Q .vs\B2bOrder\v17\*.*
del/Q .vs\B2bOrder\v17\.suo
del/Q .vs\B2bOrder\config
del/Q .vs\B2bOrder\DesignTimeBuild
rd .vs\B2bOrder\config
rd .vs\B2bOrder\DesignTimeBuild
rd .vs\B2bOrder\v17
rd .vs\B2bOrder
rd .vs

attrib -h .vs\B2bOrder\v17\.suo
del/Q .vs\B2bOrder\v17\INI\*.*
del/Q .vs\B2bOrder\v17\.suo
del/Q .vs\B2bOrder\FileContentIndex\*.*
rd .vs\B2bOrder\FileContentIndex
rd .vs\B2bOrder\v17
rd .vs\B2bOrder
rd .vs

del/Q B2bOrder\obj\Debug\net8.0\Razor\Views\Messageboard\*.*
del/Q B2bOrder\obj\Debug\net8.0\Razor\Views\Shared\*.*
del/Q B2bOrder\obj\Debug\net8.0\Razor\Views\Home\*.*
del/Q B2bOrder\obj\Debug\net8.0\Razor\Views\*.*
del/Q B2bOrder\obj\Debug\net8.0\staticwebassets\*.*
del/Q B2bOrder\obj\Debug\net8.0\ref\*.*
del/Q B2bOrder\obj\Debug\net8.0\refint\*.*
del/Q B2bOrder\obj\Debug\net8.0\*.*
del/Q B2bOrder\obj\*.*
del/Q B2bOrder\bin\Debug\net8.0\Settings\*.*
del/Q B2bOrder\bin\Debug\net8.0\x86\*.*
del/Q B2bOrder\bin\Debug\net8.0\x64\*.*
del/Q B2bOrder\bin\Debug\net8.0\INI\*.*
del/Q B2bOrder\bin\Debug\net8.0\Log\*.*
del/Q B2bOrder\bin\Debug\net8.0\cs\*.*
del/Q B2bOrder\bin\Debug\net8.0\de\*.*
del/Q B2bOrder\bin\Debug\net8.0\es\*.*
del/Q B2bOrder\bin\Debug\net8.0\fr\*.*
del/Q B2bOrder\bin\Debug\net8.0\it\*.*
del/Q B2bOrder\bin\Debug\net8.0\ja\*.*
del/Q B2bOrder\bin\Debug\net8.0\ko\*.*
del/Q B2bOrder\bin\Debug\net8.0\pl\*.*
del/Q B2bOrder\bin\Debug\net8.0\pt-BR\*.*
del/Q B2bOrder\bin\Debug\net8.0\refs\*.*
del/Q B2bOrder\bin\Debug\net8.0\ru\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.0\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netstandard2.0\*.*
del/Q B2bOrder\bin\Debug\net8.0\runtimes\win-x64\native\*.*
del/Q B2bOrder\bin\Debug\net8.0\tr\*.*
del/Q B2bOrder\bin\Debug\net8.0\zh-Hans\*.*
del/Q B2bOrder\bin\Debug\net8.0\zh-Hant\*.*
del/Q B2bOrder\bin\Debug\net8.0\*.*
del/Q B2bOrder\bin\Debug\Settings\*.*
del/Q B2bOrder\bin\Debug\x86\*.*
del/Q B2bOrder\bin\Debug\x64\*.*
del/Q B2bOrder\bin\Debug\INI\*.*
del/Q B2bOrder\bin\Debug\Log\*.*
del/Q B2bOrder\bin\Debug\*.*
del/Q B2bOrder\bin\Debug\*.trc
del/Q B2bOrder\bin\Debug\net8.0\*.trc

del/Q B2bOrder\obj\Release\net8.0\Razor\Views\Messageboard\*.*
del/Q B2bOrder\obj\Release\net8.0\Razor\Views\Shared\*.*
del/Q B2bOrder\obj\Release\net8.0\Razor\Views\Home\*.*
del/Q B2bOrder\obj\Release\net8.0\Razor\Views\*.*
del/Q B2bOrder\obj\Release\net8.0\staticwebassets\*.*
del/Q B2bOrder\obj\Release\net8.0\ref\*.*
del/Q B2bOrder\obj\Release\net8.0\refint\*.*
del/Q B2bOrder\obj\Release\net8.0\*.*
del/Q B2bOrder\obj\*.*
del/Q B2bOrder\bin\Release\net8.0\*.*
del/Q B2bOrder\bin\Release\net8.0\Settings\*.*
del/Q B2bOrder\bin\Release\net8.0\x86\*.*
del/Q B2bOrder\bin\Release\net8.0\x64\*.*
del/Q B2bOrder\bin\Release\net8.0\INI\*.*
del/Q B2bOrder\bin\Release\net8.0\Log\*.*
del/Q B2bOrder\bin\Release\net8.0\cs\*.*
del/Q B2bOrder\bin\Release\net8.0\de\*.*
del/Q B2bOrder\bin\Release\net8.0\es\*.*
del/Q B2bOrder\bin\Release\net8.0\fr\*.*
del/Q B2bOrder\bin\Release\net8.0\it\*.*
del/Q B2bOrder\bin\Release\net8.0\ja\*.*
del/Q B2bOrder\bin\Release\net8.0\ko\*.*
del/Q B2bOrder\bin\Release\net8.0\pl\*.*
del/Q B2bOrder\bin\Release\net8.0\pt-BR\*.*
del/Q B2bOrder\bin\Release\net8.0\refs\*.*
del/Q B2bOrder\bin\Release\net8.0\ru\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.0\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\win\lib\netstandard2.0\*.*
del/Q B2bOrder\bin\Release\net8.0\runtimes\win-x64\native\*.*
del/Q B2bOrder\bin\Release\net8.0\tr\*.*
del/Q B2bOrder\bin\Release\net8.0\zh-Hans\*.*
del/Q B2bOrder\bin\Release\net8.0\zh-Hant\*.*
del/Q B2bOrder\bin\Release\net8.0\*.*
del/Q B2bOrder\bin\Release\Settings\*.*
del/Q B2bOrder\bin\Release\x86\*.*
del/Q B2bOrder\bin\Release\x64\*.*
del/Q B2bOrder\bin\Release\INI\*.*
del/Q B2bOrder\bin\Release\Log\*.*
del/Q B2bOrder\bin\Release\*.*
del/Q B2bOrder\bin\Release\*.trc
del/Q B2bOrder\bin\Release\net8.0\*.trc

rd B2bOrder\obj\Debug\net8.0\Razor\Views\Messageboard
rd B2bOrder\obj\Debug\net8.0\Razor\Views\Shared
rd B2bOrder\obj\Debug\net8.0\Razor\Views\Home
rd B2bOrder\obj\Debug\net8.0\Razor\Views
rd B2bOrder\obj\Debug\net8.0\Razor
rd B2bOrder\obj\Debug\net8.0\staticwebassets
rd B2bOrder\obj\Debug\net8.0\ref
rd B2bOrder\obj\Debug\net8.0\refint
rd B2bOrder\obj\Debug\net8.0
rd B2bOrder\obj\Debug
rd B2bOrder\obj
rd B2bOrder\bin\Debug\net8.0
rd B2bOrder\bin\Debug\net8.0\Settings
rd B2bOrder\bin\Debug\net8.0\INI
rd B2bOrder\bin\Debug\net8.0\Log
rd B2bOrder\bin\Debug\net8.0\x86
rd B2bOrder\bin\Debug\net8.0\x64
rd B2bOrder\bin\Debug\net8.0\cs
rd B2bOrder\bin\Debug\net8.0\de
rd B2bOrder\bin\Debug\net8.0\es
rd B2bOrder\bin\Debug\net8.0\fr
rd B2bOrder\bin\Debug\net8.0\it
rd B2bOrder\bin\Debug\net8.0\ja
rd B2bOrder\bin\Debug\net8.0\ko
rd B2bOrder\bin\Debug\net8.0\pl
rd B2bOrder\bin\Debug\net8.0\pt-BR
rd B2bOrder\bin\Debug\net8.0\refs
rd B2bOrder\bin\Debug\net8.0\ru
rd B2bOrder\bin\Debug\net8.0\runtimes\unix\lib\netcoreapp2.1
rd B2bOrder\bin\Debug\net8.0\runtimes\unix\lib
rd B2bOrder\bin\Debug\net8.0\runtimes\unix
rd B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.1
rd B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.0
rd B2bOrder\bin\Debug\net8.0\runtimes\win\lib\netstandard2.0
rd B2bOrder\bin\Debug\net8.0\runtimes\win\lib
rd B2bOrder\bin\Debug\net8.0\runtimes\win
rd B2bOrder\bin\Debug\net8.0\runtimes\win-x64\native
rd B2bOrder\bin\Debug\net8.0\runtimes\win-x64
rd B2bOrder\bin\Debug\net8.0\runtimes
rd B2bOrder\bin\Debug\net8.0\tr
rd B2bOrder\bin\Debug\net8.0\zh-Hans
rd B2bOrder\bin\Debug\net8.0\zh-Hant
rd B2bOrder\bin\Debug\net8.0
rd B2bOrder\bin\Debug\Settings
rd B2bOrder\bin\Debug\INI
rd B2bOrder\bin\Debug\Log
rd B2bOrder\bin\Debug\x86
rd B2bOrder\bin\Debug\x64
rd B2bOrder\bin\Debug

rd B2bOrder\obj\Release\net8.0\Razor\Views\Messageboard
rd B2bOrder\obj\Release\net8.0\Razor\Views\Shared
rd B2bOrder\obj\Release\net8.0\Razor\Views\Home
rd B2bOrder\obj\Release\net8.0\Razor\Views
rd B2bOrder\obj\Release\net8.0\Razor
rd B2bOrder\obj\Release\net8.0\staticwebassets
rd B2bOrder\obj\Release\net8.0
rd B2bOrder\obj\Release
rd B2bOrder\obj
rd B2bOrder\bin\Release\net8.0\Settings
rd B2bOrder\bin\Release\net8.0\INI
rd B2bOrder\bin\Release\net8.0\Log
rd B2bOrder\bin\Release\net8.0\x86
rd B2bOrder\bin\Release\net8.0\x64
rd B2bOrder\bin\Release\net8.0\cs
rd B2bOrder\bin\Release\net8.0\de
rd B2bOrder\bin\Release\net8.0\es
rd B2bOrder\bin\Release\net8.0\fr
rd B2bOrder\bin\Release\net8.0\it
rd B2bOrder\bin\Release\net8.0\ja
rd B2bOrder\bin\Release\net8.0\ko
rd B2bOrder\bin\Release\net8.0\pl
rd B2bOrder\bin\Release\net8.0\pt-BR
rd B2bOrder\bin\Release\net8.0\refs
rd B2bOrder\bin\Release\net8.0\ru
rd B2bOrder\bin\Release\net8.0\runtimes\unix\lib\netcoreapp2.1
rd B2bOrder\bin\Release\net8.0\runtimes\unix\lib
rd B2bOrder\bin\Release\net8.0\runtimes\unix
rd B2bOrder\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.1
rd B2bOrder\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.0
rd B2bOrder\bin\Release\net8.0\runtimes\win\lib\netstandard2.0
rd B2bOrder\bin\Release\net8.0\runtimes\win\lib
rd B2bOrder\bin\Release\net8.0\runtimes\win
rd B2bOrder\bin\Release\net8.0\runtimes\win-x64\native
rd B2bOrder\bin\Release\net8.0\runtimes\win-x64
rd B2bOrder\bin\Release\net8.0\runtimes
rd B2bOrder\bin\Release\net8.0\tr
rd B2bOrder\bin\Release\net8.0\zh-Hans
rd B2bOrder\bin\Release\net8.0\zh-Hant
rd B2bOrder\bin\Release\net8.0
rd B2bOrder\bin\Release\Settings
rd B2bOrder\bin\Release\INI
rd B2bOrder\bin\Release\Log
rd B2bOrder\bin\Release\x86
rd B2bOrder\bin\Release\x64


del/Q B2bOrder\bin\Release\publish\Settings\*.*
del/Q B2bOrder\bin\Release\publish\x86\*.*
del/Q B2bOrder\bin\Release\publish\x64\*.*
del/Q B2bOrder\bin\Release\publish\INI\*.*
del/Q B2bOrder\bin\Release\publish\Log\*.*
del/Q B2bOrder\bin\Release\publish\cs\*.*
del/Q B2bOrder\bin\Release\publish\de\*.*
del/Q B2bOrder\bin\Release\publish\es\*.*
del/Q B2bOrder\bin\Release\publish\fr\*.*
del/Q B2bOrder\bin\Release\publish\it\*.*
del/Q B2bOrder\bin\Release\publish\ja\*.*
del/Q B2bOrder\bin\Release\publish\ko\*.*
del/Q B2bOrder\bin\Release\publish\pl\*.*
del/Q B2bOrder\bin\Release\publish\pt-BR\*.*
del/Q B2bOrder\bin\Release\publish\refs\*.*
del/Q B2bOrder\bin\Release\publish\ru\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\win\lib\netcoreapp2.1\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\win\lib\netcoreapp2.0\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\win\lib\netstandard2.0\*.*
del/Q B2bOrder\bin\Release\publish\runtimes\win-x64\native\*.*
del/Q B2bOrder\bin\Release\publish\tr\*.*
del/Q B2bOrder\bin\Release\publish\zh-Hans\*.*
del/Q B2bOrder\bin\Release\publish\zh-Hant\*.*
del/Q B2bOrder\bin\Release\publish\*.*
del/Q B2bOrder\bin\Release\publish\Settings\*.*
del/Q B2bOrder\bin\Release\publish\x86\*.*
del/Q B2bOrder\bin\Release\publish\x64\*.*
del/Q B2bOrder\bin\Release\publish\INI\*.*
del/Q B2bOrder\bin\Release\publish\Log\*.*
del/Q B2bOrder\bin\Release\publish\*.*
del/Q B2bOrder\bin\Release\publish\*.trc
del/Q B2bOrder\bin\Release\publish\wwwroot\css\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\js\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist\css\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist\js\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery\dist\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery\css\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery\js\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\dist\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\css\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\js\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\dist\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\css\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\js\*.*
del/Q B2bOrder\bin\Release\publish\wwwroot\*.*

rd B2bOrder\bin\Release\publish\Settings
rd B2bOrder\bin\Release\publish\INI
rd B2bOrder\bin\Release\publish\Log
rd B2bOrder\bin\Release\publish\x86
rd B2bOrder\bin\Release\publish\x64
rd B2bOrder\bin\Release\publish\cs
rd B2bOrder\bin\Release\publish\de
rd B2bOrder\bin\Release\publish\es
rd B2bOrder\bin\Release\publish\fr
rd B2bOrder\bin\Release\publish\it
rd B2bOrder\bin\Release\publish\ja
rd B2bOrder\bin\Release\publish\ko
rd B2bOrder\bin\Release\publish\pl
rd B2bOrder\bin\Release\publish\pt-BR
rd B2bOrder\bin\Release\publish\refs
rd B2bOrder\bin\Release\publish\ru
rd B2bOrder\bin\Release\publish\runtimes\unix\lib\netcoreapp2.1
rd B2bOrder\bin\Release\publish\runtimes\unix\lib
rd B2bOrder\bin\Release\publish\runtimes\unix
rd B2bOrder\bin\Release\publish\runtimes\win\lib\netcoreapp2.1
rd B2bOrder\bin\Release\publish\runtimes\win\lib\netcoreapp2.0
rd B2bOrder\bin\Release\publish\runtimes\win\lib\netstandard2.0
rd B2bOrder\bin\Release\publish\runtimes\win\lib
rd B2bOrder\bin\Release\publish\runtimes\win
rd B2bOrder\bin\Release\publish\runtimes\win-x64\native
rd B2bOrder\bin\Release\publish\runtimes\win-x64
rd B2bOrder\bin\Release\publish\runtimes
rd B2bOrder\bin\Release\publish\tr
rd B2bOrder\bin\Release\publish\zh-Hans
rd B2bOrder\bin\Release\publish\zh-Hant
rd B2bOrder\bin\Release\publish
rd B2bOrder\bin\Release\publish\Settings
rd B2bOrder\bin\Release\publish\INI
rd B2bOrder\bin\Release\publish\Log
rd B2bOrder\bin\Release\publish\x86
rd B2bOrder\bin\Release\publish\x64
rd B2bOrder\bin\Release\publish\wwwroot\css
rd B2bOrder\bin\Release\publish\wwwroot\js
rd B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist\css
rd B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist\js
rd B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap\dist
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery\css
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery\js
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery\dist
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\css
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\js
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation\dist
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\css
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\js
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\dist
rd B2bOrder\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive
rd B2bOrder\bin\Release\publish\wwwroot\lib\bootstrap
rd B2bOrder\bin\Release\publish\wwwroot\lib
rd B2bOrder\bin\Release\publish\wwwroot
rd B2bOrder\bin\Release\publish

rd B2bOrder\bin\Release

rd B2bOrder\bin

del/Q B2bOrder\obj\Debug\TempPE\*.*
del/Q B2bOrder\obj\Debug\*.*
del/Q B2bOrder\obj\Release\TempPE\*.*
del/Q B2bOrder\obj\Release\*.*

rd B2bOrder\obj\Debug\TempPE
rd B2bOrder\obj\Debug
rd B2bOrder\obj\Release\TempPE
rd B2bOrder\obj\Release
rd B2bOrder\obj