namespace B2bOrder.Resources.eCommerce
{
    /// <summary>
    /// InventoryDB V2 Shared Core Schema
    /// 設計目標：
    /// 1. 同時支援 Shopping Platform 與 Construction ERP
    /// 2. 支援庫存帳、異動、預留、批號、序號、調撥、盤點、報廢、領料、退料與材料耗用
    /// 3. 倉庫與儲位由 MasterDB 提供；Item與變體由 PIM/MIMDB 提供
    /// 4. 採購收貨由 PurchaseDB 提供；銷售與訂單由 Shopping/OMS/SalesDB 提供
    /// 5. 專案、工地、WBS、成本中心與承包商等維度皆以 sid 關聯
    /// 6. nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼
    /// 7. avalible：Y可用；W停用；D刪除
    /// 8. 適用 MySQL 8.x / InnoDB / utf8mb4
    /// </summary>
    internal static class InventoryDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- 01. 庫存政策與Item庫存設定
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_policy (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存政策序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    policy_code             VARCHAR(100)                        NOT NULL COMMENT '政策代碼',
    policy_name             VARCHAR(200)                        NOT NULL COMMENT '政策名稱',
    company_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB公司序號',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT 'MasterDB倉庫序號',
    negative_stock_allowed  TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否允許負庫存',
    reservation_required    TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '出庫是否需先預留',
    batch_strategy          VARCHAR(30)                         NOT NULL DEFAULT 'FIFO' COMMENT 'FIFO先進先出;FEFO先到期先出;LIFO後進先出;MANUAL人工',
    cost_method             VARCHAR(30)                         NOT NULL DEFAULT 'MOVING_AVERAGE' COMMENT 'MOVING_AVERAGE移動平均;STANDARD標準;FIFO;SPECIFIC特定辨認',
    over_issue_rate         DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '允許超領率百分比',
    short_issue_rate        DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '允許短領率百分比',
    policy_status           VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ip_policy_code UNIQUE (policy_code),
    INDEX idx_ip_company_sid (company_sid),
    INDEX idx_ip_warehouse_sid (warehouse_sid),
    INDEX idx_ip_status (policy_status),
    INDEX idx_ip_avalible (avalible),
    CHECK (over_issue_rate >= 0),
    CHECK (short_issue_rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存管理政策';

CREATE TABLE IF NOT EXISTS inv_item_setting (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT 'Item庫存設定序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'PIM/MIMDB Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT 'PIM/MIMDB變體序號',
    company_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB公司序號',
    inventory_unit_sid      VARCHAR(32)                         NOT NULL COMMENT 'MasterDB庫存單位序號',
    issue_unit_sid          VARCHAR(32)                             NULL COMMENT 'MasterDB發料單位序號',
    receipt_unit_sid        VARCHAR(32)                             NULL COMMENT 'MasterDB收料單位序號',
    batch_control           TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否批號控管',
    serial_control          TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否序號控管',
    expiry_control          TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否效期控管',
    quality_hold_required   TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '收貨後是否先進待驗',
    safety_stock_qty        DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '安全庫存',
    reorder_point_qty       DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '再訂購點',
    reorder_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '建議補貨量',
    maximum_stock_qty       DECIMAL(20,6)                           NULL COMMENT '最大庫存',
    minimum_issue_qty       DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '最小發料量',
    issue_multiple_qty      DECIMAL(20,6)                       NOT NULL DEFAULT 1 COMMENT '發料倍數',
    setting_status          VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_iis_item_variant_company UNIQUE (item_sid, variant_sid, company_sid),
    INDEX idx_iis_item_sid (item_sid),
    INDEX idx_iis_variant_sid (variant_sid),
    INDEX idx_iis_company_sid (company_sid),
    INDEX idx_iis_status (setting_status),
    INDEX idx_iis_avalible (avalible),
    CHECK (safety_stock_qty >= 0),
    CHECK (reorder_point_qty >= 0),
    CHECK (reorder_qty >= 0),
    CHECK (maximum_stock_qty IS NULL OR maximum_stock_qty >= 0),
    CHECK (minimum_issue_qty >= 0),
    CHECK (issue_multiple_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Item庫存控制設定';

-- =========================================================
-- 02. 即時庫存帳
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_stock_balance (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存餘額序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '儲位序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    owner_party_sid         VARCHAR(32)                             NULL COMMENT '庫存所有Party序號',
    stock_status            VARCHAR(20)                         NOT NULL DEFAULT 'AVAILABLE' COMMENT 'AVAILABLE可用;RESERVED預留;QUALITY_HOLD待驗;BLOCKED凍結;DAMAGED損壞;IN_TRANSIT在途',
    on_hand_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '現有量',
    reserved_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '預留量',
    allocated_qty           DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已配貨量',
    available_qty           DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '可用量',
    in_transit_qty          DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '在途量',
    quality_hold_qty        DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '待驗量',
    blocked_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '凍結量',
    damaged_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '損壞量',
    average_cost            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '移動平均成本',
    total_cost              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '庫存總成本',
    last_movement_date      DATETIME                                NULL COMMENT '最後異動時間',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    CONSTRAINT uk_isb_balance UNIQUE (company_sid, warehouse_sid, location_sid, item_sid, variant_sid, batch_sid, project_sid, site_sid, wbs_sid, owner_party_sid, stock_status),
    INDEX idx_isb_company_sid (company_sid),
    INDEX idx_isb_warehouse_sid (warehouse_sid),
    INDEX idx_isb_location_sid (location_sid),
    INDEX idx_isb_item_sid (item_sid),
    INDEX idx_isb_variant_sid (variant_sid),
    INDEX idx_isb_batch_sid (batch_sid),
    INDEX idx_isb_project_sid (project_sid),
    INDEX idx_isb_site_sid (site_sid),
    INDEX idx_isb_wbs_sid (wbs_sid),
    INDEX idx_isb_owner_party_sid (owner_party_sid),
    INDEX idx_isb_stock_status (stock_status),
    INDEX idx_isb_last_movement_date (last_movement_date),
    CHECK (on_hand_qty >= 0),
    CHECK (reserved_qty >= 0),
    CHECK (allocated_qty >= 0),
    CHECK (available_qty >= 0),
    CHECK (in_transit_qty >= 0),
    CHECK (quality_hold_qty >= 0),
    CHECK (blocked_qty >= 0),
    CHECK (damaged_qty >= 0),
    CHECK (average_cost >= 0),
    CHECK (total_cost >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='即時庫存餘額';

CREATE TABLE IF NOT EXISTS inv_stock_summary (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存彙總序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    total_on_hand_qty       DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '總現有量',
    total_reserved_qty      DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '總預留量',
    total_available_qty     DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '總可用量',
    total_in_transit_qty    DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '總在途量',
    total_quality_hold_qty  DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '總待驗量',
    total_stock_value       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '總庫存價值',
    last_calculated_date    DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最後彙總時間',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    CONSTRAINT uk_iss_company_item_variant UNIQUE (company_sid, item_sid, variant_sid),
    INDEX idx_iss_company_sid (company_sid),
    INDEX idx_iss_item_sid (item_sid),
    INDEX idx_iss_variant_sid (variant_sid),
    INDEX idx_iss_last_calculated_date (last_calculated_date),
    CHECK (total_on_hand_qty >= 0),
    CHECK (total_reserved_qty >= 0),
    CHECK (total_available_qty >= 0),
    CHECK (total_in_transit_qty >= 0),
    CHECK (total_quality_hold_qty >= 0),
    CHECK (total_stock_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Item公司層級庫存彙總';

-- =========================================================
-- 03. 批號與序號
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_batch (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '批號序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_no                VARCHAR(150)                        NOT NULL COMMENT '批號',
    supplier_party_sid      VARCHAR(32)                             NULL COMMENT '供應商Party序號',
    manufacturer_party_sid  VARCHAR(32)                             NULL COMMENT '製造商Party序號',
    manufacture_date        DATE                                    NULL COMMENT '製造日期',
    expiry_date             DATE                                    NULL COMMENT '有效期限',
    receipt_sid             VARCHAR(32)                             NULL COMMENT '來源收貨單序號',
    inspection_sid          VARCHAR(32)                             NULL COMMENT '來源驗收單序號',
    quality_status          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待驗;PASS合格;FAIL不合格;CONDITIONAL有條件;EXPIRED過期',
    batch_status            VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;BLOCKED凍結;CONSUMED用罄;EXPIRED過期;RECALLED召回',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ib_item_variant_batch UNIQUE (item_sid, variant_sid, batch_no),
    INDEX idx_ib_item_sid (item_sid),
    INDEX idx_ib_variant_sid (variant_sid),
    INDEX idx_ib_supplier_party_sid (supplier_party_sid),
    INDEX idx_ib_manufacturer_party_sid (manufacturer_party_sid),
    INDEX idx_ib_expiry_date (expiry_date),
    INDEX idx_ib_quality_status (quality_status),
    INDEX idx_ib_batch_status (batch_status),
    INDEX idx_ib_avalible (avalible),
    CHECK (expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date >= manufacture_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存批號';

CREATE TABLE IF NOT EXISTS inv_serial (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '序號序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    serial_no               VARCHAR(300)                        NOT NULL COMMENT '序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT '目前倉庫序號',
    location_sid            VARCHAR(32)                             NULL COMMENT '目前儲位序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '目前專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '目前工地序號',
    owner_party_sid         VARCHAR(32)                             NULL COMMENT '目前所有Party序號',
    receipt_sid             VARCHAR(32)                             NULL COMMENT '來源收貨單序號',
    warranty_start_date     DATE                                    NULL COMMENT '保固開始日',
    warranty_end_date       DATE                                    NULL COMMENT '保固結束日',
    serial_status           VARCHAR(30)                         NOT NULL DEFAULT 'IN_STOCK' COMMENT 'IN_STOCK庫存中;RESERVED已預留;ISSUED已發出;INSTALLED已安裝;SOLD已售出;RETURNED已退回;SCRAPPED報廢;LOST遺失',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_is_serial_no UNIQUE (serial_no),
    INDEX idx_is_item_sid (item_sid),
    INDEX idx_is_variant_sid (variant_sid),
    INDEX idx_is_batch_sid (batch_sid),
    INDEX idx_is_warehouse_sid (warehouse_sid),
    INDEX idx_is_location_sid (location_sid),
    INDEX idx_is_project_sid (project_sid),
    INDEX idx_is_site_sid (site_sid),
    INDEX idx_is_owner_party_sid (owner_party_sid),
    INDEX idx_is_status (serial_status),
    INDEX idx_is_avalible (avalible),
    CHECK (warranty_end_date IS NULL OR warranty_start_date IS NULL OR warranty_end_date >= warranty_start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存序號';

-- =========================================================
-- 04. 庫存異動與成本
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_transaction (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存異動序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    transaction_no          VARCHAR(100)                        NOT NULL COMMENT '異動編號',
    transaction_type        VARCHAR(30)                         NOT NULL COMMENT 'RECEIPT入庫;ISSUE出庫;TRANSFER_IN調入;TRANSFER_OUT調出;ADJUST_IN調增;ADJUST_OUT調減;RETURN_IN退料入庫;RETURN_OUT退貨出庫;CONSUME耗用;SCRAP報廢',
    transaction_date        DATETIME                            NOT NULL COMMENT '異動時間',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '儲位序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    serial_sid              VARCHAR(32)                             NULL COMMENT '序號序號',
    quantity                DECIMAL(20,6)                       NOT NULL COMMENT '異動數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    unit_cost               DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '單位成本',
    total_cost              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '總成本',
    stock_status_from       VARCHAR(20)                             NULL COMMENT '原庫存狀態',
    stock_status_to         VARCHAR(20)                             NULL COMMENT '新庫存狀態',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    owner_party_sid         VARCHAR(32)                             NULL COMMENT '庫存所有Party序號',
    source_type             VARCHAR(50)                         NOT NULL COMMENT 'PURCHASE_RECEIPT採購收貨;SALES_ORDER銷售訂單;OMS;TRANSFER調撥;COUNT盤點;ISSUE_REQUEST領料;RETURN退料;MANUAL人工;OTHER',
    source_sid              VARCHAR(32)                         NOT NULL COMMENT '來源資料序號',
    source_line_sid         VARCHAR(32)                             NULL COMMENT '來源明細序號',
    operator_user_sid       VARCHAR(32)                             NULL COMMENT '操作人員序號',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    CONSTRAINT uk_it_transaction_no UNIQUE (transaction_no),
    INDEX idx_it_transaction_type (transaction_type),
    INDEX idx_it_transaction_date (transaction_date),
    INDEX idx_it_company_sid (company_sid),
    INDEX idx_it_warehouse_sid (warehouse_sid),
    INDEX idx_it_location_sid (location_sid),
    INDEX idx_it_item_sid (item_sid),
    INDEX idx_it_variant_sid (variant_sid),
    INDEX idx_it_batch_sid (batch_sid),
    INDEX idx_it_serial_sid (serial_sid),
    INDEX idx_it_project_sid (project_sid),
    INDEX idx_it_site_sid (site_sid),
    INDEX idx_it_wbs_sid (wbs_sid),
    INDEX idx_it_source (source_type, source_sid),
    INDEX idx_it_correlation_id (correlation_id),
    CHECK (quantity > 0),
    CHECK (unit_cost >= 0),
    CHECK (total_cost >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='不可變庫存異動流水帳';

CREATE TABLE IF NOT EXISTS inv_cost_layer (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '成本層序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    source_transaction_sid  VARCHAR(32)                         NOT NULL COMMENT '來源入庫異動序號',
    original_qty            DECIMAL(20,6)                       NOT NULL COMMENT '原始數量',
    remaining_qty           DECIMAL(20,6)                       NOT NULL COMMENT '剩餘數量',
    unit_cost               DECIMAL(20,6)                       NOT NULL COMMENT '單位成本',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    cost_date               DATETIME                            NOT NULL COMMENT '成本日期',
    layer_status            VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN可用;PARTIAL部分使用;CLOSED用罄;ADJUSTED已調整',
    INDEX idx_icl_company_sid (company_sid),
    INDEX idx_icl_warehouse_sid (warehouse_sid),
    INDEX idx_icl_item_sid (item_sid),
    INDEX idx_icl_variant_sid (variant_sid),
    INDEX idx_icl_batch_sid (batch_sid),
    INDEX idx_icl_source_transaction_sid (source_transaction_sid),
    INDEX idx_icl_cost_date (cost_date),
    INDEX idx_icl_status (layer_status),
    CHECK (original_qty > 0),
    CHECK (remaining_qty >= 0),
    CHECK (remaining_qty <= original_qty),
    CHECK (unit_cost >= 0),
    CHECK (exchange_rate > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='FIFO與特定辨認成本層';

-- =========================================================
-- 05. 預留與配貨
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_reservation (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存預留序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    reservation_no          VARCHAR(100)                        NOT NULL COMMENT '預留編號',
    source_type             VARCHAR(30)                         NOT NULL COMMENT 'SHOPPING_ORDER商城訂單;OMS_ORDER;SALES_ORDER銷售單;PROJECT專案;ISSUE_REQUEST領料;MANUAL人工',
    source_sid              VARCHAR(32)                         NOT NULL COMMENT '來源資料序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    requested_date          DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申請時間',
    expiry_date             DATETIME                                NULL COMMENT '預留到期時間',
    priority                VARCHAR(20)                         NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW低;NORMAL一般;HIGH高;URGENT緊急',
    reservation_status      VARCHAR(30)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;PARTIAL部分預留;RESERVED已預留;ALLOCATED已配貨;RELEASED已釋放;EXPIRED過期;CANCELLED取消;FAILED失敗',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    CONSTRAINT uk_ir_reservation_no UNIQUE (reservation_no),
    INDEX idx_ir_source (source_type, source_sid),
    INDEX idx_ir_company_sid (company_sid),
    INDEX idx_ir_project_sid (project_sid),
    INDEX idx_ir_site_sid (site_sid),
    INDEX idx_ir_expiry_date (expiry_date),
    INDEX idx_ir_priority (priority),
    INDEX idx_ir_status (reservation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存預留主檔';

CREATE TABLE IF NOT EXISTS inv_reservation_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存預留明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    reservation_nid         BIGINT UNSIGNED                     NOT NULL COMMENT '預留主檔流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    source_line_sid         VARCHAR(32)                             NULL COMMENT '來源明細序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    requested_qty           DECIMAL(20,6)                       NOT NULL COMMENT '需求數量',
    reserved_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已預留數量',
    allocated_qty           DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已配貨數量',
    released_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已釋放數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    preferred_warehouse_sid VARCHAR(32)                             NULL COMMENT '優先倉庫序號',
    preferred_location_sid  VARCHAR(32)                             NULL COMMENT '優先儲位序號',
    batch_strategy          VARCHAR(30)                             NULL COMMENT '批號策略',
    reservation_status      VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;PARTIAL部分預留;RESERVED已預留;ALLOCATED已配貨;RELEASED已釋放;FAILED失敗',
    CONSTRAINT fk_iri_reservation
        FOREIGN KEY (reservation_nid) REFERENCES inv_reservation(nid),
    CONSTRAINT uk_iri_reservation_line UNIQUE (reservation_nid, line_no),
    INDEX idx_iri_reservation_nid (reservation_nid),
    INDEX idx_iri_source_line_sid (source_line_sid),
    INDEX idx_iri_item_sid (item_sid),
    INDEX idx_iri_variant_sid (variant_sid),
    INDEX idx_iri_preferred_warehouse_sid (preferred_warehouse_sid),
    INDEX idx_iri_status (reservation_status),
    CHECK (line_no > 0),
    CHECK (requested_qty > 0),
    CHECK (reserved_qty >= 0),
    CHECK (allocated_qty >= 0),
    CHECK (released_qty >= 0),
    CHECK (reserved_qty <= requested_qty),
    CHECK (allocated_qty <= reserved_qty),
    CHECK (released_qty <= reserved_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存預留明細';

CREATE TABLE IF NOT EXISTS inv_allocation (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存配貨序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    reservation_item_sid    VARCHAR(32)                         NOT NULL COMMENT '預留明細序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '配貨倉庫序號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '配貨儲位序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    serial_sid              VARCHAR(32)                             NULL COMMENT '序號序號',
    allocated_qty           DECIMAL(20,6)                       NOT NULL COMMENT '配貨數量',
    allocation_status       VARCHAR(20)                         NOT NULL DEFAULT 'ALLOCATED' COMMENT 'ALLOCATED已配貨;PICKED已揀取;ISSUED已出庫;RELEASED已釋放',
    picked_date             DATETIME                                NULL COMMENT '揀取時間',
    issued_date             DATETIME                                NULL COMMENT '出庫時間',
    CONSTRAINT uk_ia_allocation UNIQUE (reservation_item_sid, warehouse_sid, location_sid, batch_sid, serial_sid),
    INDEX idx_ia_reservation_item_sid (reservation_item_sid),
    INDEX idx_ia_warehouse_sid (warehouse_sid),
    INDEX idx_ia_location_sid (location_sid),
    INDEX idx_ia_batch_sid (batch_sid),
    INDEX idx_ia_serial_sid (serial_sid),
    INDEX idx_ia_status (allocation_status),
    CHECK (allocated_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存配貨明細';

-- =========================================================
-- 06. 調撥
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_transfer (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存調撥序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    transfer_no             VARCHAR(100)                        NOT NULL COMMENT '調撥單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    from_warehouse_sid      VARCHAR(32)                         NOT NULL COMMENT '來源倉庫序號',
    to_warehouse_sid        VARCHAR(32)                         NOT NULL COMMENT '目的倉庫序號',
    from_project_sid        VARCHAR(32)                             NULL COMMENT '來源專案序號',
    to_project_sid          VARCHAR(32)                             NULL COMMENT '目的專案序號',
    from_site_sid           VARCHAR(32)                             NULL COMMENT '來源工地序號',
    to_site_sid             VARCHAR(32)                             NULL COMMENT '目的工地序號',
    request_date            DATE                                NOT NULL COMMENT '申請日期',
    planned_ship_date       DATE                                    NULL COMMENT '預計出庫日',
    planned_receive_date    DATE                                    NULL COMMENT '預計到貨日',
    requester_user_sid      VARCHAR(32)                         NOT NULL COMMENT '申請人員序號',
    transfer_status         VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;PICKING揀料中;SHIPPED已出庫;IN_TRANSIT在途;PARTIAL_RECEIVED部分收貨;RECEIVED已完成;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    shipped_date            DATETIME                                NULL COMMENT '出庫時間',
    received_date           DATETIME                                NULL COMMENT '收貨完成時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_itr_transfer_no UNIQUE (transfer_no),
    INDEX idx_itr_company_sid (company_sid),
    INDEX idx_itr_from_warehouse_sid (from_warehouse_sid),
    INDEX idx_itr_to_warehouse_sid (to_warehouse_sid),
    INDEX idx_itr_from_project_sid (from_project_sid),
    INDEX idx_itr_to_project_sid (to_project_sid),
    INDEX idx_itr_status (transfer_status),
    INDEX idx_itr_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_itr_avalible (avalible),
    CHECK (from_warehouse_sid <> to_warehouse_sid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存調撥單';

CREATE TABLE IF NOT EXISTS inv_transfer_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '調撥明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    transfer_nid            BIGINT UNSIGNED                     NOT NULL COMMENT '調撥單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    request_qty             DECIMAL(20,6)                       NOT NULL COMMENT '申請數量',
    shipped_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已出庫數量',
    received_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已收貨數量',
    damaged_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '運損數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    from_location_sid       VARCHAR(32)                             NULL COMMENT '來源儲位序號',
    to_location_sid         VARCHAR(32)                             NULL COMMENT '目的儲位序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待處理;PARTIAL部分;SHIPPED已出庫;RECEIVED已完成;CANCELLED取消',
    CONSTRAINT fk_itri_transfer
        FOREIGN KEY (transfer_nid) REFERENCES inv_transfer(nid),
    CONSTRAINT uk_itri_transfer_line UNIQUE (transfer_nid, line_no),
    INDEX idx_itri_transfer_nid (transfer_nid),
    INDEX idx_itri_item_sid (item_sid),
    INDEX idx_itri_variant_sid (variant_sid),
    INDEX idx_itri_from_location_sid (from_location_sid),
    INDEX idx_itri_to_location_sid (to_location_sid),
    INDEX idx_itri_batch_sid (batch_sid),
    INDEX idx_itri_status (item_status),
    CHECK (line_no > 0),
    CHECK (request_qty > 0),
    CHECK (shipped_qty >= 0),
    CHECK (received_qty >= 0),
    CHECK (damaged_qty >= 0),
    CHECK (shipped_qty <= request_qty),
    CHECK (received_qty + damaged_qty <= shipped_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存調撥明細';

-- =========================================================
-- 07. 盤點與調整
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_stock_count (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '盤點單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    count_no                VARCHAR(100)                        NOT NULL COMMENT '盤點單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    count_type              VARCHAR(30)                         NOT NULL COMMENT 'FULL全面;CYCLE循環;SPOT抽盤;PROJECT專案;LOCATION儲位',
    freeze_stock            TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '盤點期間是否凍結庫存',
    planned_date            DATE                                NOT NULL COMMENT '計畫盤點日',
    start_date              DATETIME                                NULL COMMENT '開始時間',
    completed_date          DATETIME                                NULL COMMENT '完成時間',
    responsible_user_sid    VARCHAR(32)                         NOT NULL COMMENT '負責人員序號',
    count_status            VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;PLANNED已排程;COUNTING盤點中;REVIEW待覆核;APPROVED核准;ADJUSTED已調整;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_isc_count_no UNIQUE (count_no),
    INDEX idx_isc_company_sid (company_sid),
    INDEX idx_isc_warehouse_sid (warehouse_sid),
    INDEX idx_isc_project_sid (project_sid),
    INDEX idx_isc_site_sid (site_sid),
    INDEX idx_isc_count_type (count_type),
    INDEX idx_isc_planned_date (planned_date),
    INDEX idx_isc_status (count_status),
    INDEX idx_isc_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_isc_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存盤點單';

CREATE TABLE IF NOT EXISTS inv_stock_count_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '盤點明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    stock_count_nid         BIGINT UNSIGNED                     NOT NULL COMMENT '盤點單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '儲位序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    system_qty              DECIMAL(20,6)                       NOT NULL COMMENT '系統數量',
    counted_qty             DECIMAL(20,6)                           NULL COMMENT '實盤數量',
    variance_qty            DECIMAL(20,6)                           NULL COMMENT '差異數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    count_user_sid          VARCHAR(32)                             NULL COMMENT '盤點人員序號',
    recount_user_sid        VARCHAR(32)                             NULL COMMENT '複盤人員序號',
    count_date              DATETIME                                NULL COMMENT '盤點時間',
    variance_reason_code    VARCHAR(50)                             NULL COMMENT '差異原因代碼',
    variance_note           TEXT                                    NULL COMMENT '差異說明',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待盤;COUNTED已盤;RECOUNT複盤;CONFIRMED確認;ADJUSTED已調整',
    CONSTRAINT fk_isci_stock_count
        FOREIGN KEY (stock_count_nid) REFERENCES inv_stock_count(nid),
    CONSTRAINT uk_isci_count_line UNIQUE (stock_count_nid, line_no),
    INDEX idx_isci_stock_count_nid (stock_count_nid),
    INDEX idx_isci_location_sid (location_sid),
    INDEX idx_isci_item_sid (item_sid),
    INDEX idx_isci_variant_sid (variant_sid),
    INDEX idx_isci_batch_sid (batch_sid),
    INDEX idx_isci_status (item_status),
    CHECK (line_no > 0),
    CHECK (system_qty >= 0),
    CHECK (counted_qty IS NULL OR counted_qty >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存盤點明細';

CREATE TABLE IF NOT EXISTS inv_adjustment (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存調整序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    adjustment_no           VARCHAR(100)                        NOT NULL COMMENT '調整單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    adjustment_type         VARCHAR(30)                         NOT NULL COMMENT 'COUNT盤點;DAMAGE損壞;LOSS短少;FOUND盤盈;QUALITY品質;COST成本;STATUS狀態;MANUAL人工',
    source_type             VARCHAR(30)                             NULL COMMENT 'COUNT盤點;INSPECTION驗收;SYSTEM系統;MANUAL人工',
    source_sid              VARCHAR(32)                             NULL COMMENT '來源資料序號',
    adjustment_date         DATETIME                            NOT NULL COMMENT '調整時間',
    reason_code             VARCHAR(50)                         NOT NULL COMMENT '調整原因代碼',
    reason                  TEXT                                    NULL COMMENT '調整原因',
    adjustment_status       VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;POSTED已過帳;REJECTED駁回;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    posted_date             DATETIME                                NULL COMMENT '過帳時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_iad_adjustment_no UNIQUE (adjustment_no),
    INDEX idx_iad_company_sid (company_sid),
    INDEX idx_iad_warehouse_sid (warehouse_sid),
    INDEX idx_iad_adjustment_type (adjustment_type),
    INDEX idx_iad_source (source_type, source_sid),
    INDEX idx_iad_adjustment_date (adjustment_date),
    INDEX idx_iad_status (adjustment_status),
    INDEX idx_iad_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_iad_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存調整單';

CREATE TABLE IF NOT EXISTS inv_adjustment_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存調整明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    adjustment_nid          BIGINT UNSIGNED                     NOT NULL COMMENT '調整單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '儲位序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    serial_sid              VARCHAR(32)                             NULL COMMENT '序號序號',
    before_qty              DECIMAL(20,6)                       NOT NULL COMMENT '調整前數量',
    adjustment_qty          DECIMAL(20,6)                       NOT NULL COMMENT '調整數量，可正可負',
    after_qty               DECIMAL(20,6)                       NOT NULL COMMENT '調整後數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    before_unit_cost        DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '調整前單位成本',
    after_unit_cost         DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '調整後單位成本',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_iadi_adjustment
        FOREIGN KEY (adjustment_nid) REFERENCES inv_adjustment(nid),
    CONSTRAINT uk_iadi_adjustment_line UNIQUE (adjustment_nid, line_no),
    INDEX idx_iadi_adjustment_nid (adjustment_nid),
    INDEX idx_iadi_location_sid (location_sid),
    INDEX idx_iadi_item_sid (item_sid),
    INDEX idx_iadi_variant_sid (variant_sid),
    INDEX idx_iadi_batch_sid (batch_sid),
    INDEX idx_iadi_serial_sid (serial_sid),
    INDEX idx_iadi_project_sid (project_sid),
    INDEX idx_iadi_wbs_sid (wbs_sid),
    CHECK (line_no > 0),
    CHECK (before_qty >= 0),
    CHECK (after_qty >= 0),
    CHECK (before_unit_cost >= 0),
    CHECK (after_unit_cost >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存調整明細';

-- =========================================================
-- 08. 領料、退料與耗用
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_issue_request (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '領料申請序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    issue_no                VARCHAR(100)                        NOT NULL COMMENT '領料單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '發料倉庫序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    contractor_party_sid    VARCHAR(32)                             NULL COMMENT '領料承包商或工班Party序號',
    requester_user_sid      VARCHAR(32)                         NOT NULL COMMENT '申請人員序號',
    request_date            DATE                                NOT NULL COMMENT '申請日期',
    required_date           DATE                                    NULL COMMENT '需求日期',
    issue_purpose           VARCHAR(30)                         NOT NULL COMMENT 'SALES銷售;PROJECT專案;CONSTRUCTION施工;MAINTENANCE維修;PRODUCTION生產;SAMPLE樣品;OTHER',
    reservation_sid         VARCHAR(32)                             NULL COMMENT '庫存預留序號',
    issue_status            VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;ALLOCATED已配料;PARTIAL_ISSUED部分發料;ISSUED已發料;CANCELLED取消;CLOSED結案',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    issued_date             DATETIME                                NULL COMMENT '發料完成時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_iir_issue_no UNIQUE (issue_no),
    INDEX idx_iir_company_sid (company_sid),
    INDEX idx_iir_warehouse_sid (warehouse_sid),
    INDEX idx_iir_project_sid (project_sid),
    INDEX idx_iir_site_sid (site_sid),
    INDEX idx_iir_wbs_sid (wbs_sid),
    INDEX idx_iir_contractor_party_sid (contractor_party_sid),
    INDEX idx_iir_requester_user_sid (requester_user_sid),
    INDEX idx_iir_reservation_sid (reservation_sid),
    INDEX idx_iir_status (issue_status),
    INDEX idx_iir_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_iir_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='領料與工地發料申請';

CREATE TABLE IF NOT EXISTS inv_issue_request_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '領料明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    issue_request_nid       BIGINT UNSIGNED                     NOT NULL COMMENT '領料申請流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    request_qty             DECIMAL(20,6)                       NOT NULL COMMENT '申請數量',
    approved_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '核准數量',
    issued_qty              DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已發料數量',
    returned_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已退料數量',
    consumed_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已耗用數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    preferred_location_sid  VARCHAR(32)                             NULL COMMENT '優先儲位序號',
    budget_item_sid         VARCHAR(32)                             NULL COMMENT 'BudgetCostDB預算明細序號',
    contract_item_sid       VARCHAR(32)                             NULL COMMENT 'ContractDB合約明細序號',
    bom_component_sid       VARCHAR(32)                             NULL COMMENT 'PIM/MIMDB BOM組件序號',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待處理;PARTIAL部分發料;ISSUED已發料;RETURNED已退料;CONSUMED已耗用;CANCELLED取消',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_iiri_issue_request
        FOREIGN KEY (issue_request_nid) REFERENCES inv_issue_request(nid),
    CONSTRAINT uk_iiri_issue_line UNIQUE (issue_request_nid, line_no),
    INDEX idx_iiri_issue_request_nid (issue_request_nid),
    INDEX idx_iiri_item_sid (item_sid),
    INDEX idx_iiri_variant_sid (variant_sid),
    INDEX idx_iiri_budget_item_sid (budget_item_sid),
    INDEX idx_iiri_contract_item_sid (contract_item_sid),
    INDEX idx_iiri_bom_component_sid (bom_component_sid),
    INDEX idx_iiri_status (item_status),
    CHECK (line_no > 0),
    CHECK (request_qty > 0),
    CHECK (approved_qty >= 0),
    CHECK (issued_qty >= 0),
    CHECK (returned_qty >= 0),
    CHECK (consumed_qty >= 0),
    CHECK (approved_qty <= request_qty),
    CHECK (issued_qty <= approved_qty),
    CHECK (returned_qty <= issued_qty),
    CHECK (consumed_qty <= issued_qty - returned_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='領料申請明細';

CREATE TABLE IF NOT EXISTS inv_material_return (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '退料單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    return_no               VARCHAR(100)                        NOT NULL COMMENT '退料單號',
    issue_request_sid       VARCHAR(32)                         NOT NULL COMMENT '來源領料單序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '退回倉庫序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    contractor_party_sid    VARCHAR(32)                             NULL COMMENT '退料承包商或工班Party序號',
    return_date             DATETIME                            NOT NULL COMMENT '退料時間',
    return_reason_code      VARCHAR(50)                         NOT NULL COMMENT '退料原因代碼',
    return_status           VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;RECEIVED已收料;INSPECTED已檢查;POSTED已入庫;CANCELLED取消',
    receiver_user_sid       VARCHAR(32)                             NULL COMMENT '收料人員序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_imr_return_no UNIQUE (return_no),
    INDEX idx_imr_issue_request_sid (issue_request_sid),
    INDEX idx_imr_warehouse_sid (warehouse_sid),
    INDEX idx_imr_project_sid (project_sid),
    INDEX idx_imr_site_sid (site_sid),
    INDEX idx_imr_wbs_sid (wbs_sid),
    INDEX idx_imr_contractor_party_sid (contractor_party_sid),
    INDEX idx_imr_return_date (return_date),
    INDEX idx_imr_status (return_status),
    INDEX idx_imr_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工程與一般退料單';

CREATE TABLE IF NOT EXISTS inv_material_return_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '退料明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    material_return_nid     BIGINT UNSIGNED                     NOT NULL COMMENT '退料單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    issue_request_item_sid  VARCHAR(32)                         NOT NULL COMMENT '來源領料明細序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    return_qty              DECIMAL(20,6)                       NOT NULL COMMENT '退料數量',
    accepted_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '可再使用數量',
    damaged_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '損壞數量',
    scrap_qty               DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '報廢數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    target_location_sid     VARCHAR(32)                             NULL COMMENT '退回儲位序號',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待收;ACCEPTED已接受;PARTIAL部分接受;REJECTED拒收;POSTED已入庫',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_imri_return
        FOREIGN KEY (material_return_nid) REFERENCES inv_material_return(nid),
    CONSTRAINT uk_imri_return_line UNIQUE (material_return_nid, line_no),
    INDEX idx_imri_return_nid (material_return_nid),
    INDEX idx_imri_issue_request_item_sid (issue_request_item_sid),
    INDEX idx_imri_item_sid (item_sid),
    INDEX idx_imri_variant_sid (variant_sid),
    INDEX idx_imri_batch_sid (batch_sid),
    INDEX idx_imri_target_location_sid (target_location_sid),
    INDEX idx_imri_status (item_status),
    CHECK (line_no > 0),
    CHECK (return_qty > 0),
    CHECK (accepted_qty >= 0),
    CHECK (damaged_qty >= 0),
    CHECK (scrap_qty >= 0),
    CHECK (accepted_qty + damaged_qty + scrap_qty <= return_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退料明細';

CREATE TABLE IF NOT EXISTS inv_consumption (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '材料耗用序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    consumption_no          VARCHAR(100)                        NOT NULL COMMENT '耗用單號',
    issue_request_sid       VARCHAR(32)                             NULL COMMENT '來源領料單序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    contractor_party_sid    VARCHAR(32)                             NULL COMMENT '施工承包商或工班Party序號',
    consumption_date        DATETIME                            NOT NULL COMMENT '耗用時間',
    source_type             VARCHAR(30)                         NOT NULL COMMENT 'MANUAL人工;PROGRESS進度回報;WORK_ORDER工單;INSTALLATION安裝;SYSTEM系統',
    source_sid              VARCHAR(32)                             NULL COMMENT '來源資料序號',
    consumption_status      VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;POSTED已過帳;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    posted_date             DATETIME                                NULL COMMENT '過帳時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ic_consumption_no UNIQUE (consumption_no),
    INDEX idx_ic_issue_request_sid (issue_request_sid),
    INDEX idx_ic_company_sid (company_sid),
    INDEX idx_ic_project_sid (project_sid),
    INDEX idx_ic_site_sid (site_sid),
    INDEX idx_ic_wbs_sid (wbs_sid),
    INDEX idx_ic_contractor_party_sid (contractor_party_sid),
    INDEX idx_ic_consumption_date (consumption_date),
    INDEX idx_ic_source (source_type, source_sid),
    INDEX idx_ic_status (consumption_status),
    INDEX idx_ic_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_ic_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='材料實際耗用';

CREATE TABLE IF NOT EXISTS inv_consumption_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '材料耗用明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    consumption_nid         BIGINT UNSIGNED                     NOT NULL COMMENT '耗用主檔流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    issue_request_item_sid  VARCHAR(32)                             NULL COMMENT '來源領料明細序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    consumed_qty            DECIMAL(20,6)                       NOT NULL COMMENT '耗用數量',
    waste_qty               DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '耗損數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    unit_cost               DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '單位成本',
    total_cost              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '總成本',
    budget_item_sid         VARCHAR(32)                             NULL COMMENT 'BudgetCostDB預算明細序號',
    contract_item_sid       VARCHAR(32)                             NULL COMMENT 'ContractDB合約明細序號',
    bom_component_sid       VARCHAR(32)                             NULL COMMENT 'PIM/MIMDB BOM組件序號',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_ici_consumption
        FOREIGN KEY (consumption_nid) REFERENCES inv_consumption(nid),
    CONSTRAINT uk_ici_consumption_line UNIQUE (consumption_nid, line_no),
    INDEX idx_ici_consumption_nid (consumption_nid),
    INDEX idx_ici_issue_request_item_sid (issue_request_item_sid),
    INDEX idx_ici_item_sid (item_sid),
    INDEX idx_ici_variant_sid (variant_sid),
    INDEX idx_ici_batch_sid (batch_sid),
    INDEX idx_ici_budget_item_sid (budget_item_sid),
    INDEX idx_ici_contract_item_sid (contract_item_sid),
    INDEX idx_ici_bom_component_sid (bom_component_sid),
    CHECK (line_no > 0),
    CHECK (consumed_qty > 0),
    CHECK (waste_qty >= 0),
    CHECK (unit_cost >= 0),
    CHECK (total_cost >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='材料耗用明細';

-- =========================================================
-- 09. 報廢與召回
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_scrap (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '報廢單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    scrap_no                VARCHAR(100)                        NOT NULL COMMENT '報廢單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '倉庫序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    scrap_date              DATETIME                            NOT NULL COMMENT '報廢時間',
    reason_code             VARCHAR(50)                         NOT NULL COMMENT '報廢原因代碼',
    disposal_method         VARCHAR(30)                         NOT NULL COMMENT 'DISPOSE廢棄;RECYCLE回收;SELL出售;RETURN_SUPPLIER退供應商;OTHER',
    estimated_recovery_amount DECIMAL(20,4)                     NOT NULL DEFAULT 0 COMMENT '預估回收金額',
    scrap_status            VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;POSTED已過帳;DISPOSED已處置;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    disposed_date           DATETIME                                NULL COMMENT '完成處置時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_iscp_scrap_no UNIQUE (scrap_no),
    INDEX idx_iscp_company_sid (company_sid),
    INDEX idx_iscp_warehouse_sid (warehouse_sid),
    INDEX idx_iscp_project_sid (project_sid),
    INDEX idx_iscp_site_sid (site_sid),
    INDEX idx_iscp_scrap_date (scrap_date),
    INDEX idx_iscp_status (scrap_status),
    INDEX idx_iscp_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_iscp_avalible (avalible),
    CHECK (estimated_recovery_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存報廢單';

CREATE TABLE IF NOT EXISTS inv_scrap_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '報廢明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    scrap_nid               BIGINT UNSIGNED                     NOT NULL COMMENT '報廢單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    location_sid            VARCHAR(32)                         NOT NULL COMMENT '儲位序號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    serial_sid              VARCHAR(32)                             NULL COMMENT '序號序號',
    scrap_qty               DECIMAL(20,6)                       NOT NULL COMMENT '報廢數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    unit_cost               DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '單位成本',
    total_cost              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '報廢成本',
    recovery_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '回收金額',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_iscri_scrap
        FOREIGN KEY (scrap_nid) REFERENCES inv_scrap(nid),
    CONSTRAINT uk_iscri_scrap_line UNIQUE (scrap_nid, line_no),
    INDEX idx_iscri_scrap_nid (scrap_nid),
    INDEX idx_iscri_location_sid (location_sid),
    INDEX idx_iscri_item_sid (item_sid),
    INDEX idx_iscri_variant_sid (variant_sid),
    INDEX idx_iscri_batch_sid (batch_sid),
    INDEX idx_iscri_serial_sid (serial_sid),
    INDEX idx_iscri_project_sid (project_sid),
    INDEX idx_iscri_wbs_sid (wbs_sid),
    CHECK (line_no > 0),
    CHECK (scrap_qty > 0),
    CHECK (unit_cost >= 0),
    CHECK (total_cost >= 0),
    CHECK (recovery_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存報廢明細';

CREATE TABLE IF NOT EXISTS inv_recall (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '召回序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    recall_no               VARCHAR(100)                        NOT NULL COMMENT '召回編號',
    item_sid                VARCHAR(32)                         NOT NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    batch_sid               VARCHAR(32)                             NULL COMMENT '批號序號',
    supplier_party_sid      VARCHAR(32)                             NULL COMMENT '供應商Party序號',
    manufacturer_party_sid  VARCHAR(32)                             NULL COMMENT '製造商Party序號',
    recall_reason           TEXT                                NOT NULL COMMENT '召回原因',
    risk_level              VARCHAR(20)                         NOT NULL DEFAULT 'HIGH' COMMENT 'LOW低;MEDIUM中;HIGH高;CRITICAL嚴重',
    announced_date          DATETIME                            NOT NULL COMMENT '公告時間',
    effective_date          DATETIME                            NOT NULL COMMENT '生效時間',
    recall_status           VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'DRAFT草稿;ACTIVE生效;COMPLETED完成;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ircl_recall_no UNIQUE (recall_no),
    INDEX idx_ircl_item_sid (item_sid),
    INDEX idx_ircl_variant_sid (variant_sid),
    INDEX idx_ircl_batch_sid (batch_sid),
    INDEX idx_ircl_supplier_party_sid (supplier_party_sid),
    INDEX idx_ircl_risk_level (risk_level),
    INDEX idx_ircl_status (recall_status),
    INDEX idx_ircl_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_ircl_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批號與Item召回';

-- =========================================================
-- 10. 庫存事件與歷程
-- =========================================================

CREATE TABLE IF NOT EXISTS inv_status_history (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存狀態歷程序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'RESERVATION;TRANSFER;COUNT;ADJUSTMENT;ISSUE;RETURN;CONSUMPTION;SCRAP;RECALL;BATCH;SERIAL',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '實體序號',
    old_status              VARCHAR(30)                             NULL COMMENT '原狀態',
    new_status              VARCHAR(30)                         NOT NULL COMMENT '新狀態',
    event_code              VARCHAR(100)                            NULL COMMENT '觸發事件代碼',
    operator_user_sid       VARCHAR(32)                             NULL COMMENT '操作人員序號',
    reason                  TEXT                                    NULL COMMENT '原因說明',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_ish_entity (entity_type, entity_sid),
    INDEX idx_ish_new_status (new_status),
    INDEX idx_ish_event_code (event_code),
    INDEX idx_ish_operator_user_sid (operator_user_sid),
    INDEX idx_ish_correlation_id (correlation_id),
    INDEX idx_ish_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存狀態歷程';

CREATE TABLE IF NOT EXISTS inv_event (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '庫存事件序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'BALANCE;TRANSACTION;RESERVATION;TRANSFER;COUNT;ISSUE;RETURN;CONSUMPTION;SCRAP;RECALL',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '實體序號',
    event_code              VARCHAR(120)                        NOT NULL COMMENT '事件代碼',
    event_version           INT                                 NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data              JSON                                    NULL COMMENT '事件內容',
    source_event_id         VARCHAR(100)                            NULL COMMENT '來源事件ID',
    correlation_id          VARCHAR(100)                            NULL COMMENT '關聯識別碼',
    causation_id            VARCHAR(100)                            NULL COMMENT '因果事件ID',
    outbox_event_sid        VARCHAR(32)                             NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date          DATETIME                                NULL COMMENT '處理時間',
    error_message           TEXT                                    NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_ie_source_event_id (source_event_id),
    INDEX idx_ie_entity (entity_type, entity_sid),
    INDEX idx_ie_event_code (event_code),
    INDEX idx_ie_correlation_id (correlation_id),
    INDEX idx_ie_outbox_event_sid (outbox_event_sid),
    INDEX idx_ie_status (process_status),
    INDEX idx_ie_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='庫存領域事件';

SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
