namespace B2bOrder.Resources.eCommerce
{
    /// <summary>
    /// PurchaseDB V2 Shared Core Schema
    /// 設計目標：
    /// 1. 同時支援 Shopping Platform 與 Construction ERP
    /// 2. 支援請購、詢價、比價、採購單、交期、收貨、驗收、退貨與供應商績效
    /// 3. 預留公司、營運單位、部門、專案、成本中心、倉庫、工地、WBS、預算與合約維度
    /// 4. PartyDB 管理供應商與承包商；PIM/MIMDB 管理商品、材料、設備與服務
    /// 5. PricingDB 管理協議價與採購價格；InventoryDB 管理實際庫存
    /// 6. AccountingDB 管理應付帳款；WorkflowDB 管理簽核流程
    /// 7. nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼
    /// 8. avalible：Y可用；W停用；D刪除
    /// 9. 適用 MySQL 8.x / InnoDB / utf8mb4
    /// </summary>
    internal static class PurchaseDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- 01. 採購類型與政策
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_purchase_type (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購類型序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    purchase_type_code      VARCHAR(100)                        NOT NULL COMMENT '採購類型代碼',
    purchase_type_name      VARCHAR(200)                        NOT NULL COMMENT '採購類型名稱',
    purchase_category       VARCHAR(30)                         NOT NULL COMMENT 'MATERIAL材料;PRODUCT商品;EQUIPMENT設備;SERVICE服務;LABOR勞務;RENTAL租賃;SUBCONTRACT發包;GENERAL一般',
    approval_required       TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否需要簽核',
    receipt_required        TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否需要收貨',
    inspection_required     TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否需要驗收',
    inventory_effect        TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否影響庫存',
    contract_required       TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否需合約',
    budget_check_required   TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否需預算檢核',
    type_status             VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ppt_purchase_type_code UNIQUE (purchase_type_code),
    INDEX idx_ppt_category (purchase_category),
    INDEX idx_ppt_approval_required (approval_required),
    INDEX idx_ppt_budget_check_required (budget_check_required),
    INDEX idx_ppt_status (type_status),
    INDEX idx_ppt_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購類型';

CREATE TABLE IF NOT EXISTS pur_policy (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購政策序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    policy_code             VARCHAR(100)                        NOT NULL COMMENT '政策代碼',
    policy_name             VARCHAR(200)                        NOT NULL COMMENT '政策名稱',
    company_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB公司序號',
    purchase_type_sid       VARCHAR(32)                             NULL COMMENT '採購類型序號',
    minimum_quote_count     INT                                 NOT NULL DEFAULT 1 COMMENT '最低詢價家數',
    approval_amount         DECIMAL(20,4)                           NULL COMMENT '觸發簽核金額',
    tender_amount           DECIMAL(20,4)                           NULL COMMENT '觸發招標金額',
    single_source_allowed   TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否允許單一來源',
    emergency_allowed       TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否允許緊急採購',
    split_order_allowed     TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否允許拆單',
    over_receipt_rate       DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '允許超收率百分比',
    under_receipt_rate      DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '允許短收率百分比',
    price_variance_rate     DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '允許價格差異率百分比',
    policy_status           VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_pp_policy_code UNIQUE (policy_code),
    INDEX idx_pp_company_sid (company_sid),
    INDEX idx_pp_purchase_type_sid (purchase_type_sid),
    INDEX idx_pp_status (policy_status),
    INDEX idx_pp_avalible (avalible),
    CHECK (minimum_quote_count > 0),
    CHECK (approval_amount IS NULL OR approval_amount >= 0),
    CHECK (tender_amount IS NULL OR tender_amount >= 0),
    CHECK (over_receipt_rate >= 0),
    CHECK (under_receipt_rate >= 0),
    CHECK (price_variance_rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購政策';

-- =========================================================
-- 02. 請購
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_requisition (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '請購單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    requisition_no          VARCHAR(100)                        NOT NULL COMMENT '請購單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT 'MasterDB公司序號',
    business_unit_sid       VARCHAR(32)                             NULL COMMENT 'MasterDB營運單位序號',
    department_sid          VARCHAR(32)                             NULL COMMENT 'MasterDB部門序號',
    project_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT 'Construction ERP工地序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT 'MasterDB成本中心序號',
    purchase_type_sid       VARCHAR(32)                         NOT NULL COMMENT '採購類型序號',
    requester_user_sid      VARCHAR(32)                         NOT NULL COMMENT '請購人帳號序號',
    requester_employee_sid  VARCHAR(32)                             NULL COMMENT '請購人員工序號',
    request_date            DATE                                NOT NULL COMMENT '請購日期',
    required_date           DATE                                    NULL COMMENT '需求日期',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT 'MasterDB幣別序號',
    estimated_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '預估金額',
    emergency_mark          TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否緊急採購',
    source_type             VARCHAR(30)                         NOT NULL DEFAULT 'MANUAL' COMMENT 'MANUAL人工;REORDER補貨;PROJECT專案;MAINTENANCE維修;SALES訂單;SYSTEM系統',
    source_reference_sid    VARCHAR(32)                             NULL COMMENT '來源資料序號',
    requisition_status      VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;REVIEW待審;APPROVED核准;REJECTED駁回;PARTIAL_ORDERED部分轉單;ORDERED已轉單;CANCELLED取消;CLOSED結案',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    reject_reason           TEXT                                    NULL COMMENT '駁回原因',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_pr_requisition_no UNIQUE (requisition_no),
    INDEX idx_pr_company_sid (company_sid),
    INDEX idx_pr_business_unit_sid (business_unit_sid),
    INDEX idx_pr_department_sid (department_sid),
    INDEX idx_pr_project_sid (project_sid),
    INDEX idx_pr_site_sid (site_sid),
    INDEX idx_pr_cost_center_sid (cost_center_sid),
    INDEX idx_pr_purchase_type_sid (purchase_type_sid),
    INDEX idx_pr_requester_user_sid (requester_user_sid),
    INDEX idx_pr_request_date (request_date),
    INDEX idx_pr_required_date (required_date),
    INDEX idx_pr_status (requisition_status),
    INDEX idx_pr_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_pr_avalible (avalible),
    CHECK (estimated_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購請購單';

CREATE TABLE IF NOT EXISTS pur_requisition_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '請購明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    requisition_nid         BIGINT UNSIGNED                     NOT NULL COMMENT '請購單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    item_sid                VARCHAR(32)                             NULL COMMENT 'PIM/MIMDB Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT 'PIM/MIMDB變體序號',
    item_description        VARCHAR(1000)                       NOT NULL COMMENT '品名或需求說明',
    specification_text      TEXT                                    NULL COMMENT '規格說明',
    quantity                DECIMAL(20,6)                       NOT NULL COMMENT '請購數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT 'MasterDB單位序號',
    estimated_unit_price    DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '預估單價',
    estimated_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '預估金額',
    required_date           DATE                                    NULL COMMENT '需求日期',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT 'MasterDB目標倉庫序號',
    location_sid            VARCHAR(32)                             NULL COMMENT 'MasterDB目標儲位序號',
    delivery_address_sid    VARCHAR(32)                             NULL COMMENT 'MasterDB地址序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'Construction ERP WBS序號',
    budget_sid              VARCHAR(32)                             NULL COMMENT 'BudgetCostDB預算序號',
    budget_item_sid         VARCHAR(32)                             NULL COMMENT 'BudgetCostDB預算明細序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT 'ContractDB合約序號',
    contract_item_sid       VARCHAR(32)                             NULL COMMENT 'ContractDB合約明細序號',
    preferred_supplier_sid  VARCHAR(32)                             NULL COMMENT 'PartyDB建議供應商序號',
    ordered_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已轉採購數量',
    cancelled_qty           DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '取消數量',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待處理;PARTIAL部分轉單;ORDERED已轉單;CANCELLED取消;CLOSED結束',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_pri_requisition
        FOREIGN KEY (requisition_nid) REFERENCES pur_requisition(nid),
    CONSTRAINT uk_pri_req_line UNIQUE (requisition_nid, line_no),
    INDEX idx_pri_requisition_nid (requisition_nid),
    INDEX idx_pri_item_sid (item_sid),
    INDEX idx_pri_variant_sid (variant_sid),
    INDEX idx_pri_warehouse_sid (warehouse_sid),
    INDEX idx_pri_wbs_sid (wbs_sid),
    INDEX idx_pri_budget_item_sid (budget_item_sid),
    INDEX idx_pri_contract_item_sid (contract_item_sid),
    INDEX idx_pri_preferred_supplier_sid (preferred_supplier_sid),
    INDEX idx_pri_status (item_status),
    CHECK (line_no > 0),
    CHECK (quantity > 0),
    CHECK (estimated_unit_price >= 0),
    CHECK (estimated_amount >= 0),
    CHECK (ordered_qty >= 0),
    CHECK (cancelled_qty >= 0),
    CHECK (ordered_qty + cancelled_qty <= quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購請購明細';

-- =========================================================
-- 03. 詢價與比價
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_rfq (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '詢價單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    rfq_no                  VARCHAR(100)                        NOT NULL COMMENT '詢價單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT 'MasterDB公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB專案序號',
    purchase_type_sid       VARCHAR(32)                         NOT NULL COMMENT '採購類型序號',
    requisition_sid         VARCHAR(32)                             NULL COMMENT '來源請購單序號',
    issue_date              DATE                                NOT NULL COMMENT '發出日期',
    response_deadline       DATETIME                            NOT NULL COMMENT '報價截止時間',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '預設幣別序號',
    quotation_valid_days    INT                                 NOT NULL DEFAULT 30 COMMENT '報價有效天數',
    evaluation_method       VARCHAR(30)                         NOT NULL DEFAULT 'LOWEST_TOTAL' COMMENT 'LOWEST_TOTAL最低總價;LOWEST_ITEM逐項最低;SCORE綜合評分;MANUAL人工',
    rfq_status              VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;ISSUED已發出;RECEIVING收件中;EVALUATING評選中;AWARDED已決標;CANCELLED取消;CLOSED結束',
    create_user_sid         VARCHAR(32)                         NOT NULL COMMENT '建立人員序號',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_prfq_rfq_no UNIQUE (rfq_no),
    INDEX idx_prfq_company_sid (company_sid),
    INDEX idx_prfq_project_sid (project_sid),
    INDEX idx_prfq_purchase_type_sid (purchase_type_sid),
    INDEX idx_prfq_requisition_sid (requisition_sid),
    INDEX idx_prfq_issue_date (issue_date),
    INDEX idx_prfq_response_deadline (response_deadline),
    INDEX idx_prfq_status (rfq_status),
    INDEX idx_prfq_avalible (avalible),
    CHECK (quotation_valid_days > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購詢價單';

CREATE TABLE IF NOT EXISTS pur_rfq_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '詢價明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    rfq_nid                 BIGINT UNSIGNED                     NOT NULL COMMENT '詢價單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    requisition_item_sid    VARCHAR(32)                             NULL COMMENT '來源請購明細序號',
    item_sid                VARCHAR(32)                             NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    item_description        VARCHAR(1000)                       NOT NULL COMMENT '品名或需求說明',
    specification_text      TEXT                                    NULL COMMENT '規格說明',
    quantity                DECIMAL(20,6)                       NOT NULL COMMENT '詢價數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    required_date           DATE                                    NULL COMMENT '需求日期',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT '目標倉庫序號',
    delivery_address_sid    VARCHAR(32)                             NULL COMMENT '交貨地址序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    budget_item_sid         VARCHAR(32)                             NULL COMMENT '預算明細序號',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN開放;AWARDED已決標;CANCELLED取消',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_prfqi_rfq
        FOREIGN KEY (rfq_nid) REFERENCES pur_rfq(nid),
    CONSTRAINT uk_prfqi_rfq_line UNIQUE (rfq_nid, line_no),
    INDEX idx_prfqi_rfq_nid (rfq_nid),
    INDEX idx_prfqi_requisition_item_sid (requisition_item_sid),
    INDEX idx_prfqi_item_sid (item_sid),
    INDEX idx_prfqi_variant_sid (variant_sid),
    INDEX idx_prfqi_wbs_sid (wbs_sid),
    INDEX idx_prfqi_status (item_status),
    CHECK (line_no > 0),
    CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購詢價明細';

CREATE TABLE IF NOT EXISTS pur_rfq_supplier (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '詢價供應商序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    rfq_nid                 BIGINT UNSIGNED                     NOT NULL COMMENT '詢價單流水號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT 'PartyDB供應商序號',
    invitation_status       VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待發;SENT已寄送;VIEWED已查看;RESPONDED已回覆;DECLINED拒絕;EXPIRED逾期',
    invitation_date         DATETIME                                NULL COMMENT '邀請時間',
    viewed_date             DATETIME                                NULL COMMENT '查看時間',
    response_date           DATETIME                                NULL COMMENT '回覆時間',
    access_token_hash       VARCHAR(255)                            NULL COMMENT '外部報價存取Token雜湊',
    token_expiry_date       DATETIME                                NULL COMMENT 'Token到期時間',
    CONSTRAINT fk_prfqs_rfq
        FOREIGN KEY (rfq_nid) REFERENCES pur_rfq(nid),
    CONSTRAINT uk_prfqs_rfq_supplier UNIQUE (rfq_nid, supplier_party_sid),
    INDEX idx_prfqs_rfq_nid (rfq_nid),
    INDEX idx_prfqs_supplier_party_sid (supplier_party_sid),
    INDEX idx_prfqs_status (invitation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='詢價供應商邀請';

CREATE TABLE IF NOT EXISTS pur_supplier_quote (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '供應商報價序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    quote_no                VARCHAR(100)                        NOT NULL COMMENT '報價單號',
    rfq_sid                 VARCHAR(32)                         NOT NULL COMMENT '詢價單序號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    supplier_quote_no       VARCHAR(150)                            NULL COMMENT '供應商報價單號',
    quote_date              DATE                                NOT NULL COMMENT '報價日期',
    valid_until             DATE                                    NULL COMMENT '有效期限',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    subtotal_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未稅小計',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    freight_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '運費',
    other_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '其他費用',
    total_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '總額',
    payment_term_sid        VARCHAR(32)                             NULL COMMENT '付款條件序號',
    delivery_term_code      VARCHAR(50)                             NULL COMMENT '交貨條件代碼',
    quote_status            VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;VALID有效;EXPIRED過期;AWARDED得標;REJECTED未得標;WITHDRAWN撤回',
    submitted_date          DATETIME                                NULL COMMENT '送出時間',
    file_sid                VARCHAR(32)                             NULL COMMENT 'FileDB報價附件序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_psq_quote_no UNIQUE (quote_no),
    CONSTRAINT uk_psq_rfq_supplier UNIQUE (rfq_sid, supplier_party_sid),
    INDEX idx_psq_rfq_sid (rfq_sid),
    INDEX idx_psq_supplier_party_sid (supplier_party_sid),
    INDEX idx_psq_quote_date (quote_date),
    INDEX idx_psq_valid_until (valid_until),
    INDEX idx_psq_status (quote_status),
    INDEX idx_psq_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (subtotal_amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (freight_amount >= 0),
    CHECK (other_amount >= 0),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供應商報價單';

CREATE TABLE IF NOT EXISTS pur_supplier_quote_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '供應商報價明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    supplier_quote_nid      BIGINT UNSIGNED                     NOT NULL COMMENT '供應商報價流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    rfq_item_sid            VARCHAR(32)                         NOT NULL COMMENT '詢價明細序號',
    supplier_item_no        VARCHAR(150)                            NULL COMMENT '供應商料號',
    item_description        VARCHAR(1000)                       NOT NULL COMMENT '品名或說明',
    quoted_qty              DECIMAL(20,6)                       NOT NULL COMMENT '報價數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    unit_price              DECIMAL(20,6)                       NOT NULL COMMENT '單價',
    discount_rate           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '折扣率',
    tax_sid                 VARCHAR(32)                             NULL COMMENT '稅別序號',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    line_amount             DECIMAL(20,4)                       NOT NULL COMMENT '明細總額',
    lead_time_days          INT                                 NOT NULL DEFAULT 0 COMMENT '交期天數',
    promised_date           DATE                                    NULL COMMENT '承諾交貨日',
    minimum_order_qty       DECIMAL(20,6)                           NULL COMMENT '最低訂購量',
    warranty_months         INT                                     NULL COMMENT '保固月數',
    compliance_result       JSON                                    NULL COMMENT '規格符合性',
    award_status            VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待評選;AWARDED得標;REJECTED未得標;PARTIAL部分得標',
    awarded_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '得標數量',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_psqi_quote
        FOREIGN KEY (supplier_quote_nid) REFERENCES pur_supplier_quote(nid),
    CONSTRAINT uk_psqi_quote_line UNIQUE (supplier_quote_nid, line_no),
    INDEX idx_psqi_quote_nid (supplier_quote_nid),
    INDEX idx_psqi_rfq_item_sid (rfq_item_sid),
    INDEX idx_psqi_award_status (award_status),
    CHECK (line_no > 0),
    CHECK (quoted_qty > 0),
    CHECK (unit_price >= 0),
    CHECK (discount_rate >= 0),
    CHECK (tax_amount >= 0),
    CHECK (line_amount >= 0),
    CHECK (lead_time_days >= 0),
    CHECK (minimum_order_qty IS NULL OR minimum_order_qty > 0),
    CHECK (warranty_months IS NULL OR warranty_months >= 0),
    CHECK (awarded_qty >= 0),
    CHECK (awarded_qty <= quoted_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供應商報價明細';

CREATE TABLE IF NOT EXISTS pur_quote_evaluation (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '報價評選序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    rfq_sid                 VARCHAR(32)                         NOT NULL COMMENT '詢價單序號',
    supplier_quote_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商報價序號',
    price_score             DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '價格分數',
    delivery_score          DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '交期分數',
    quality_score           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '品質分數',
    service_score           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '服務分數',
    compliance_score        DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '合規分數',
    total_score             DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '總分',
    rank_no                 INT                                     NULL COMMENT '排名',
    recommendation          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待評;RECOMMEND建議;ALTERNATE備選;REJECT不建議',
    evaluator_user_sid      VARCHAR(32)                             NULL COMMENT '評選人員序號',
    evaluation_note         TEXT                                    NULL COMMENT '評選說明',
    CONSTRAINT uk_pqe_rfq_quote UNIQUE (rfq_sid, supplier_quote_sid),
    INDEX idx_pqe_rfq_sid (rfq_sid),
    INDEX idx_pqe_supplier_quote_sid (supplier_quote_sid),
    INDEX idx_pqe_total_score (total_score),
    INDEX idx_pqe_rank_no (rank_no),
    INDEX idx_pqe_recommendation (recommendation),
    CHECK (price_score >= 0),
    CHECK (delivery_score >= 0),
    CHECK (quality_score >= 0),
    CHECK (service_score >= 0),
    CHECK (compliance_score >= 0),
    CHECK (total_score >= 0),
    CHECK (rank_no IS NULL OR rank_no > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供應商報價評選';

-- =========================================================
-- 04. 採購單
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_order (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    purchase_order_no       VARCHAR(100)                        NOT NULL COMMENT '採購單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    business_unit_sid       VARCHAR(32)                             NULL COMMENT '營運單位序號',
    department_sid          VARCHAR(32)                             NULL COMMENT '部門序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    purchase_type_sid       VARCHAR(32)                         NOT NULL COMMENT '採購類型序號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    requisition_sid         VARCHAR(32)                             NULL COMMENT '來源請購單序號',
    rfq_sid                 VARCHAR(32)                             NULL COMMENT '來源詢價單序號',
    supplier_quote_sid      VARCHAR(32)                             NULL COMMENT '來源供應商報價序號',
    agreement_sid           VARCHAR(32)                             NULL COMMENT 'PricingDB價格協議序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT 'ContractDB合約序號',
    order_date              DATE                                NOT NULL COMMENT '採購日期',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    subtotal_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未稅小計',
    discount_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '折扣',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    freight_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '運費',
    other_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '其他費用',
    total_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '採購總額',
    payment_term_sid        VARCHAR(32)                             NULL COMMENT '付款條件序號',
    payment_method_sid      VARCHAR(32)                             NULL COMMENT '付款方式序號',
    delivery_term_code      VARCHAR(50)                             NULL COMMENT '交貨條件',
    expected_delivery_date  DATE                                    NULL COMMENT '預計交貨日',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT '預設收貨倉庫序號',
    delivery_address_sid    VARCHAR(32)                             NULL COMMENT '交貨地址序號',
    order_status            VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;REVIEW待審;APPROVED核准;ISSUED已發單;PARTIAL_RECEIVED部分收貨;RECEIVED已收貨;CANCELLED取消;CLOSED結案',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    issued_date             DATETIME                                NULL COMMENT '發單時間',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_po_purchase_order_no UNIQUE (purchase_order_no),
    INDEX idx_po_company_sid (company_sid),
    INDEX idx_po_project_sid (project_sid),
    INDEX idx_po_site_sid (site_sid),
    INDEX idx_po_supplier_party_sid (supplier_party_sid),
    INDEX idx_po_requisition_sid (requisition_sid),
    INDEX idx_po_rfq_sid (rfq_sid),
    INDEX idx_po_supplier_quote_sid (supplier_quote_sid),
    INDEX idx_po_agreement_sid (agreement_sid),
    INDEX idx_po_contract_sid (contract_sid),
    INDEX idx_po_order_date (order_date),
    INDEX idx_po_expected_delivery_date (expected_delivery_date),
    INDEX idx_po_warehouse_sid (warehouse_sid),
    INDEX idx_po_status (order_status),
    INDEX idx_po_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_po_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (subtotal_amount >= 0),
    CHECK (discount_amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (freight_amount >= 0),
    CHECK (other_amount >= 0),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購單';

CREATE TABLE IF NOT EXISTS pur_order_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購單明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    purchase_order_nid      BIGINT UNSIGNED                     NOT NULL COMMENT '採購單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    requisition_item_sid    VARCHAR(32)                             NULL COMMENT '來源請購明細序號',
    rfq_item_sid            VARCHAR(32)                             NULL COMMENT '來源詢價明細序號',
    quote_item_sid          VARCHAR(32)                             NULL COMMENT '來源報價明細序號',
    item_sid                VARCHAR(32)                             NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    item_description        VARCHAR(1000)                       NOT NULL COMMENT '品名或需求說明',
    specification_text      TEXT                                    NULL COMMENT '規格說明',
    supplier_item_no        VARCHAR(150)                            NULL COMMENT '供應商料號',
    order_qty               DECIMAL(20,6)                       NOT NULL COMMENT '採購數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '採購單位序號',
    unit_price              DECIMAL(20,6)                       NOT NULL COMMENT '單價',
    discount_rate           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '折扣率',
    discount_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '折扣金額',
    tax_sid                 VARCHAR(32)                             NULL COMMENT '稅別序號',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    line_amount             DECIMAL(20,4)                       NOT NULL COMMENT '明細總額',
    expected_delivery_date  DATE                                    NULL COMMENT '預計交貨日',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT '收貨倉庫序號',
    location_sid            VARCHAR(32)                             NULL COMMENT '收貨儲位序號',
    delivery_address_sid    VARCHAR(32)                             NULL COMMENT '交貨地址序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    budget_sid              VARCHAR(32)                             NULL COMMENT '預算序號',
    budget_item_sid         VARCHAR(32)                             NULL COMMENT '預算明細序號',
    contract_item_sid       VARCHAR(32)                             NULL COMMENT '合約明細序號',
    received_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已收貨數量',
    accepted_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已驗收數量',
    returned_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '已退貨數量',
    cancelled_qty           DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '取消數量',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待交貨;PARTIAL部分收貨;RECEIVED已收貨;CANCELLED取消;CLOSED結束',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_poi_order
        FOREIGN KEY (purchase_order_nid) REFERENCES pur_order(nid),
    CONSTRAINT uk_poi_order_line UNIQUE (purchase_order_nid, line_no),
    INDEX idx_poi_order_nid (purchase_order_nid),
    INDEX idx_poi_requisition_item_sid (requisition_item_sid),
    INDEX idx_poi_rfq_item_sid (rfq_item_sid),
    INDEX idx_poi_quote_item_sid (quote_item_sid),
    INDEX idx_poi_item_sid (item_sid),
    INDEX idx_poi_variant_sid (variant_sid),
    INDEX idx_poi_warehouse_sid (warehouse_sid),
    INDEX idx_poi_wbs_sid (wbs_sid),
    INDEX idx_poi_budget_item_sid (budget_item_sid),
    INDEX idx_poi_contract_item_sid (contract_item_sid),
    INDEX idx_poi_expected_delivery_date (expected_delivery_date),
    INDEX idx_poi_status (item_status),
    CHECK (line_no > 0),
    CHECK (order_qty > 0),
    CHECK (unit_price >= 0),
    CHECK (discount_rate >= 0),
    CHECK (discount_amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (line_amount >= 0),
    CHECK (received_qty >= 0),
    CHECK (accepted_qty >= 0),
    CHECK (returned_qty >= 0),
    CHECK (cancelled_qty >= 0),
    CHECK (received_qty <= order_qty + (order_qty * 1)),
    CHECK (accepted_qty <= received_qty),
    CHECK (returned_qty <= received_qty),
    CHECK (cancelled_qty <= order_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購單明細';

CREATE TABLE IF NOT EXISTS pur_order_schedule (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '交期排程序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    purchase_order_item_nid BIGINT UNSIGNED                     NOT NULL COMMENT '採購單明細流水號',
    schedule_no             INT                                 NOT NULL COMMENT '批次序號',
    scheduled_qty           DECIMAL(20,6)                       NOT NULL COMMENT '排程數量',
    planned_delivery_date   DATE                                NOT NULL COMMENT '計畫交貨日',
    confirmed_delivery_date DATE                                    NULL COMMENT '供應商確認交貨日',
    actual_delivery_date    DATE                                    NULL COMMENT '實際交貨日',
    warehouse_sid           VARCHAR(32)                             NULL COMMENT '收貨倉庫序號',
    delivery_address_sid    VARCHAR(32)                             NULL COMMENT '交貨地址序號',
    schedule_status         VARCHAR(20)                         NOT NULL DEFAULT 'PLANNED' COMMENT 'PLANNED計畫;CONFIRMED確認;PARTIAL部分到貨;DELIVERED完成;DELAYED延遲;CANCELLED取消',
    delay_reason            TEXT                                    NULL COMMENT '延遲原因',
    CONSTRAINT fk_pos_order_item
        FOREIGN KEY (purchase_order_item_nid) REFERENCES pur_order_item(nid),
    CONSTRAINT uk_pos_item_schedule UNIQUE (purchase_order_item_nid, schedule_no),
    INDEX idx_pos_order_item_nid (purchase_order_item_nid),
    INDEX idx_pos_planned_delivery_date (planned_delivery_date),
    INDEX idx_pos_confirmed_delivery_date (confirmed_delivery_date),
    INDEX idx_pos_status (schedule_status),
    CHECK (schedule_no > 0),
    CHECK (scheduled_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購交期排程';

-- =========================================================
-- 05. 收貨與到場
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_receipt (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '收貨單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    receipt_no              VARCHAR(100)                        NOT NULL COMMENT '收貨單號',
    purchase_order_sid      VARCHAR(32)                         NOT NULL COMMENT '採購單序號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '收貨倉庫序號',
    receipt_date            DATETIME                            NOT NULL COMMENT '收貨時間',
    delivery_note_no        VARCHAR(150)                            NULL COMMENT '送貨單號',
    vehicle_no              VARCHAR(100)                            NULL COMMENT '車牌號碼',
    driver_name             VARCHAR(100)                            NULL COMMENT '司機姓名',
    receiver_user_sid       VARCHAR(32)                         NOT NULL COMMENT '收貨人員序號',
    source_type             VARCHAR(30)                         NOT NULL DEFAULT 'PURCHASE_ORDER' COMMENT 'PURCHASE_ORDER採購單;TRANSFER調撥;RETURN退回;OTHER',
    inventory_receipt_sid   VARCHAR(32)                             NULL COMMENT 'InventoryDB入庫單序號',
    receipt_status          VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;RECEIVED已收貨;INSPECTING驗收中;ACCEPTED已驗收;REJECTED拒收;CANCELLED取消;CLOSED結案',
    file_sid                VARCHAR(32)                             NULL COMMENT 'FileDB送貨單或照片序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_prec_receipt_no UNIQUE (receipt_no),
    INDEX idx_prec_purchase_order_sid (purchase_order_sid),
    INDEX idx_prec_supplier_party_sid (supplier_party_sid),
    INDEX idx_prec_project_sid (project_sid),
    INDEX idx_prec_site_sid (site_sid),
    INDEX idx_prec_warehouse_sid (warehouse_sid),
    INDEX idx_prec_receipt_date (receipt_date),
    INDEX idx_prec_inventory_receipt_sid (inventory_receipt_sid),
    INDEX idx_prec_status (receipt_status),
    INDEX idx_prec_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購收貨單與工地到場紀錄';

CREATE TABLE IF NOT EXISTS pur_receipt_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '收貨明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    receipt_nid             BIGINT UNSIGNED                     NOT NULL COMMENT '收貨單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    purchase_order_item_sid VARCHAR(32)                         NOT NULL COMMENT '採購單明細序號',
    schedule_sid            VARCHAR(32)                             NULL COMMENT '交期排程序號',
    item_sid                VARCHAR(32)                             NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    received_qty            DECIMAL(20,6)                       NOT NULL COMMENT '本次收貨數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '收貨單位序號',
    accepted_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '驗收合格數量',
    rejected_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '驗收不合格數量',
    pending_qty             DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '待驗數量',
    batch_no                VARCHAR(150)                            NULL COMMENT '批號',
    manufacture_date        DATE                                    NULL COMMENT '製造日期',
    expiry_date             DATE                                    NULL COMMENT '有效期限',
    location_sid            VARCHAR(32)                             NULL COMMENT '收貨儲位序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    inspection_required     TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否需驗收',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'RECEIVED' COMMENT 'RECEIVED已收;INSPECTING驗收中;ACCEPTED合格;PARTIAL部分合格;REJECTED不合格',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_prechi_receipt
        FOREIGN KEY (receipt_nid) REFERENCES pur_receipt(nid),
    CONSTRAINT uk_prechi_receipt_line UNIQUE (receipt_nid, line_no),
    INDEX idx_prechi_receipt_nid (receipt_nid),
    INDEX idx_prechi_purchase_order_item_sid (purchase_order_item_sid),
    INDEX idx_prechi_schedule_sid (schedule_sid),
    INDEX idx_prechi_item_sid (item_sid),
    INDEX idx_prechi_variant_sid (variant_sid),
    INDEX idx_prechi_batch_no (batch_no),
    INDEX idx_prechi_wbs_sid (wbs_sid),
    INDEX idx_prechi_status (item_status),
    CHECK (line_no > 0),
    CHECK (received_qty > 0),
    CHECK (accepted_qty >= 0),
    CHECK (rejected_qty >= 0),
    CHECK (pending_qty >= 0),
    CHECK (accepted_qty + rejected_qty + pending_qty <= received_qty),
    CHECK (expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date >= manufacture_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購收貨明細';

-- =========================================================
-- 06. 驗收
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_inspection (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '驗收單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    inspection_no           VARCHAR(100)                        NOT NULL COMMENT '驗收單號',
    receipt_sid             VARCHAR(32)                         NOT NULL COMMENT '收貨單序號',
    inspection_type         VARCHAR(30)                         NOT NULL COMMENT 'QUANTITY數量;QUALITY品質;SPEC規格;SAFETY安全;DOCUMENT文件;FULL完整',
    inspection_date         DATETIME                            NOT NULL COMMENT '驗收時間',
    inspector_user_sid      VARCHAR(32)                         NOT NULL COMMENT '驗收人員序號',
    inspection_result       VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待驗;PASS合格;PARTIAL部分合格;FAIL不合格;WAIVED免驗',
    inspection_status       VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;PROCESSING進行中;COMPLETED完成;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    completed_date          DATETIME                                NULL COMMENT '完成時間',
    file_sid                VARCHAR(32)                             NULL COMMENT 'FileDB驗收附件序號',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_pins_inspection_no UNIQUE (inspection_no),
    INDEX idx_pins_receipt_sid (receipt_sid),
    INDEX idx_pins_inspection_type (inspection_type),
    INDEX idx_pins_inspection_date (inspection_date),
    INDEX idx_pins_inspector_user_sid (inspector_user_sid),
    INDEX idx_pins_result (inspection_result),
    INDEX idx_pins_status (inspection_status),
    INDEX idx_pins_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_pins_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購驗收單';

CREATE TABLE IF NOT EXISTS pur_inspection_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '驗收明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    inspection_nid          BIGINT UNSIGNED                     NOT NULL COMMENT '驗收單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    receipt_item_sid        VARCHAR(32)                         NOT NULL COMMENT '收貨明細序號',
    inspected_qty           DECIMAL(20,6)                       NOT NULL COMMENT '驗收數量',
    accepted_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '合格數量',
    rejected_qty            DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '不合格數量',
    conditional_qty         DECIMAL(20,6)                       NOT NULL DEFAULT 0 COMMENT '有條件接受數量',
    result                  VARCHAR(20)                         NOT NULL COMMENT 'PASS合格;PARTIAL部分;FAIL不合格;WAIVED免驗',
    defect_code             VARCHAR(100)                            NULL COMMENT '缺失代碼',
    defect_description      TEXT                                    NULL COMMENT '缺失說明',
    disposition_type        VARCHAR(30)                             NULL COMMENT 'ACCEPT接受;REWORK重工;RETURN退貨;DISCOUNT折價;REPLACE換貨;SCRAP報廢',
    responsible_party_sid   VARCHAR(32)                             NULL COMMENT '責任Party序號',
    due_date                DATE                                    NULL COMMENT '改善期限',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待處理;RESOLVED已解決;CLOSED結案',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_pinsi_inspection
        FOREIGN KEY (inspection_nid) REFERENCES pur_inspection(nid),
    CONSTRAINT uk_pinsi_inspection_line UNIQUE (inspection_nid, line_no),
    INDEX idx_pinsi_inspection_nid (inspection_nid),
    INDEX idx_pinsi_receipt_item_sid (receipt_item_sid),
    INDEX idx_pinsi_result (result),
    INDEX idx_pinsi_defect_code (defect_code),
    INDEX idx_pinsi_responsible_party_sid (responsible_party_sid),
    INDEX idx_pinsi_status (item_status),
    CHECK (line_no > 0),
    CHECK (inspected_qty > 0),
    CHECK (accepted_qty >= 0),
    CHECK (rejected_qty >= 0),
    CHECK (conditional_qty >= 0),
    CHECK (accepted_qty + rejected_qty + conditional_qty <= inspected_qty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購驗收明細';

-- =========================================================
-- 07. 採購退貨
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_return (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購退貨單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    return_no               VARCHAR(100)                        NOT NULL COMMENT '退貨單號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    purchase_order_sid      VARCHAR(32)                         NOT NULL COMMENT '採購單序號',
    receipt_sid             VARCHAR(32)                             NULL COMMENT '來源收貨單序號',
    inspection_sid          VARCHAR(32)                             NULL COMMENT '來源驗收單序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    warehouse_sid           VARCHAR(32)                         NOT NULL COMMENT '退貨倉庫序號',
    return_date             DATE                                NOT NULL COMMENT '退貨日期',
    reason_code             VARCHAR(50)                         NOT NULL COMMENT '退貨原因代碼',
    reason_description      TEXT                                    NULL COMMENT '退貨原因說明',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    total_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '退貨總額',
    return_status           VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;SHIPPED已退運;RECEIVED供應商已收;CREDITED已折讓;CANCELLED取消;CLOSED結案',
    inventory_issue_sid     VARCHAR(32)                             NULL COMMENT 'InventoryDB出庫單序號',
    allowance_sid           VARCHAR(32)                             NULL COMMENT 'InvoiceTaxDB折讓序號',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_pret_return_no UNIQUE (return_no),
    INDEX idx_pret_supplier_party_sid (supplier_party_sid),
    INDEX idx_pret_purchase_order_sid (purchase_order_sid),
    INDEX idx_pret_receipt_sid (receipt_sid),
    INDEX idx_pret_inspection_sid (inspection_sid),
    INDEX idx_pret_project_sid (project_sid),
    INDEX idx_pret_warehouse_sid (warehouse_sid),
    INDEX idx_pret_return_date (return_date),
    INDEX idx_pret_status (return_status),
    INDEX idx_pret_inventory_issue_sid (inventory_issue_sid),
    INDEX idx_pret_allowance_sid (allowance_sid),
    INDEX idx_pret_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_pret_avalible (avalible),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購退貨單';

CREATE TABLE IF NOT EXISTS pur_return_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購退貨明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    return_nid              BIGINT UNSIGNED                     NOT NULL COMMENT '退貨單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    purchase_order_item_sid VARCHAR(32)                         NOT NULL COMMENT '採購單明細序號',
    receipt_item_sid        VARCHAR(32)                             NULL COMMENT '收貨明細序號',
    inspection_item_sid     VARCHAR(32)                             NULL COMMENT '驗收明細序號',
    item_sid                VARCHAR(32)                             NULL COMMENT 'Item序號',
    variant_sid             VARCHAR(32)                             NULL COMMENT '變體序號',
    return_qty              DECIMAL(20,6)                       NOT NULL COMMENT '退貨數量',
    unit_sid                VARCHAR(32)                         NOT NULL COMMENT '單位序號',
    unit_price              DECIMAL(20,6)                       NOT NULL COMMENT '退貨單價',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    line_amount             DECIMAL(20,4)                       NOT NULL COMMENT '退貨金額',
    batch_no                VARCHAR(150)                            NULL COMMENT '批號',
    serial_data             JSON                                    NULL COMMENT '序號清單',
    disposition_type        VARCHAR(30)                         NOT NULL DEFAULT 'RETURN' COMMENT 'RETURN退貨;REPLACE換貨;REWORK重工;SCRAP報廢',
    item_status             VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN待處理;SHIPPED已退運;RECEIVED已收;CREDITED已折讓;CLOSED結束',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT fk_preti_return
        FOREIGN KEY (return_nid) REFERENCES pur_return(nid),
    CONSTRAINT uk_preti_return_line UNIQUE (return_nid, line_no),
    INDEX idx_preti_return_nid (return_nid),
    INDEX idx_preti_purchase_order_item_sid (purchase_order_item_sid),
    INDEX idx_preti_receipt_item_sid (receipt_item_sid),
    INDEX idx_preti_inspection_item_sid (inspection_item_sid),
    INDEX idx_preti_item_sid (item_sid),
    INDEX idx_preti_variant_sid (variant_sid),
    INDEX idx_preti_batch_no (batch_no),
    INDEX idx_preti_status (item_status),
    CHECK (line_no > 0),
    CHECK (return_qty > 0),
    CHECK (unit_price >= 0),
    CHECK (tax_amount >= 0),
    CHECK (line_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購退貨明細';

-- =========================================================
-- 08. 採購變更與取消
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_order_change (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購單變更序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    change_no               VARCHAR(100)                        NOT NULL COMMENT '變更單號',
    purchase_order_sid      VARCHAR(32)                         NOT NULL COMMENT '採購單序號',
    change_type             VARCHAR(30)                         NOT NULL COMMENT 'QUANTITY數量;PRICE價格;DELIVERY交期;ITEM品項;SUPPLIER供應商;CANCEL取消;OTHER',
    before_data             JSON                                    NULL COMMENT '變更前資料',
    requested_data          JSON                                NOT NULL COMMENT '申請變更資料',
    changed_fields          JSON                                    NULL COMMENT '變更欄位',
    change_reason           TEXT                                NOT NULL COMMENT '變更原因',
    requester_user_sid      VARCHAR(32)                         NOT NULL COMMENT '申請人員序號',
    change_status           VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;REVIEW待審;APPROVED核准;REJECTED駁回;APPLIED已套用;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    applied_date            DATETIME                                NULL COMMENT '套用時間',
    CONSTRAINT uk_poc_change_no UNIQUE (change_no),
    INDEX idx_poc_purchase_order_sid (purchase_order_sid),
    INDEX idx_poc_change_type (change_type),
    INDEX idx_poc_requester_user_sid (requester_user_sid),
    INDEX idx_poc_status (change_status),
    INDEX idx_poc_workflow_instance_sid (workflow_instance_sid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購單變更申請';

-- =========================================================
-- 09. 供應商績效
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_supplier_performance (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '供應商績效序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    company_sid             VARCHAR(32)                             NULL COMMENT '公司序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    period_start_date       DATE                                NOT NULL COMMENT '評估期間開始日',
    period_end_date         DATE                                NOT NULL COMMENT '評估期間結束日',
    order_count             INT                                 NOT NULL DEFAULT 0 COMMENT '採購單數',
    on_time_delivery_rate   DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '準時交貨率',
    acceptance_rate         DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '驗收合格率',
    return_rate             DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '退貨率',
    price_variance_rate     DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '價格差異率',
    response_score          DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '回應分數',
    quality_score           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '品質分數',
    delivery_score          DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '交期分數',
    service_score           DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '服務分數',
    compliance_score        DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '合規分數',
    total_score             DECIMAL(8,4)                        NOT NULL DEFAULT 0 COMMENT '總分',
    rating_level            VARCHAR(20)                             NULL COMMENT '績效等級',
    evaluation_data         JSON                                    NULL COMMENT '評估明細',
    evaluator_user_sid      VARCHAR(32)                             NULL COMMENT '評估人員序號',
    performance_status      VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'DRAFT草稿;ACTIVE有效;REPLACED已取代;VOID作廢',
    CONSTRAINT uk_psp_supplier_period UNIQUE (supplier_party_sid, company_sid, project_sid, period_start_date, period_end_date),
    INDEX idx_psp_supplier_party_sid (supplier_party_sid),
    INDEX idx_psp_company_sid (company_sid),
    INDEX idx_psp_project_sid (project_sid),
    INDEX idx_psp_period (period_start_date, period_end_date),
    INDEX idx_psp_total_score (total_score),
    INDEX idx_psp_rating_level (rating_level),
    INDEX idx_psp_status (performance_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (order_count >= 0),
    CHECK (on_time_delivery_rate >= 0),
    CHECK (acceptance_rate >= 0),
    CHECK (return_rate >= 0),
    CHECK (price_variance_rate >= 0),
    CHECK (response_score >= 0),
    CHECK (quality_score >= 0),
    CHECK (delivery_score >= 0),
    CHECK (service_score >= 0),
    CHECK (compliance_score >= 0),
    CHECK (total_score >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供應商採購績效';

-- =========================================================
-- 10. 採購事件與歷程
-- =========================================================

CREATE TABLE IF NOT EXISTS pur_status_history (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購狀態歷程序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'REQUISITION請購;RFQ詢價;QUOTE報價;ORDER採購單;RECEIPT收貨;INSPECTION驗收;RETURN退貨;CHANGE變更',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '採購實體序號',
    old_status              VARCHAR(30)                             NULL COMMENT '原狀態',
    new_status              VARCHAR(30)                         NOT NULL COMMENT '新狀態',
    event_code              VARCHAR(100)                            NULL COMMENT '觸發事件代碼',
    source_service_code     VARCHAR(80)                             NULL COMMENT '來源服務代碼',
    source_reference_sid    VARCHAR(32)                             NULL COMMENT '來源資料序號',
    operator_user_sid       VARCHAR(32)                             NULL COMMENT '操作人員序號',
    reason_code             VARCHAR(50)                             NULL COMMENT '原因代碼',
    reason                  TEXT                                    NULL COMMENT '原因說明',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_psh_entity (entity_type, entity_sid),
    INDEX idx_psh_new_status (new_status),
    INDEX idx_psh_event_code (event_code),
    INDEX idx_psh_operator_user_sid (operator_user_sid),
    INDEX idx_psh_correlation_id (correlation_id),
    INDEX idx_psh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購狀態歷程';

CREATE TABLE IF NOT EXISTS pur_event (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '採購事件序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'REQUISITION;RFQ;QUOTE;ORDER;RECEIPT;INSPECTION;RETURN',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '採購實體序號',
    event_code              VARCHAR(120)                        NOT NULL COMMENT '事件代碼',
    event_version           INT                                 NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data              JSON                                    NULL COMMENT '事件內容',
    source_event_id         VARCHAR(100)                            NULL COMMENT '來源事件ID',
    correlation_id          VARCHAR(100)                            NULL COMMENT '關聯識別碼',
    causation_id            VARCHAR(100)                            NULL COMMENT '因果事件ID',
    outbox_event_sid        VARCHAR(32)                             NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date          DATETIME                                NULL COMMENT '處理時間',
    error_message           TEXT                                    NULL COMMENT '錯誤訊息',
    CONSTRAINT uk_pe_source_event UNIQUE (source_event_id),
    INDEX idx_pe_entity (entity_type, entity_sid),
    INDEX idx_pe_event_code (event_code),
    INDEX idx_pe_correlation_id (correlation_id),
    INDEX idx_pe_outbox_event_sid (outbox_event_sid),
    INDEX idx_pe_status (process_status),
    INDEX idx_pe_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='採購領域事件';

SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
