namespace B2bOrder.Resources.Finance
{
    /// <summary>
    /// AccountingDB V2 Shared Core Schema
    /// 設計目標：
    /// 1. 同時支援 Shopping Platform、B2B Sales 與 Construction ERP
    /// 2. 支援應收、應付、收款、付款、沖帳、預收、預付、費用、折讓與財務傳票介面
    /// 3. SalesOrderDB、PurchaseDB、PaymentDB、ReturnAfterSalesDB 與 InventoryDB 透過 API/Event 串接
    /// 4. 總帳正式過帳可由 GeneralLedgerDB 處理；本資料庫保留營運財務子帳與傳票請求
    /// 5. PartyDB 提供客戶、供應商與銀行帳戶；MasterDB 提供公司、幣別、稅別、成本中心與會計期間
    /// 6. nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼
    /// 7. avalible：Y可用；W停用；D刪除
    /// 8. 適用 MySQL 8.x / InnoDB / utf8mb4
    /// </summary>
    internal static class AccountingDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- 01. 財務單據類型與政策
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_document_type (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務單據類型序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    document_type_code      VARCHAR(100)                        NOT NULL COMMENT '單據類型代碼',
    document_type_name      VARCHAR(200)                        NOT NULL COMMENT '單據類型名稱',
    document_category      VARCHAR(30)                         NOT NULL COMMENT 'AR應收;AP應付;RECEIPT收款;PAYMENT付款;PREPAYMENT預付;ADVANCE預收;EXPENSE費用;CREDIT折讓;ADJUSTMENT調整',
    source_module          VARCHAR(30)                         NOT NULL COMMENT 'SALES;PURCHASE;PAYMENT;RETURN;INVENTORY;PROJECT;MANUAL',
    approval_required      TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否需要簽核',
    posting_required       TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否需建立傳票',
    document_status        VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible               VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                 TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_adt_document_type_code UNIQUE (document_type_code),
    INDEX idx_adt_document_category (document_category),
    INDEX idx_adt_source_module (source_module),
    INDEX idx_adt_status (document_status),
    INDEX idx_adt_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='財務單據類型';

CREATE TABLE IF NOT EXISTS acc_policy (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務政策序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    policy_code             VARCHAR(100)                        NOT NULL COMMENT '政策代碼',
    policy_name             VARCHAR(200)                        NOT NULL COMMENT '政策名稱',
    company_sid             VARCHAR(32)                             NULL COMMENT 'MasterDB公司序號',
    business_unit_sid       VARCHAR(32)                             NULL COMMENT '營運單位序號',
    default_currency_sid    VARCHAR(32)                         NOT NULL COMMENT '預設幣別序號',
    exchange_rate_type      VARCHAR(30)                         NOT NULL DEFAULT 'TRANSACTION_DATE' COMMENT 'TRANSACTION_DATE交易日;POSTING_DATE過帳日;MANUAL人工',
    tolerance_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '沖帳容許差額',
    writeoff_limit_amount   DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '小額沖銷上限',
    auto_post_enabled       TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否自動產生傳票',
    auto_match_enabled      TINYINT(1)                          NOT NULL DEFAULT 1 COMMENT '是否自動沖帳',
    policy_status           VARCHAR(20)                         NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ap_policy_code UNIQUE (policy_code),
    INDEX idx_ap_company_sid (company_sid),
    INDEX idx_ap_business_unit_sid (business_unit_sid),
    INDEX idx_ap_status (policy_status),
    INDEX idx_ap_avalible (avalible),
    CHECK (tolerance_amount >= 0),
    CHECK (writeoff_limit_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='財務子帳與沖帳政策';

-- =========================================================
-- 02. 應收帳款
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_receivable (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '應收帳款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    receivable_no           VARCHAR(100)                        NOT NULL COMMENT '應收單號',
    document_type_sid       VARCHAR(32)                         NOT NULL COMMENT '財務單據類型序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    business_unit_sid       VARCHAR(32)                             NULL COMMENT '營運單位序號',
    customer_party_sid      VARCHAR(32)                         NOT NULL COMMENT '客戶Party序號',
    sales_order_sid         VARCHAR(32)                             NULL COMMENT 'SalesOrderDB銷售單序號',
    invoice_sid             VARCHAR(32)                             NULL COMMENT 'InvoiceTaxDB銷項發票序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT 'ContractDB合約序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    transaction_date        DATE                                NOT NULL COMMENT '交易日期',
    posting_date            DATE                                    NULL COMMENT '過帳日期',
    due_date                DATE                                NOT NULL COMMENT '到期日',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    original_amount         DECIMAL(20,4)                       NOT NULL COMMENT '原始應收金額',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    paid_amount             DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '已收金額',
    credit_amount           DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '折讓與貸項金額',
    writeoff_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '沖銷金額',
    outstanding_amount      DECIMAL(20,4)                       NOT NULL COMMENT '未收餘額',
    receivable_status       VARCHAR(30)                         NOT NULL DEFAULT 'OPEN' COMMENT 'DRAFT草稿;OPEN未收;PARTIAL部分收款;PAID已收清;OVERDUE逾期;DISPUTED爭議;WRITTEN_OFF已沖銷;CANCELLED取消',
    accounting_period_sid   VARCHAR(32)                             NULL COMMENT '會計期間序號',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ar_receivable_no UNIQUE (receivable_no),
    INDEX idx_ar_company_sid (company_sid),
    INDEX idx_ar_customer_party_sid (customer_party_sid),
    INDEX idx_ar_sales_order_sid (sales_order_sid),
    INDEX idx_ar_invoice_sid (invoice_sid),
    INDEX idx_ar_contract_sid (contract_sid),
    INDEX idx_ar_project_sid (project_sid),
    INDEX idx_ar_site_sid (site_sid),
    INDEX idx_ar_wbs_sid (wbs_sid),
    INDEX idx_ar_cost_center_sid (cost_center_sid),
    INDEX idx_ar_transaction_date (transaction_date),
    INDEX idx_ar_due_date (due_date),
    INDEX idx_ar_status (receivable_status),
    INDEX idx_ar_accounting_period_sid (accounting_period_sid),
    INDEX idx_ar_journal_request_sid (journal_request_sid),
    INDEX idx_ar_correlation_id (correlation_id),
    INDEX idx_ar_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (original_amount > 0),
    CHECK (tax_amount >= 0),
    CHECK (paid_amount >= 0),
    CHECK (credit_amount >= 0),
    CHECK (writeoff_amount >= 0),
    CHECK (outstanding_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應收帳款主檔';

CREATE TABLE IF NOT EXISTS acc_receivable_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '應收帳款明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    receivable_nid          BIGINT UNSIGNED                     NOT NULL COMMENT '應收帳款流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    reference_type          VARCHAR(30)                         NOT NULL COMMENT 'ORDER_ITEM訂單明細;INVOICE_ITEM發票明細;MILESTONE里程碑;SERVICE服務;ADJUSTMENT調整',
    reference_sid           VARCHAR(32)                         NOT NULL COMMENT '來源明細序號',
    description             VARCHAR(1000)                           NULL COMMENT '明細說明',
    quantity                DECIMAL(20,6)                           NULL COMMENT '數量',
    unit_sid                VARCHAR(32)                             NULL COMMENT '單位序號',
    unit_price              DECIMAL(20,6)                           NULL COMMENT '單價',
    amount                  DECIMAL(20,4)                       NOT NULL COMMENT '明細金額',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    revenue_account_sid     VARCHAR(32)                             NULL COMMENT '收入科目序號',
    CONSTRAINT fk_ari_receivable
        FOREIGN KEY (receivable_nid) REFERENCES acc_receivable(nid),
    CONSTRAINT uk_ari_receivable_line UNIQUE (receivable_nid, line_no),
    INDEX idx_ari_receivable_nid (receivable_nid),
    INDEX idx_ari_reference (reference_type, reference_sid),
    INDEX idx_ari_project_sid (project_sid),
    INDEX idx_ari_wbs_sid (wbs_sid),
    INDEX idx_ari_revenue_account_sid (revenue_account_sid),
    CHECK (line_no > 0),
    CHECK (quantity IS NULL OR quantity > 0),
    CHECK (unit_price IS NULL OR unit_price >= 0),
    CHECK (amount > 0),
    CHECK (tax_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應收帳款明細';

-- =========================================================
-- 03. 應付帳款
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_payable (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '應付帳款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payable_no              VARCHAR(100)                        NOT NULL COMMENT '應付單號',
    document_type_sid       VARCHAR(32)                         NOT NULL COMMENT '財務單據類型序號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    business_unit_sid       VARCHAR(32)                             NULL COMMENT '營運單位序號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    purchase_order_sid      VARCHAR(32)                             NULL COMMENT 'PurchaseDB採購單序號',
    receipt_sid             VARCHAR(32)                             NULL COMMENT 'PurchaseDB收貨單序號',
    invoice_sid             VARCHAR(32)                             NULL COMMENT 'InvoiceTaxDB進項發票序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT 'ContractDB合約序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    transaction_date        DATE                                NOT NULL COMMENT '交易日期',
    posting_date            DATE                                    NULL COMMENT '過帳日期',
    due_date                DATE                                NOT NULL COMMENT '到期日',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    original_amount         DECIMAL(20,4)                       NOT NULL COMMENT '原始應付金額',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    paid_amount             DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '已付金額',
    debit_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '扣款與折讓金額',
    writeoff_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '沖銷金額',
    outstanding_amount      DECIMAL(20,4)                       NOT NULL COMMENT '未付餘額',
    payable_status          VARCHAR(30)                         NOT NULL DEFAULT 'OPEN' COMMENT 'DRAFT草稿;OPEN未付;PARTIAL部分付款;PAID已付清;OVERDUE逾期;DISPUTED爭議;HELD暫停付款;WRITTEN_OFF已沖銷;CANCELLED取消',
    payment_hold_mark       TINYINT(1)                          NOT NULL DEFAULT 0 COMMENT '是否停止付款',
    hold_reason             TEXT                                    NULL COMMENT '停止付款原因',
    accounting_period_sid   VARCHAR(32)                             NULL COMMENT '會計期間序號',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    version_no              BIGINT UNSIGNED                     NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_apay_payable_no UNIQUE (payable_no),
    INDEX idx_apay_company_sid (company_sid),
    INDEX idx_apay_supplier_party_sid (supplier_party_sid),
    INDEX idx_apay_purchase_order_sid (purchase_order_sid),
    INDEX idx_apay_receipt_sid (receipt_sid),
    INDEX idx_apay_invoice_sid (invoice_sid),
    INDEX idx_apay_contract_sid (contract_sid),
    INDEX idx_apay_project_sid (project_sid),
    INDEX idx_apay_site_sid (site_sid),
    INDEX idx_apay_wbs_sid (wbs_sid),
    INDEX idx_apay_cost_center_sid (cost_center_sid),
    INDEX idx_apay_due_date (due_date),
    INDEX idx_apay_status (payable_status),
    INDEX idx_apay_payment_hold_mark (payment_hold_mark),
    INDEX idx_apay_accounting_period_sid (accounting_period_sid),
    INDEX idx_apay_journal_request_sid (journal_request_sid),
    INDEX idx_apay_correlation_id (correlation_id),
    INDEX idx_apay_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (original_amount > 0),
    CHECK (tax_amount >= 0),
    CHECK (paid_amount >= 0),
    CHECK (debit_amount >= 0),
    CHECK (writeoff_amount >= 0),
    CHECK (outstanding_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應付帳款主檔';

CREATE TABLE IF NOT EXISTS acc_payable_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '應付帳款明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    payable_nid             BIGINT UNSIGNED                     NOT NULL COMMENT '應付帳款流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    reference_type          VARCHAR(30)                         NOT NULL COMMENT 'PO_ITEM採購明細;RECEIPT_ITEM收貨明細;INVOICE_ITEM發票明細;EXPENSE費用;MILESTONE里程碑;ADJUSTMENT調整',
    reference_sid           VARCHAR(32)                         NOT NULL COMMENT '來源明細序號',
    description             VARCHAR(1000)                           NULL COMMENT '明細說明',
    quantity                DECIMAL(20,6)                           NULL COMMENT '數量',
    unit_sid                VARCHAR(32)                             NULL COMMENT '單位序號',
    unit_price              DECIMAL(20,6)                           NULL COMMENT '單價',
    amount                  DECIMAL(20,4)                       NOT NULL COMMENT '明細金額',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    expense_account_sid     VARCHAR(32)                             NULL COMMENT '費用或成本科目序號',
    CONSTRAINT fk_api_payable
        FOREIGN KEY (payable_nid) REFERENCES acc_payable(nid),
    CONSTRAINT uk_api_payable_line UNIQUE (payable_nid, line_no),
    INDEX idx_api_payable_nid (payable_nid),
    INDEX idx_api_reference (reference_type, reference_sid),
    INDEX idx_api_project_sid (project_sid),
    INDEX idx_api_wbs_sid (wbs_sid),
    INDEX idx_api_expense_account_sid (expense_account_sid),
    CHECK (line_no > 0),
    CHECK (quantity IS NULL OR quantity > 0),
    CHECK (unit_price IS NULL OR unit_price >= 0),
    CHECK (amount > 0),
    CHECK (tax_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應付帳款明細';

-- =========================================================
-- 04. 收款
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_receipt (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '收款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    receipt_no              VARCHAR(100)                        NOT NULL COMMENT '收款單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    customer_party_sid      VARCHAR(32)                             NULL COMMENT '客戶Party序號',
    payer_party_sid         VARCHAR(32)                             NULL COMMENT '實際付款Party序號',
    payment_request_sid     VARCHAR(32)                             NULL COMMENT 'PaymentDB付款請求序號',
    payment_transaction_sid VARCHAR(32)                             NULL COMMENT 'PaymentDB成功交易序號',
    bank_account_sid        VARCHAR(32)                             NULL COMMENT 'PartyDB收款銀行帳戶序號',
    receipt_method          VARCHAR(30)                         NOT NULL COMMENT 'CREDIT_CARD信用卡;BANK_TRANSFER轉帳;VIRTUAL_ACCOUNT虛擬帳號;CASH現金;CHECK支票;COD貨到付款;WALLET電子錢包;OTHER',
    receipt_date            DATETIME                            NOT NULL COMMENT '收款時間',
    value_date              DATE                                    NULL COMMENT '銀行價值日',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    receipt_amount          DECIMAL(20,4)                       NOT NULL COMMENT '收款金額',
    fee_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '手續費',
    net_amount              DECIMAL(20,4)                       NOT NULL COMMENT '淨收款金額',
    unapplied_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未沖帳金額',
    receipt_status          VARCHAR(30)                         NOT NULL DEFAULT 'UNAPPLIED' COMMENT 'DRAFT草稿;UNAPPLIED未沖帳;PARTIAL部分沖帳;APPLIED已沖帳;REVERSED已沖正;CANCELLED取消',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_arc_receipt_no UNIQUE (receipt_no),
    INDEX idx_arc_company_sid (company_sid),
    INDEX idx_arc_customer_party_sid (customer_party_sid),
    INDEX idx_arc_payer_party_sid (payer_party_sid),
    INDEX idx_arc_payment_request_sid (payment_request_sid),
    INDEX idx_arc_payment_transaction_sid (payment_transaction_sid),
    INDEX idx_arc_bank_account_sid (bank_account_sid),
    INDEX idx_arc_receipt_date (receipt_date),
    INDEX idx_arc_status (receipt_status),
    INDEX idx_arc_journal_request_sid (journal_request_sid),
    INDEX idx_arc_correlation_id (correlation_id),
    INDEX idx_arc_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (receipt_amount > 0),
    CHECK (fee_amount >= 0),
    CHECK (net_amount >= 0),
    CHECK (unapplied_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收款主檔';

CREATE TABLE IF NOT EXISTS acc_receipt_application (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '收款沖帳序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    receipt_sid             VARCHAR(32)                         NOT NULL COMMENT '收款序號',
    receivable_sid          VARCHAR(32)                         NOT NULL COMMENT '應收帳款序號',
    applied_amount          DECIMAL(20,4)                       NOT NULL COMMENT '沖帳金額',
    discount_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '現金折扣',
    writeoff_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '小額沖銷',
    exchange_gain_loss      DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '匯兌損益，可正可負',
    application_date        DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '沖帳時間',
    application_status      VARCHAR(20)                         NOT NULL DEFAULT 'APPLIED' COMMENT 'APPLIED已沖帳;REVERSED已沖回',
    reversal_sid            VARCHAR(32)                             NULL COMMENT '沖回紀錄序號',
    CONSTRAINT uk_ara_receipt_receivable UNIQUE (receipt_sid, receivable_sid),
    INDEX idx_ara_receipt_sid (receipt_sid),
    INDEX idx_ara_receivable_sid (receivable_sid),
    INDEX idx_ara_application_date (application_date),
    INDEX idx_ara_status (application_status),
    CHECK (applied_amount > 0),
    CHECK (discount_amount >= 0),
    CHECK (writeoff_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收款沖銷應收帳款';

-- =========================================================
-- 05. 付款
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_payment (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '付款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payment_no              VARCHAR(100)                        NOT NULL COMMENT '付款單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    supplier_party_sid      VARCHAR(32)                             NULL COMMENT '供應商Party序號',
    payee_party_sid         VARCHAR(32)                             NULL COMMENT '實際收款Party序號',
    bank_account_sid        VARCHAR(32)                             NULL COMMENT '公司付款銀行帳戶序號',
    payee_bank_account_sid  VARCHAR(32)                             NULL COMMENT '收款方銀行帳戶序號',
    payment_method          VARCHAR(30)                         NOT NULL COMMENT 'BANK_TRANSFER轉帳;CHECK支票;CASH現金;WALLET電子錢包;OTHER',
    payment_date            DATETIME                            NOT NULL COMMENT '付款時間',
    value_date              DATE                                    NULL COMMENT '銀行價值日',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    exchange_rate           DECIMAL(20,10)                      NOT NULL DEFAULT 1 COMMENT '匯率',
    payment_amount          DECIMAL(20,4)                       NOT NULL COMMENT '付款金額',
    fee_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '手續費',
    net_amount              DECIMAL(20,4)                       NOT NULL COMMENT '實際支出金額',
    unapplied_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未沖帳金額',
    payment_status          VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;PROCESSING處理中;UNAPPLIED未沖帳;PARTIAL部分沖帳;APPLIED已沖帳;FAILED失敗;REVERSED已沖正;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_apt_payment_no UNIQUE (payment_no),
    INDEX idx_apt_company_sid (company_sid),
    INDEX idx_apt_supplier_party_sid (supplier_party_sid),
    INDEX idx_apt_payee_party_sid (payee_party_sid),
    INDEX idx_apt_bank_account_sid (bank_account_sid),
    INDEX idx_apt_payee_bank_account_sid (payee_bank_account_sid),
    INDEX idx_apt_payment_date (payment_date),
    INDEX idx_apt_status (payment_status),
    INDEX idx_apt_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_apt_journal_request_sid (journal_request_sid),
    INDEX idx_apt_correlation_id (correlation_id),
    INDEX idx_apt_avalible (avalible),
    CHECK (exchange_rate > 0),
    CHECK (payment_amount > 0),
    CHECK (fee_amount >= 0),
    CHECK (net_amount >= 0),
    CHECK (unapplied_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付款主檔';

CREATE TABLE IF NOT EXISTS acc_payment_application (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '付款沖帳序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    payment_sid             VARCHAR(32)                         NOT NULL COMMENT '付款序號',
    payable_sid             VARCHAR(32)                         NOT NULL COMMENT '應付帳款序號',
    applied_amount          DECIMAL(20,4)                       NOT NULL COMMENT '沖帳金額',
    discount_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '付款折扣',
    writeoff_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '小額沖銷',
    exchange_gain_loss      DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '匯兌損益，可正可負',
    application_date        DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '沖帳時間',
    application_status      VARCHAR(20)                         NOT NULL DEFAULT 'APPLIED' COMMENT 'APPLIED已沖帳;REVERSED已沖回',
    reversal_sid            VARCHAR(32)                             NULL COMMENT '沖回紀錄序號',
    CONSTRAINT uk_apa_payment_payable UNIQUE (payment_sid, payable_sid),
    INDEX idx_apa_payment_sid (payment_sid),
    INDEX idx_apa_payable_sid (payable_sid),
    INDEX idx_apa_application_date (application_date),
    INDEX idx_apa_status (application_status),
    CHECK (applied_amount > 0),
    CHECK (discount_amount >= 0),
    CHECK (writeoff_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='付款沖銷應付帳款';

-- =========================================================
-- 06. 預收與預付
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_advance_receipt (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '預收款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    advance_no              VARCHAR(100)                        NOT NULL COMMENT '預收款單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    customer_party_sid      VARCHAR(32)                         NOT NULL COMMENT '客戶Party序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT '合約序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    source_type             VARCHAR(30)                         NOT NULL COMMENT 'ORDER_DEPOSIT訂單訂金;CONTRACT_ADVANCE合約預收;PROJECT_ADVANCE專案預收;MANUAL人工',
    source_sid              VARCHAR(32)                             NULL COMMENT '來源資料序號',
    receipt_sid             VARCHAR(32)                             NULL COMMENT '收款序號',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    advance_amount          DECIMAL(20,4)                       NOT NULL COMMENT '預收金額',
    applied_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '已轉應收金額',
    remaining_amount        DECIMAL(20,4)                       NOT NULL COMMENT '剩餘預收金額',
    advance_status          VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN未使用;PARTIAL部分使用;APPLIED已用完;REFUNDED已退款;CANCELLED取消',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    CONSTRAINT uk_aar_advance_no UNIQUE (advance_no),
    INDEX idx_aar_company_sid (company_sid),
    INDEX idx_aar_customer_party_sid (customer_party_sid),
    INDEX idx_aar_contract_sid (contract_sid),
    INDEX idx_aar_project_sid (project_sid),
    INDEX idx_aar_source (source_type, source_sid),
    INDEX idx_aar_receipt_sid (receipt_sid),
    INDEX idx_aar_status (advance_status),
    CHECK (advance_amount > 0),
    CHECK (applied_amount >= 0),
    CHECK (remaining_amount >= 0),
    CHECK (applied_amount + remaining_amount <= advance_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶預收款與訂金';

CREATE TABLE IF NOT EXISTS acc_prepayment (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '預付款序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    prepayment_no           VARCHAR(100)                        NOT NULL COMMENT '預付款單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    supplier_party_sid      VARCHAR(32)                         NOT NULL COMMENT '供應商Party序號',
    contract_sid            VARCHAR(32)                             NULL COMMENT '合約序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    source_type             VARCHAR(30)                         NOT NULL COMMENT 'PO_DEPOSIT採購訂金;CONTRACT_PREPAYMENT合約預付;PROJECT_PREPAYMENT專案預付;MANUAL人工',
    source_sid              VARCHAR(32)                             NULL COMMENT '來源資料序號',
    payment_sid             VARCHAR(32)                             NULL COMMENT '付款序號',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    prepayment_amount       DECIMAL(20,4)                       NOT NULL COMMENT '預付金額',
    applied_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '已轉應付金額',
    remaining_amount        DECIMAL(20,4)                       NOT NULL COMMENT '剩餘預付金額',
    prepayment_status       VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN未使用;PARTIAL部分使用;APPLIED已用完;REFUNDED已退回;CANCELLED取消',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    CONSTRAINT uk_app_prepayment_no UNIQUE (prepayment_no),
    INDEX idx_app_company_sid (company_sid),
    INDEX idx_app_supplier_party_sid (supplier_party_sid),
    INDEX idx_app_contract_sid (contract_sid),
    INDEX idx_app_project_sid (project_sid),
    INDEX idx_app_source (source_type, source_sid),
    INDEX idx_app_payment_sid (payment_sid),
    INDEX idx_app_status (prepayment_status),
    CHECK (prepayment_amount > 0),
    CHECK (applied_amount >= 0),
    CHECK (remaining_amount >= 0),
    CHECK (applied_amount + remaining_amount <= prepayment_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供應商預付款與採購訂金';

-- =========================================================
-- 07. 費用與報支
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_expense (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '費用單序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    expense_no              VARCHAR(100)                        NOT NULL COMMENT '費用單號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    department_sid          VARCHAR(32)                             NULL COMMENT '部門序號',
    employee_party_sid      VARCHAR(32)                             NULL COMMENT '申請員工Party序號',
    supplier_party_sid      VARCHAR(32)                             NULL COMMENT '費用供應商Party序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    expense_date            DATE                                NOT NULL COMMENT '費用日期',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    total_amount            DECIMAL(20,4)                       NOT NULL COMMENT '費用總額',
    reimbursable_amount     DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '可報支金額',
    payable_sid             VARCHAR(32)                             NULL COMMENT '產生的應付帳款序號',
    expense_status          VARCHAR(30)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;REVIEW待審;APPROVED核准;REJECTED駁回;PAYABLE_CREATED已建應付;PAID已付款;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid       VARCHAR(32)                             NULL COMMENT '核准人員序號',
    approved_date           DATETIME                                NULL COMMENT '核准時間',
    avalible                VARCHAR(2)                          NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark                  TEXT                                    NULL COMMENT '備註',
    CONSTRAINT uk_ae_expense_no UNIQUE (expense_no),
    INDEX idx_ae_company_sid (company_sid),
    INDEX idx_ae_department_sid (department_sid),
    INDEX idx_ae_employee_party_sid (employee_party_sid),
    INDEX idx_ae_supplier_party_sid (supplier_party_sid),
    INDEX idx_ae_project_sid (project_sid),
    INDEX idx_ae_site_sid (site_sid),
    INDEX idx_ae_wbs_sid (wbs_sid),
    INDEX idx_ae_cost_center_sid (cost_center_sid),
    INDEX idx_ae_expense_date (expense_date),
    INDEX idx_ae_payable_sid (payable_sid),
    INDEX idx_ae_status (expense_status),
    INDEX idx_ae_workflow_instance_sid (workflow_instance_sid),
    INDEX idx_ae_avalible (avalible),
    CHECK (total_amount > 0),
    CHECK (reimbursable_amount >= 0),
    CHECK (reimbursable_amount <= total_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='費用申請與報支';

CREATE TABLE IF NOT EXISTS acc_expense_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '費用明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    expense_nid             BIGINT UNSIGNED                     NOT NULL COMMENT '費用單流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    expense_category_sid    VARCHAR(32)                         NOT NULL COMMENT '費用分類序號',
    description             VARCHAR(1000)                       NOT NULL COMMENT '費用說明',
    expense_date            DATE                                NOT NULL COMMENT '費用日期',
    amount                  DECIMAL(20,4)                       NOT NULL COMMENT '未稅金額',
    tax_amount              DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '稅額',
    total_amount            DECIMAL(20,4)                       NOT NULL COMMENT '含稅總額',
    tax_sid                 VARCHAR(32)                             NULL COMMENT '稅別序號',
    invoice_sid             VARCHAR(32)                             NULL COMMENT 'InvoiceTaxDB憑證序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    expense_account_sid     VARCHAR(32)                             NULL COMMENT '費用科目序號',
    file_sid                VARCHAR(32)                             NULL COMMENT 'FileDB收據或發票附件序號',
    CONSTRAINT fk_aei_expense
        FOREIGN KEY (expense_nid) REFERENCES acc_expense(nid),
    CONSTRAINT uk_aei_expense_line UNIQUE (expense_nid, line_no),
    INDEX idx_aei_expense_nid (expense_nid),
    INDEX idx_aei_expense_category_sid (expense_category_sid),
    INDEX idx_aei_invoice_sid (invoice_sid),
    INDEX idx_aei_project_sid (project_sid),
    INDEX idx_aei_wbs_sid (wbs_sid),
    INDEX idx_aei_cost_center_sid (cost_center_sid),
    INDEX idx_aei_expense_account_sid (expense_account_sid),
    CHECK (line_no > 0),
    CHECK (amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (total_amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='費用報支明細';

-- =========================================================
-- 08. 折讓、貸項與借項
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_credit_debit_note (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '折讓借貸項序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    note_no                 VARCHAR(100)                        NOT NULL COMMENT '折讓或借貸項單號',
    note_type               VARCHAR(20)                         NOT NULL COMMENT 'AR_CREDIT應收貸項;AR_DEBIT應收借項;AP_CREDIT應付貸項;AP_DEBIT應付借項',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    party_sid               VARCHAR(32)                         NOT NULL COMMENT '客戶或供應商Party序號',
    receivable_sid          VARCHAR(32)                             NULL COMMENT '應收帳款序號',
    payable_sid             VARCHAR(32)                             NULL COMMENT '應付帳款序號',
    return_case_sid         VARCHAR(32)                             NULL COMMENT 'ReturnAfterSalesDB售後案件序號',
    supplier_claim_sid      VARCHAR(32)                             NULL COMMENT 'ReturnAfterSalesDB供應商追償序號',
    invoice_allowance_sid   VARCHAR(32)                             NULL COMMENT 'InvoiceTaxDB折讓序號',
    note_date               DATE                                NOT NULL COMMENT '單據日期',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    note_amount             DECIMAL(20,4)                       NOT NULL COMMENT '調整金額',
    reason_code             VARCHAR(50)                         NOT NULL COMMENT '原因代碼',
    reason                  TEXT                                    NULL COMMENT '原因說明',
    note_status             VARCHAR(20)                         NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;APPROVED核准;APPLIED已套用;CANCELLED取消',
    workflow_instance_sid   VARCHAR(32)                             NULL COMMENT 'WorkflowDB流程實例序號',
    journal_request_sid     VARCHAR(32)                             NULL COMMENT '傳票請求序號',
    CONSTRAINT uk_acdn_note_no UNIQUE (note_no),
    INDEX idx_acdn_note_type (note_type),
    INDEX idx_acdn_company_sid (company_sid),
    INDEX idx_acdn_party_sid (party_sid),
    INDEX idx_acdn_receivable_sid (receivable_sid),
    INDEX idx_acdn_payable_sid (payable_sid),
    INDEX idx_acdn_return_case_sid (return_case_sid),
    INDEX idx_acdn_supplier_claim_sid (supplier_claim_sid),
    INDEX idx_acdn_note_date (note_date),
    INDEX idx_acdn_status (note_status),
    CHECK (note_amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應收應付折讓、貸項與借項';

-- =========================================================
-- 09. 對帳、沖帳與調整
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_reconciliation (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務對帳序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    reconciliation_no       VARCHAR(100)                        NOT NULL COMMENT '對帳編號',
    reconciliation_type     VARCHAR(30)                         NOT NULL COMMENT 'BANK銀行;PAYMENT_PROVIDER金流商;CUSTOMER客戶;SUPPLIER供應商;INTERCOMPANY關係企業',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    party_sid               VARCHAR(32)                             NULL COMMENT '對帳Party序號',
    bank_account_sid        VARCHAR(32)                             NULL COMMENT '銀行帳戶序號',
    period_start_date       DATE                                NOT NULL COMMENT '期間開始日',
    period_end_date         DATE                                NOT NULL COMMENT '期間結束日',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    opening_balance         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '期初餘額',
    closing_balance         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '期末餘額',
    matched_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '已比對金額',
    difference_amount       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '差異金額',
    statement_file_sid      VARCHAR(32)                             NULL COMMENT 'FileDB對帳檔序號',
    reconciliation_status   VARCHAR(20)                         NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN未開始;PROCESSING處理中;MATCHED已完成;DIFFERENCE有差異;CLOSED結案',
    responsible_user_sid    VARCHAR(32)                             NULL COMMENT '負責人員序號',
    completed_date          DATETIME                                NULL COMMENT '完成時間',
    CONSTRAINT uk_arec2_reconciliation_no UNIQUE (reconciliation_no),
    INDEX idx_arec2_type (reconciliation_type),
    INDEX idx_arec2_company_sid (company_sid),
    INDEX idx_arec2_party_sid (party_sid),
    INDEX idx_arec2_bank_account_sid (bank_account_sid),
    INDEX idx_arec2_period (period_start_date, period_end_date),
    INDEX idx_arec2_status (reconciliation_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (matched_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='銀行、金流商、客戶與供應商對帳';

CREATE TABLE IF NOT EXISTS acc_reconciliation_item (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務對帳明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    reconciliation_nid      BIGINT UNSIGNED                     NOT NULL COMMENT '對帳主檔流水號',
    line_no                 INT                                 NOT NULL COMMENT '明細行號',
    external_reference_no   VARCHAR(200)                            NULL COMMENT '外部參考號',
    internal_type           VARCHAR(30)                             NULL COMMENT 'RECEIPT;PAYMENT;RECEIVABLE;PAYABLE;SETTLEMENT;OTHER',
    internal_sid            VARCHAR(32)                             NULL COMMENT '內部資料序號',
    transaction_date        DATE                                    NULL COMMENT '交易日期',
    external_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '外部金額',
    internal_amount         DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '內部金額',
    difference_amount       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '差異金額',
    match_status            VARCHAR(20)                         NOT NULL DEFAULT 'UNMATCHED' COMMENT 'UNMATCHED未比對;MATCHED一致;AMOUNT_DIFF金額差異;DATE_DIFF日期差異;MISSING_INTERNAL缺內部;MISSING_EXTERNAL缺外部;RESOLVED已處理',
    resolution_note         TEXT                                    NULL COMMENT '處理說明',
    CONSTRAINT fk_ari2_reconciliation
        FOREIGN KEY (reconciliation_nid) REFERENCES acc_reconciliation(nid),
    CONSTRAINT uk_ari2_reconciliation_line UNIQUE (reconciliation_nid, line_no),
    INDEX idx_ari2_reconciliation_nid (reconciliation_nid),
    INDEX idx_ari2_external_reference_no (external_reference_no),
    INDEX idx_ari2_internal (internal_type, internal_sid),
    INDEX idx_ari2_match_status (match_status),
    CHECK (line_no > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='財務對帳明細';

-- =========================================================
-- 10. 財務傳票介面
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_journal_request (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '傳票請求序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date             DATETIME                                NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    journal_request_no      VARCHAR(100)                        NOT NULL COMMENT '傳票請求編號',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    source_module           VARCHAR(30)                         NOT NULL COMMENT 'AR;AP;RECEIPT;PAYMENT;EXPENSE;PREPAYMENT;ADVANCE;CREDIT;INVENTORY;PROJECT',
    source_type             VARCHAR(50)                         NOT NULL COMMENT '來源資料類型',
    source_sid              VARCHAR(32)                         NOT NULL COMMENT '來源資料序號',
    posting_date            DATE                                NOT NULL COMMENT '預計過帳日期',
    accounting_period_sid   VARCHAR(32)                             NULL COMMENT '會計期間序號',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    total_debit_amount      DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '借方總額',
    total_credit_amount     DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '貸方總額',
    request_status          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;VALIDATING驗證中;READY可過帳;POSTED已過帳;FAILED失敗;CANCELLED取消',
    general_ledger_journal_sid VARCHAR(32)                          NULL COMMENT 'GeneralLedgerDB正式傳票序號',
    idempotency_key         VARCHAR(200)                        NOT NULL COMMENT '冪等Key',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    posted_date             DATETIME                                NULL COMMENT '實際過帳時間',
    error_message           LONGTEXT                                NULL COMMENT '錯誤訊息',
    CONSTRAINT uk_ajr_request_no UNIQUE (journal_request_no),
    CONSTRAINT uk_ajr_idempotency_key UNIQUE (idempotency_key),
    INDEX idx_ajr_company_sid (company_sid),
    INDEX idx_ajr_source (source_module, source_type, source_sid),
    INDEX idx_ajr_posting_date (posting_date),
    INDEX idx_ajr_accounting_period_sid (accounting_period_sid),
    INDEX idx_ajr_status (request_status),
    INDEX idx_ajr_general_ledger_journal_sid (general_ledger_journal_sid),
    INDEX idx_ajr_correlation_id (correlation_id),
    CHECK (total_debit_amount >= 0),
    CHECK (total_credit_amount >= 0),
    CHECK (total_debit_amount = total_credit_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='營運子帳轉總帳傳票請求';

CREATE TABLE IF NOT EXISTS acc_journal_request_line (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '傳票請求明細序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    journal_request_nid     BIGINT UNSIGNED                     NOT NULL COMMENT '傳票請求流水號',
    line_no                 INT                                 NOT NULL COMMENT '分錄行號',
    account_sid             VARCHAR(32)                         NOT NULL COMMENT '會計科目序號',
    debit_amount            DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '借方金額',
    credit_amount           DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '貸方金額',
    description             VARCHAR(1000)                           NULL COMMENT '分錄說明',
    party_sid               VARCHAR(32)                             NULL COMMENT '往來Party序號',
    project_sid             VARCHAR(32)                             NULL COMMENT '專案序號',
    site_sid                VARCHAR(32)                             NULL COMMENT '工地序號',
    wbs_sid                 VARCHAR(32)                             NULL COMMENT 'WBS序號',
    cost_center_sid         VARCHAR(32)                             NULL COMMENT '成本中心序號',
    department_sid          VARCHAR(32)                             NULL COMMENT '部門序號',
    tax_sid                 VARCHAR(32)                             NULL COMMENT '稅別序號',
    reference_type          VARCHAR(30)                             NULL COMMENT '來源明細類型',
    reference_sid           VARCHAR(32)                             NULL COMMENT '來源明細序號',
    CONSTRAINT fk_ajrl_request
        FOREIGN KEY (journal_request_nid) REFERENCES acc_journal_request(nid),
    CONSTRAINT uk_ajrl_request_line UNIQUE (journal_request_nid, line_no),
    INDEX idx_ajrl_request_nid (journal_request_nid),
    INDEX idx_ajrl_account_sid (account_sid),
    INDEX idx_ajrl_party_sid (party_sid),
    INDEX idx_ajrl_project_sid (project_sid),
    INDEX idx_ajrl_site_sid (site_sid),
    INDEX idx_ajrl_wbs_sid (wbs_sid),
    INDEX idx_ajrl_cost_center_sid (cost_center_sid),
    INDEX idx_ajrl_reference (reference_type, reference_sid),
    CHECK (line_no > 0),
    CHECK (debit_amount >= 0),
    CHECK (credit_amount >= 0),
    CHECK ((debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='傳票請求分錄明細';

-- =========================================================
-- 11. 帳齡與財務快照
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_aging_snapshot (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '帳齡快照序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    snapshot_date           DATE                                NOT NULL COMMENT '快照日期',
    ledger_type             VARCHAR(10)                         NOT NULL COMMENT 'AR應收;AP應付',
    company_sid             VARCHAR(32)                         NOT NULL COMMENT '公司序號',
    party_sid               VARCHAR(32)                         NOT NULL COMMENT '客戶或供應商Party序號',
    currency_sid            VARCHAR(32)                         NOT NULL COMMENT '幣別序號',
    current_amount          DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未到期金額',
    days_1_30_amount        DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '逾期1至30天',
    days_31_60_amount       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '逾期31至60天',
    days_61_90_amount       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '逾期61至90天',
    days_91_180_amount      DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '逾期91至180天',
    days_over_180_amount    DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '逾期180天以上',
    total_outstanding       DECIMAL(20,4)                       NOT NULL DEFAULT 0 COMMENT '未結總額',
    CONSTRAINT uk_aas_snapshot UNIQUE (snapshot_date, ledger_type, company_sid, party_sid, currency_sid),
    INDEX idx_aas_snapshot_date (snapshot_date),
    INDEX idx_aas_ledger_type (ledger_type),
    INDEX idx_aas_company_sid (company_sid),
    INDEX idx_aas_party_sid (party_sid),
    CHECK (current_amount >= 0),
    CHECK (days_1_30_amount >= 0),
    CHECK (days_31_60_amount >= 0),
    CHECK (days_61_90_amount >= 0),
    CHECK (days_91_180_amount >= 0),
    CHECK (days_over_180_amount >= 0),
    CHECK (total_outstanding >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='應收應付帳齡快照';

-- =========================================================
-- 12. 狀態歷程與事件
-- =========================================================

CREATE TABLE IF NOT EXISTS acc_status_history (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務狀態歷程序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'RECEIVABLE;PAYABLE;RECEIPT;PAYMENT;ADVANCE;PREPAYMENT;EXPENSE;CREDIT_NOTE;RECONCILIATION;JOURNAL_REQUEST',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '實體序號',
    old_status              VARCHAR(30)                             NULL COMMENT '原狀態',
    new_status              VARCHAR(30)                         NOT NULL COMMENT '新狀態',
    event_code              VARCHAR(100)                            NULL COMMENT '觸發事件代碼',
    operator_user_sid       VARCHAR(32)                             NULL COMMENT '操作人員序號',
    reason                  TEXT                                    NULL COMMENT '原因說明',
    correlation_id          VARCHAR(100)                            NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_ash_entity (entity_type, entity_sid),
    INDEX idx_ash_new_status (new_status),
    INDEX idx_ash_event_code (event_code),
    INDEX idx_ash_operator_user_sid (operator_user_sid),
    INDEX idx_ash_correlation_id (correlation_id),
    INDEX idx_ash_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='財務子帳狀態歷程';

CREATE TABLE IF NOT EXISTS acc_event (
    nid                     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid                     VARCHAR(32)                         NOT NULL UNIQUE COMMENT '財務事件序號',
    create_date             DATETIME                            NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type             VARCHAR(30)                         NOT NULL COMMENT 'RECEIVABLE;PAYABLE;RECEIPT;PAYMENT;EXPENSE;JOURNAL_REQUEST;RECONCILIATION',
    entity_sid              VARCHAR(32)                         NOT NULL COMMENT '實體序號',
    event_code              VARCHAR(120)                        NOT NULL COMMENT '事件代碼',
    event_version           INT                                 NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data              JSON                                    NULL COMMENT '事件內容',
    source_event_id         VARCHAR(100)                            NULL COMMENT '來源事件ID',
    correlation_id          VARCHAR(100)                            NULL COMMENT '關聯識別碼',
    causation_id            VARCHAR(100)                            NULL COMMENT '因果事件ID',
    outbox_event_sid        VARCHAR(32)                             NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status          VARCHAR(20)                         NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date          DATETIME                                NULL COMMENT '處理時間',
    error_message           TEXT                                    NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_ae_source_event_id (source_event_id),
    INDEX idx_ae_entity (entity_type, entity_sid),
    INDEX idx_ae_event_code (event_code),
    INDEX idx_ae_correlation_id (correlation_id),
    INDEX idx_ae_outbox_event_sid (outbox_event_sid),
    INDEX idx_ae_status (process_status),
    INDEX idx_ae_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='財務子帳領域事件';

SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
