namespace B2bOrder.Resources.HumanResource
{
    /// <summary>
    /// HumanResourcePayrollDB V2 Shared Core Schema
    /// 支援員工、排班、出勤、請假、加班、工時、薪資、獎金、扣款、勞健保與專案人工成本。
    /// nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼。
    /// avalible：Y可用；W停用；D刪除。
    /// 適用 MySQL 8.x / InnoDB / utf8mb4。
    /// </summary>
    internal static class HumanResourcePayrollDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS hr_employee (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '員工序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_no VARCHAR(100) NOT NULL COMMENT '員工編號',
    party_sid VARCHAR(32) NOT NULL COMMENT 'PartyDB人員序號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    business_unit_sid VARCHAR(32) NULL COMMENT '營運單位序號',
    department_sid VARCHAR(32) NULL COMMENT '部門序號',
    position_sid VARCHAR(32) NULL COMMENT '職務序號',
    manager_employee_sid VARCHAR(32) NULL COMMENT '主管員工序號',
    hire_date DATE NOT NULL COMMENT '到職日',
    probation_end_date DATE NULL COMMENT '試用期截止日',
    termination_date DATE NULL COMMENT '離職日',
    employment_type VARCHAR(30) NOT NULL COMMENT 'FULL_TIME正職;PART_TIME兼職;CONTRACT合約;TEMP派遣;INTERN實習;CONSULTANT顧問',
    payroll_type VARCHAR(20) NOT NULL DEFAULT 'MONTHLY' COMMENT 'MONTHLY月薪;HOURLY時薪;DAILY日薪;PIECE計件',
    base_currency_sid VARCHAR(32) NOT NULL COMMENT '薪資幣別序號',
    employee_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ONBOARDING報到中;ACTIVE在職;LEAVE留停;SUSPENDED停職;TERMINATED離職',
    version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_he_employee_no UNIQUE (employee_no),
    INDEX idx_he_party_sid (party_sid),
    INDEX idx_he_company_sid (company_sid),
    INDEX idx_he_department_sid (department_sid),
    INDEX idx_he_position_sid (position_sid),
    INDEX idx_he_manager_employee_sid (manager_employee_sid),
    INDEX idx_he_status (employee_status),
    INDEX idx_he_avalible (avalible),
    CHECK (termination_date IS NULL OR termination_date >= hire_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工主檔';

CREATE TABLE IF NOT EXISTS hr_position (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '職務序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    position_code VARCHAR(100) NOT NULL COMMENT '職務代碼',
    position_name VARCHAR(200) NOT NULL COMMENT '職務名稱',
    job_family VARCHAR(100) NULL COMMENT '職系',
    job_level VARCHAR(50) NULL COMMENT '職等',
    management_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否管理職',
    default_cost_center_sid VARCHAR(32) NULL COMMENT '預設成本中心序號',
    position_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_hp_position_code UNIQUE (position_code),
    INDEX idx_hp_job_family (job_family),
    INDEX idx_hp_job_level (job_level),
    INDEX idx_hp_status (position_status),
    INDEX idx_hp_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='職務與職等';

CREATE TABLE IF NOT EXISTS hr_employment_contract (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '任用合約序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    contract_no VARCHAR(100) NOT NULL COMMENT '任用合約編號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    contract_type VARCHAR(30) NOT NULL COMMENT 'PERMANENT不定期;FIXED_TERM定期;PART_TIME兼職;CONSULTING顧問;PROJECT專案',
    start_date DATE NOT NULL COMMENT '開始日',
    end_date DATE NULL COMMENT '結束日',
    monthly_salary DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '月薪',
    hourly_rate DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '時薪',
    overtime_eligible TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否計算加班',
    standard_hours_per_week DECIMAL(10,4) NOT NULL DEFAULT 40 COMMENT '每週標準工時',
    probation_months INT NOT NULL DEFAULT 0 COMMENT '試用月數',
    contract_file_sid VARCHAR(32) NULL COMMENT 'FileDB合約文件序號',
    contract_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'DRAFT草稿;ACTIVE生效;EXPIRED到期;TERMINATED終止',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_hec_contract_no UNIQUE (contract_no),
    INDEX idx_hec_employee_sid (employee_sid),
    INDEX idx_hec_contract_type (contract_type),
    INDEX idx_hec_date_range (start_date, end_date),
    INDEX idx_hec_status (contract_status),
    CHECK (end_date IS NULL OR end_date >= start_date),
    CHECK (monthly_salary >= 0),
    CHECK (hourly_rate >= 0),
    CHECK (standard_hours_per_week >= 0),
    CHECK (probation_months >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工任用與薪資合約';

CREATE TABLE IF NOT EXISTS hr_shift (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '班別序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    shift_code VARCHAR(100) NOT NULL COMMENT '班別代碼',
    shift_name VARCHAR(200) NOT NULL COMMENT '班別名稱',
    start_time TIME NOT NULL COMMENT '上班時間',
    end_time TIME NOT NULL COMMENT '下班時間',
    break_minutes INT NOT NULL DEFAULT 60 COMMENT '休息分鐘',
    standard_work_minutes INT NOT NULL COMMENT '標準工作分鐘',
    cross_day_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否跨日',
    night_shift_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否夜班',
    shift_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_hs_shift_code UNIQUE (shift_code),
    INDEX idx_hs_night_shift_mark (night_shift_mark),
    INDEX idx_hs_status (shift_status),
    INDEX idx_hs_avalible (avalible),
    CHECK (break_minutes >= 0),
    CHECK (standard_work_minutes > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='班別';

CREATE TABLE IF NOT EXISTS hr_schedule (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '排班序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    schedule_date DATE NOT NULL COMMENT '排班日期',
    shift_sid VARCHAR(32) NOT NULL COMMENT '班別序號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    department_sid VARCHAR(32) NULL COMMENT '部門序號',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    site_sid VARCHAR(32) NULL COMMENT '工地序號',
    wbs_sid VARCHAR(32) NULL COMMENT 'WBS序號',
    scheduled_start DATETIME NOT NULL COMMENT '預定開始時間',
    scheduled_end DATETIME NOT NULL COMMENT '預定結束時間',
    schedule_status VARCHAR(20) NOT NULL DEFAULT 'PLANNED' COMMENT 'PLANNED已排班;CONFIRMED確認;CHANGED變更;CANCELLED取消',
    CONSTRAINT uk_hsch_employee_date UNIQUE (employee_sid, schedule_date),
    INDEX idx_hsch_shift_sid (shift_sid),
    INDEX idx_hsch_company_sid (company_sid),
    INDEX idx_hsch_project_sid (project_sid),
    INDEX idx_hsch_site_sid (site_sid),
    INDEX idx_hsch_status (schedule_status),
    CHECK (scheduled_end > scheduled_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工排班';

CREATE TABLE IF NOT EXISTS hr_attendance_record (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '出勤紀錄序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    attendance_date DATE NOT NULL COMMENT '出勤日期',
    schedule_sid VARCHAR(32) NULL COMMENT '排班序號',
    clock_in_time DATETIME NULL COMMENT '上班打卡時間',
    clock_out_time DATETIME NULL COMMENT '下班打卡時間',
    work_minutes INT NOT NULL DEFAULT 0 COMMENT '實際工作分鐘',
    late_minutes INT NOT NULL DEFAULT 0 COMMENT '遲到分鐘',
    early_leave_minutes INT NOT NULL DEFAULT 0 COMMENT '早退分鐘',
    absence_minutes INT NOT NULL DEFAULT 0 COMMENT '缺勤分鐘',
    source_type VARCHAR(20) NOT NULL DEFAULT 'DEVICE' COMMENT 'DEVICE打卡機;APP手機;WEB網頁;IMPORT匯入;MANUAL人工',
    device_sid VARCHAR(32) NULL COMMENT '打卡設備序號',
    latitude DECIMAL(10,7) NULL COMMENT '緯度',
    longitude DECIMAL(10,7) NULL COMMENT '經度',
    attendance_status VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL正常;LATE遲到;EARLY_LEAVE早退;ABSENT缺勤;INCOMPLETE缺卡;ADJUSTED已調整',
    INDEX idx_har_employee_date (employee_sid, attendance_date),
    INDEX idx_har_schedule_sid (schedule_sid),
    INDEX idx_har_source_type (source_type),
    INDEX idx_har_status (attendance_status),
    CHECK (clock_out_time IS NULL OR clock_in_time IS NULL OR clock_out_time >= clock_in_time),
    CHECK (work_minutes >= 0),
    CHECK (late_minutes >= 0),
    CHECK (early_leave_minutes >= 0),
    CHECK (absence_minutes >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工出勤與打卡紀錄';

CREATE TABLE IF NOT EXISTS hr_attendance_adjustment (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '出勤調整序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    adjustment_no VARCHAR(100) NOT NULL COMMENT '調整單號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    attendance_record_sid VARCHAR(32) NULL COMMENT '原出勤紀錄序號',
    adjustment_type VARCHAR(30) NOT NULL COMMENT 'MISSING_CLOCK補卡;TIME_CORRECTION時間更正;BUSINESS_TRIP出差;REMOTE_WORK遠端;OTHER',
    original_data JSON NULL COMMENT '原資料',
    adjusted_data JSON NOT NULL COMMENT '調整後資料',
    reason TEXT NOT NULL COMMENT '調整原因',
    adjustment_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;REJECTED駁回;APPLIED已套用',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    CONSTRAINT uk_haa_adjustment_no UNIQUE (adjustment_no),
    INDEX idx_haa_employee_sid (employee_sid),
    INDEX idx_haa_attendance_record_sid (attendance_record_sid),
    INDEX idx_haa_type (adjustment_type),
    INDEX idx_haa_status (adjustment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='補卡與出勤調整';

CREATE TABLE IF NOT EXISTS hr_leave_type (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '假別序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    leave_code VARCHAR(100) NOT NULL COMMENT '假別代碼',
    leave_name VARCHAR(200) NOT NULL COMMENT '假別名稱',
    paid_mark TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否給薪',
    annual_quota_days DECIMAL(10,4) NULL COMMENT '年度額度天數',
    carry_forward_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可遞延',
    carry_forward_limit_days DECIMAL(10,4) NULL COMMENT '遞延上限天數',
    proof_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需證明',
    minimum_unit_minutes INT NOT NULL DEFAULT 60 COMMENT '最小申請單位分鐘',
    leave_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_hlt_leave_code UNIQUE (leave_code),
    INDEX idx_hlt_paid_mark (paid_mark),
    INDEX idx_hlt_status (leave_status),
    INDEX idx_hlt_avalible (avalible),
    CHECK (annual_quota_days IS NULL OR annual_quota_days >= 0),
    CHECK (carry_forward_limit_days IS NULL OR carry_forward_limit_days >= 0),
    CHECK (minimum_unit_minutes > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='假別';

CREATE TABLE IF NOT EXISTS hr_leave_balance (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '假別餘額序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    leave_type_sid VARCHAR(32) NOT NULL COMMENT '假別序號',
    leave_year INT NOT NULL COMMENT '年度',
    granted_minutes INT NOT NULL DEFAULT 0 COMMENT '核給分鐘',
    carried_minutes INT NOT NULL DEFAULT 0 COMMENT '遞延分鐘',
    used_minutes INT NOT NULL DEFAULT 0 COMMENT '已用分鐘',
    pending_minutes INT NOT NULL DEFAULT 0 COMMENT '申請中分鐘',
    expired_minutes INT NOT NULL DEFAULT 0 COMMENT '到期分鐘',
    remaining_minutes INT NOT NULL DEFAULT 0 COMMENT '剩餘分鐘',
    CONSTRAINT uk_hlb_employee_leave_year UNIQUE (employee_sid, leave_type_sid, leave_year),
    INDEX idx_hlb_employee_sid (employee_sid),
    INDEX idx_hlb_leave_type_sid (leave_type_sid),
    CHECK (leave_year > 0),
    CHECK (granted_minutes >= 0),
    CHECK (carried_minutes >= 0),
    CHECK (used_minutes >= 0),
    CHECK (pending_minutes >= 0),
    CHECK (expired_minutes >= 0),
    CHECK (remaining_minutes >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工假別餘額';

CREATE TABLE IF NOT EXISTS hr_leave_request (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '請假申請序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    request_no VARCHAR(100) NOT NULL COMMENT '請假單號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    leave_type_sid VARCHAR(32) NOT NULL COMMENT '假別序號',
    start_date DATETIME NOT NULL COMMENT '開始時間',
    end_date DATETIME NOT NULL COMMENT '結束時間',
    leave_minutes INT NOT NULL COMMENT '請假分鐘',
    reason TEXT NULL COMMENT '請假原因',
    proof_file_sid VARCHAR(32) NULL COMMENT 'FileDB證明文件序號',
   delegate_employee_sid VARCHAR(32) NULL COMMENT '代理人員工序號',
    request_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;REJECTED駁回;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    CONSTRAINT uk_hlr_request_no UNIQUE (request_no),
    INDEX idx_hlr_employee_sid (employee_sid),
    INDEX idx_hlr_leave_type_sid (leave_type_sid),
    INDEX idx_hlr_date_range (start_date, end_date),
    INDEX idx_hlr_status (request_status),
    CHECK (end_date > start_date),
    CHECK (leave_minutes > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工請假申請';

CREATE TABLE IF NOT EXISTS hr_overtime_request (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '加班申請序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    request_no VARCHAR(100) NOT NULL COMMENT '加班單號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    overtime_date DATE NOT NULL COMMENT '加班日期',
    start_date DATETIME NOT NULL COMMENT '開始時間',
    end_date DATETIME NOT NULL COMMENT '結束時間',
    requested_minutes INT NOT NULL COMMENT '申請分鐘',
    approved_minutes INT NOT NULL DEFAULT 0 COMMENT '核准分鐘',
    overtime_type VARCHAR(30) NOT NULL COMMENT 'WEEKDAY平日;REST_DAY休息日;HOLIDAY假日;NIGHT夜間',
    compensation_type VARCHAR(20) NOT NULL DEFAULT 'PAY' COMMENT 'PAY加班費;COMP_TIME補休;MIXED混合',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    site_sid VARCHAR(32) NULL COMMENT '工地序號',
    wbs_sid VARCHAR(32) NULL COMMENT 'WBS序號',
    reason TEXT NOT NULL COMMENT '加班原因',
    request_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;REJECTED駁回;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    INDEX idx_hor_employee_sid (employee_sid),
    INDEX idx_hor_overtime_date (overtime_date),
    INDEX idx_hor_project_sid (project_sid),
    INDEX idx_hor_status (request_status),
    CHECK (end_date > start_date),
    CHECK (requested_minutes > 0),
    CHECK (approved_minutes >= 0),
    CHECK (approved_minutes <= requested_minutes)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='加班申請';

CREATE TABLE IF NOT EXISTS hr_timesheet (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '工時表序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    timesheet_no VARCHAR(100) NOT NULL COMMENT '工時表編號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    period_start_date DATE NOT NULL COMMENT '期間開始日',
    period_end_date DATE NOT NULL COMMENT '期間結束日',
    total_work_minutes INT NOT NULL DEFAULT 0 COMMENT '總工時分鐘',
    billable_minutes INT NOT NULL DEFAULT 0 COMMENT '可計費分鐘',
    overtime_minutes INT NOT NULL DEFAULT 0 COMMENT '加班分鐘',
    timesheet_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;REJECTED駁回;LOCKED鎖定',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    CONSTRAINT uk_ht_timesheet_no UNIQUE (timesheet_no),
    CONSTRAINT uk_ht_employee_period UNIQUE (employee_sid, period_start_date, period_end_date),
    INDEX idx_ht_employee_sid (employee_sid),
    INDEX idx_ht_period (period_start_date, period_end_date),
    INDEX idx_ht_status (timesheet_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (total_work_minutes >= 0),
    CHECK (billable_minutes >= 0),
    CHECK (overtime_minutes >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工工時表';

CREATE TABLE IF NOT EXISTS hr_timesheet_item (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '工時明細序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    timesheet_nid BIGINT UNSIGNED NOT NULL COMMENT '工時表流水號',
    line_no INT NOT NULL COMMENT '明細行號',
    work_date DATE NOT NULL COMMENT '工作日期',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    site_sid VARCHAR(32) NULL COMMENT '工地序號',
    wbs_sid VARCHAR(32) NULL COMMENT 'WBS序號',
    cost_code_sid VARCHAR(32) NULL COMMENT 'ProjectCostDB成本代碼序號',
    activity_code VARCHAR(100) NULL COMMENT '活動代碼',
    description VARCHAR(1000) NULL COMMENT '工作內容',
    work_minutes INT NOT NULL COMMENT '工作分鐘',
    overtime_minutes INT NOT NULL DEFAULT 0 COMMENT '加班分鐘',
    billable_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可對客戶計費',
    labor_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '人工成本',
    billing_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '可請款金額',
    CONSTRAINT fk_hti_timesheet FOREIGN KEY (timesheet_nid) REFERENCES hr_timesheet(nid),
    CONSTRAINT uk_hti_timesheet_line UNIQUE (timesheet_nid, line_no),
    INDEX idx_hti_work_date (work_date),
    INDEX idx_hti_project_sid (project_sid),
    INDEX idx_hti_site_sid (site_sid),
    INDEX idx_hti_wbs_sid (wbs_sid),
    INDEX idx_hti_cost_code_sid (cost_code_sid),
    CHECK (line_no > 0),
    CHECK (work_minutes > 0),
    CHECK (overtime_minutes >= 0),
    CHECK (labor_cost_amount >= 0),
    CHECK (billing_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='專案與工地工時明細';

CREATE TABLE IF NOT EXISTS hr_payroll_calendar (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資曆序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    calendar_code VARCHAR(100) NOT NULL COMMENT '薪資曆代碼',
    calendar_name VARCHAR(200) NOT NULL COMMENT '薪資曆名稱',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    pay_frequency VARCHAR(20) NOT NULL COMMENT 'MONTHLY月;BIWEEKLY雙週;WEEKLY週;DAILY日',
    cutoff_day INT NULL COMMENT '結算截止日',
    payment_day INT NULL COMMENT '發薪日',
    calendar_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_hpc_calendar_code UNIQUE (calendar_code),
    INDEX idx_hpc_company_sid (company_sid),
    INDEX idx_hpc_pay_frequency (pay_frequency),
    INDEX idx_hpc_status (calendar_status),
    CHECK (cutoff_day IS NULL OR cutoff_day BETWEEN 1 AND 31),
    CHECK (payment_day IS NULL OR payment_day BETWEEN 1 AND 31)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資週期與發薪日';

CREATE TABLE IF NOT EXISTS hr_payroll_period (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資期間序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payroll_calendar_sid VARCHAR(32) NOT NULL COMMENT '薪資曆序號',
    period_no VARCHAR(50) NOT NULL COMMENT '期間編號',
    period_start_date DATE NOT NULL COMMENT '期間開始日',
    period_end_date DATE NOT NULL COMMENT '期間結束日',
    cutoff_date DATE NOT NULL COMMENT '資料截止日',
    payment_date DATE NOT NULL COMMENT '發薪日',
    period_status VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN開放;CALCULATING計算中;REVIEW待審;APPROVED核准;PAID已發薪;CLOSED關閉',
    CONSTRAINT uk_hpp_calendar_period UNIQUE (payroll_calendar_sid, period_no),
    INDEX idx_hpp_date_range (period_start_date, period_end_date),
    INDEX idx_hpp_payment_date (payment_date),
    INDEX idx_hpp_status (period_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (cutoff_date >= period_start_date),
    CHECK (payment_date >= period_end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資計算期間';

CREATE TABLE IF NOT EXISTS hr_pay_component (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資項目序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    component_code VARCHAR(100) NOT NULL COMMENT '薪資項目代碼',
    component_name VARCHAR(200) NOT NULL COMMENT '薪資項目名稱',
    component_type VARCHAR(20) NOT NULL COMMENT 'EARNING應發;DEDUCTION應扣;EMPLOYER_COST雇主負擔;INFORMATION資訊',
    calculation_method VARCHAR(30) NOT NULL COMMENT 'FIXED固定;FORMULA公式;RATE比率;QUANTITY數量;MANUAL人工',
    taxable_mark TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否課稅',
    insurable_mark TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否納入投保薪資',
    overtime_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否加班項目',
    pension_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否退休金項目',
    gl_account_sid VARCHAR(32) NULL COMMENT 'GeneralLedgerDB會計科目序號',
    offset_account_sid VARCHAR(32) NULL COMMENT '對應科目序號',
    formula_expression TEXT NULL COMMENT '計算公式',
    display_order INT NOT NULL DEFAULT 0 COMMENT '顯示順序',
    component_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_hpcmp_component_code UNIQUE (component_code),
    INDEX idx_hpcmp_component_type (component_type),
    INDEX idx_hpcmp_gl_account_sid (gl_account_sid),
    INDEX idx_hpcmp_status (component_status),
    CHECK (display_order >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資應發、應扣與雇主負擔項目';

CREATE TABLE IF NOT EXISTS hr_employee_pay_component (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '員工薪資項目序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    pay_component_sid VARCHAR(32) NOT NULL COMMENT '薪資項目序號',
    effective_start_date DATE NOT NULL COMMENT '生效日',
    effective_end_date DATE NULL COMMENT '失效日',
    fixed_amount DECIMAL(20,4) NULL COMMENT '固定金額',
    rate_value DECIMAL(12,6) NULL COMMENT '比率',
    quantity_value DECIMAL(20,6) NULL COMMENT '數量',
    override_formula TEXT NULL COMMENT '員工專屬公式',
    component_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE生效;INACTIVE停用',
    CONSTRAINT uk_hepc_employee_component_start UNIQUE (employee_sid, pay_component_sid, effective_start_date),
    INDEX idx_hepc_employee_sid (employee_sid),
    INDEX idx_hepc_pay_component_sid (pay_component_sid),
    INDEX idx_hepc_effective_date (effective_start_date, effective_end_date),
    CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date),
    CHECK (fixed_amount IS NULL OR fixed_amount >= 0),
    CHECK (rate_value IS NULL OR rate_value >= 0),
    CHECK (quantity_value IS NULL OR quantity_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工固定薪資、津貼與扣款設定';

CREATE TABLE IF NOT EXISTS hr_payroll_run (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資計算批次序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payroll_run_no VARCHAR(100) NOT NULL COMMENT '薪資批次編號',
    payroll_period_sid VARCHAR(32) NOT NULL COMMENT '薪資期間序號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    run_type VARCHAR(20) NOT NULL COMMENT 'REGULAR正常;BONUS獎金;ADJUSTMENT補發扣;TERMINATION離職;OFF_CYCLE非例行',
    employee_count INT NOT NULL DEFAULT 0 COMMENT '員工人數',
    gross_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '應發總額',
    deduction_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '應扣總額',
    net_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '實發總額',
    employer_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '雇主負擔總額',
    run_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;CALCULATING計算中;REVIEW待審;APPROVED核准;PAYMENT_CREATED已建付款;PAID已發薪;POSTED已入帳;CLOSED關閉;FAILED失敗',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    payment_batch_sid VARCHAR(32) NULL COMMENT 'AccountingDB付款批次序號',
    journal_request_sid VARCHAR(32) NULL COMMENT 'AccountingDB傳票請求序號',
    CONSTRAINT uk_hpr_payroll_run_no UNIQUE (payroll_run_no),
    INDEX idx_hpr_payroll_period_sid (payroll_period_sid),
    INDEX idx_hpr_company_sid (company_sid),
    INDEX idx_hpr_run_type (run_type),
    INDEX idx_hpr_status (run_status),
    CHECK (employee_count >= 0),
    CHECK (gross_amount >= 0),
    CHECK (deduction_amount >= 0),
    CHECK (net_amount >= 0),
    CHECK (employer_cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資計算批次';

CREATE TABLE IF NOT EXISTS hr_payslip (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資單序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payslip_no VARCHAR(100) NOT NULL COMMENT '薪資單號',
    payroll_run_sid VARCHAR(32) NOT NULL COMMENT '薪資批次序號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    gross_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '應發金額',
    deduction_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '應扣金額',
    net_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '實發金額',
    employer_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '雇主負擔',
    paid_date DATE NULL COMMENT '發薪日期',
    bank_account_sid VARCHAR(32) NULL COMMENT 'PartyDB員工薪轉帳戶序號',
    payment_sid VARCHAR(32) NULL COMMENT 'AccountingDB付款序號',
    payslip_file_sid VARCHAR(32) NULL COMMENT 'FileDB薪資單檔案序號',
    payslip_status VARCHAR(20) NOT NULL DEFAULT 'CALCULATED' COMMENT 'CALCULATED已計算;APPROVED核准;PAID已發薪;REVERSED沖回;CANCELLED取消',
    CONSTRAINT uk_hps_payslip_no UNIQUE (payslip_no),
    CONSTRAINT uk_hps_run_employee UNIQUE (payroll_run_sid, employee_sid),
    INDEX idx_hps_employee_sid (employee_sid),
    INDEX idx_hps_payment_sid (payment_sid),
    INDEX idx_hps_status (payslip_status),
    CHECK (gross_amount >= 0),
    CHECK (deduction_amount >= 0),
    CHECK (net_amount >= 0),
    CHECK (employer_cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工薪資單';

CREATE TABLE IF NOT EXISTS hr_payslip_item (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資單明細序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    payslip_nid BIGINT UNSIGNED NOT NULL COMMENT '薪資單流水號',
    line_no INT NOT NULL COMMENT '明細行號',
    pay_component_sid VARCHAR(32) NOT NULL COMMENT '薪資項目序號',
    quantity DECIMAL(20,6) NULL COMMENT '數量',
    rate DECIMAL(20,6) NULL COMMENT '單價或比率',
    amount DECIMAL(20,4) NOT NULL COMMENT '金額',
    base_amount DECIMAL(20,4) NULL COMMENT '計算基礎金額',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    site_sid VARCHAR(32) NULL COMMENT '工地序號',
    wbs_sid VARCHAR(32) NULL COMMENT 'WBS序號',
    cost_center_sid VARCHAR(32) NULL COMMENT '成本中心序號',
    journal_line_sid VARCHAR(32) NULL COMMENT 'GeneralLedgerDB分錄序號',
    CONSTRAINT fk_hpsi_payslip FOREIGN KEY (payslip_nid) REFERENCES hr_payslip(nid),
    CONSTRAINT uk_hpsi_payslip_line UNIQUE (payslip_nid, line_no),
    INDEX idx_hpsi_pay_component_sid (pay_component_sid),
    INDEX idx_hpsi_project_sid (project_sid),
    INDEX idx_hpsi_site_sid (site_sid),
    INDEX idx_hpsi_wbs_sid (wbs_sid),
    INDEX idx_hpsi_cost_center_sid (cost_center_sid),
    CHECK (line_no > 0),
    CHECK (quantity IS NULL OR quantity >= 0),
    CHECK (rate IS NULL OR rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資應發、應扣與人工成本明細';

CREATE TABLE IF NOT EXISTS hr_bonus_plan (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '獎金方案序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    plan_code VARCHAR(100) NOT NULL COMMENT '獎金方案代碼',
    plan_name VARCHAR(200) NOT NULL COMMENT '獎金方案名稱',
    bonus_type VARCHAR(30) NOT NULL COMMENT 'ANNUAL年終;PERFORMANCE績效;SALES業績;PROJECT專案;ATTENDANCE全勤;REFERRAL推薦;OTHER',
    calculation_method VARCHAR(30) NOT NULL COMMENT 'FIXED固定;SALARY_MULTIPLE薪資倍數;PERCENT百分比;FORMULA公式;MANUAL人工',
    formula_expression TEXT NULL COMMENT '計算公式',
    taxable_mark TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否課稅',
    approval_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否需簽核',
    plan_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_hbp_plan_code UNIQUE (plan_code),
    INDEX idx_hbp_bonus_type (bonus_type),
    INDEX idx_hbp_status (plan_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='獎金方案';

CREATE TABLE IF NOT EXISTS hr_bonus_award (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '獎金核發序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    award_no VARCHAR(100) NOT NULL COMMENT '獎金核發編號',
    bonus_plan_sid VARCHAR(32) NOT NULL COMMENT '獎金方案序號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    performance_period_start DATE NULL COMMENT '績效期間開始',
    performance_period_end DATE NULL COMMENT '績效期間結束',
    base_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '計算基礎',
    award_amount DECIMAL(20,4) NOT NULL COMMENT '核發金額',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    payroll_run_sid VARCHAR(32) NULL COMMENT '薪資批次序號',
    award_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已送出;APPROVED核准;PAID已發放;REJECTED駁回;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_hba_award_no UNIQUE (award_no),
    INDEX idx_hba_bonus_plan_sid (bonus_plan_sid),
    INDEX idx_hba_employee_sid (employee_sid),
    INDEX idx_hba_project_sid (project_sid),
    INDEX idx_hba_payroll_run_sid (payroll_run_sid),
    INDEX idx_hba_status (award_status),
    CHECK (performance_period_end IS NULL OR performance_period_start IS NULL OR performance_period_end >= performance_period_start),
    CHECK (base_amount >= 0),
    CHECK (award_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='員工獎金核發';

CREATE TABLE IF NOT EXISTS hr_insurance_enrollment (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '保險投保序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    insurance_type VARCHAR(30) NOT NULL COMMENT 'LABOR勞保;HEALTH健保;EMPLOYMENT就保;PENSION勞退;GROUP團保;OTHER',
    provider_party_sid VARCHAR(32) NULL COMMENT '保險或主管機關Party序號',
    enrollment_no VARCHAR(100) NULL COMMENT '投保編號',
    enrollment_date DATE NOT NULL COMMENT '加保日期',
    termination_date DATE NULL COMMENT '退保日期',
    insured_salary DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '投保薪資',
    employee_rate DECIMAL(12,6) NOT NULL DEFAULT 0 COMMENT '員工負擔率',
    employer_rate DECIMAL(12,6) NOT NULL DEFAULT 0 COMMENT '雇主負擔率',
    government_rate DECIMAL(12,6) NOT NULL DEFAULT 0 COMMENT '政府負擔率',
    enrollment_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'PENDING待加保;ACTIVE投保中;SUSPENDED暫停;TERMINATED退保',
    INDEX idx_hie_employee_sid (employee_sid),
    INDEX idx_hie_insurance_type (insurance_type),
    INDEX idx_hie_provider_party_sid (provider_party_sid),
    INDEX idx_hie_status (enrollment_status),
    CHECK (termination_date IS NULL OR termination_date >= enrollment_date),
    CHECK (insured_salary >= 0),
    CHECK (employee_rate >= 0),
    CHECK (employer_rate >= 0),
    CHECK (government_rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='勞健保、就保、勞退與團保投保';

CREATE TABLE IF NOT EXISTS hr_tax_withholding (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '薪資扣繳設定序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    tax_year INT NOT NULL COMMENT '扣繳年度',
    withholding_method VARCHAR(30) NOT NULL COMMENT 'TABLE查表;FIXED_RATE固定率;FIXED_AMOUNT固定額;EXEMPT免扣',
    withholding_rate DECIMAL(12,6) NOT NULL DEFAULT 0 COMMENT '扣繳率',
    fixed_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '固定扣繳額',
    dependent_count INT NOT NULL DEFAULT 0 COMMENT '扶養人數',
    resident_status VARCHAR(20) NOT NULL DEFAULT 'RESIDENT' COMMENT 'RESIDENT居住者;NON_RESIDENT非居住者',
    effective_start_date DATE NOT NULL COMMENT '生效日',
    effective_end_date DATE NULL COMMENT '失效日',
    INDEX idx_htw_employee_sid (employee_sid),
    INDEX idx_htw_tax_year (tax_year),
    CHECK (tax_year > 0),
    CHECK (withholding_rate >= 0),
    CHECK (fixed_amount >= 0),
    CHECK (dependent_count >= 0),
    CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='薪資所得稅扣繳設定';

CREATE TABLE IF NOT EXISTS hr_labor_cost_allocation (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '人工成本分攤序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    payroll_run_sid VARCHAR(32) NOT NULL COMMENT '薪資批次序號',
    employee_sid VARCHAR(32) NOT NULL COMMENT '員工序號',
    project_sid VARCHAR(32) NULL COMMENT '專案序號',
    site_sid VARCHAR(32) NULL COMMENT '工地序號',
    wbs_sid VARCHAR(32) NULL COMMENT 'WBS序號',
    cost_code_sid VARCHAR(32) NULL COMMENT 'ProjectCostDB成本代碼序號',
    cost_center_sid VARCHAR(32) NULL COMMENT '成本中心序號',
    allocation_basis VARCHAR(30) NOT NULL COMMENT 'TIMESHEET工時;FIXED_PERCENT固定比例;HEADCOUNT人數;MANUAL人工',
    allocation_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '分攤比例',
    labor_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '薪資人工成本',
    employer_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '雇主負擔成本',
    total_cost_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '總人工成本',
    project_actual_cost_sid VARCHAR(32) NULL COMMENT 'ProjectCostDB實際成本序號',
    journal_line_sid VARCHAR(32) NULL COMMENT 'GeneralLedgerDB分錄序號',
    allocation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;POSTED已入帳;FAILED失敗;REVERSED沖回',
    INDEX idx_hlca_payroll_run_sid (payroll_run_sid),
    INDEX idx_hlca_employee_sid (employee_sid),
    INDEX idx_hlca_project_sid (project_sid),
    INDEX idx_hlca_site_sid (site_sid),
    INDEX idx_hlca_wbs_sid (wbs_sid),
    INDEX idx_hlca_cost_code_sid (cost_code_sid),
    INDEX idx_hlca_status (allocation_status),
    CHECK (allocation_percent BETWEEN 0 AND 100),
    CHECK (labor_cost_amount >= 0),
    CHECK (employer_cost_amount >= 0),
    CHECK (total_cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='專案、工地與WBS人工成本分攤';

CREATE TABLE IF NOT EXISTS hr_status_history (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '人資薪資狀態歷程序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type VARCHAR(30) NOT NULL COMMENT 'EMPLOYEE;CONTRACT;SCHEDULE;ATTENDANCE;LEAVE;OVERTIME;TIMESHEET;PAYROLL_RUN;PAYSLIP;BONUS;INSURANCE',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    old_status VARCHAR(30) NULL COMMENT '原狀態',
    new_status VARCHAR(30) NOT NULL COMMENT '新狀態',
    event_code VARCHAR(100) NULL COMMENT '觸發事件代碼',
    operator_user_sid VARCHAR(32) NULL COMMENT '操作人員序號',
    reason TEXT NULL COMMENT '原因說明',
    correlation_id VARCHAR(100) NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_hsh_entity (entity_type, entity_sid),
    INDEX idx_hsh_new_status (new_status),
    INDEX idx_hsh_event_code (event_code),
    INDEX idx_hsh_operator_user_sid (operator_user_sid),
    INDEX idx_hsh_correlation_id (correlation_id),
    INDEX idx_hsh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人資與薪資狀態歷程';

CREATE TABLE IF NOT EXISTS hr_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '人資薪資事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type VARCHAR(30) NOT NULL COMMENT 'EMPLOYEE;ATTENDANCE;LEAVE;OVERTIME;TIMESHEET;PAYROLL_RUN;PAYSLIP;BONUS;INSURANCE;LABOR_COST',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    event_code VARCHAR(120) NOT NULL COMMENT '事件代碼',
    event_version INT NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data JSON NULL COMMENT '事件內容',
    source_event_id VARCHAR(100) NULL COMMENT '來源事件ID',
    correlation_id VARCHAR(100) NULL COMMENT '關聯識別碼',
    causation_id VARCHAR(100) NULL COMMENT '因果事件ID',
    outbox_event_sid VARCHAR(32) NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date DATETIME NULL COMMENT '處理時間',
    error_message TEXT NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_hev_source_event_id (source_event_id),
    INDEX idx_hev_entity (entity_type, entity_sid),
    INDEX idx_hev_event_code (event_code),
    INDEX idx_hev_correlation_id (correlation_id),
    INDEX idx_hev_outbox_event_sid (outbox_event_sid),
    INDEX idx_hev_status (process_status),
    INDEX idx_hev_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人資與薪資領域事件';
SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
