namespace B2bOrder.Resources.Customer
{
    /// <summary>
    /// CustomerSalesCRMDB V2 Shared Core Schema
    /// 支援潛在客戶、客戶、建案銷控、商機、互動、賞屋、報價、保留、銷售合約、收款、客變、交屋、客訴與滿意度。
    /// nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼。
    /// avalible：Y可用；W停用；D刪除。
    /// 適用 MySQL 8.x / InnoDB / utf8mb4。
    /// </summary>
    internal static class CustomerSalesCRMB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS crm_lead (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '潛在客戶序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    lead_no VARCHAR(100) NOT NULL COMMENT '潛在客戶編號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    campaign_sid VARCHAR(32) NULL COMMENT 'MarketingDB行銷活動序號',
    source_type VARCHAR(30) NOT NULL COMMENT 'WEBSITE官網;PORTAL平台;PHONE電話;WALK_IN來訪;REFERRAL介紹;SOCIAL社群;AD廣告;EXHIBITION展覽;AGENT代銷;OTHER',
    source_reference_sid VARCHAR(32) NULL COMMENT '來源資料序號',
    lead_type VARCHAR(20) NOT NULL COMMENT 'INDIVIDUAL個人;COMPANY公司;INVESTOR投資人;AGENT仲介',
    lead_name VARCHAR(300) NOT NULL COMMENT '潛在客戶名稱',
    contact_phone VARCHAR(100) NULL COMMENT '聯絡電話',
    contact_email VARCHAR(300) NULL COMMENT '聯絡信箱',
    contact_line_id VARCHAR(200) NULL COMMENT 'LINE識別資料',
    interested_project_sid VARCHAR(32) NULL COMMENT '有興趣建案序號',
    interested_product_type VARCHAR(30) NULL COMMENT 'HOUSE住宅;OFFICE辦公;SHOP店面;PARKING車位;LAND土地;OTHER',
    budget_min DECIMAL(20,4) NULL COMMENT '最低預算',
    budget_max DECIMAL(20,4) NULL COMMENT '最高預算',
    preferred_area_min DECIMAL(20,6) NULL COMMENT '偏好最小面積',
    preferred_area_max DECIMAL(20,6) NULL COMMENT '偏好最大面積',
    preferred_location VARCHAR(500) NULL COMMENT '偏好區域',
    purchase_timeline VARCHAR(30) NULL COMMENT 'IMMEDIATE立即;THREE_MONTHS三個月;SIX_MONTHS六個月;ONE_YEAR一年;UNDECIDED未定',
    assigned_sales_party_sid VARCHAR(32) NULL COMMENT '負責業務Party序號',
    qualification_score DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '潛客評分',
    lead_status VARCHAR(30) NOT NULL DEFAULT 'NEW' COMMENT 'NEW新名單;CONTACTED已聯絡;QUALIFIED有效;NURTURING培育中;CONVERTED已轉換;LOST流失;INVALID無效',
    converted_customer_sid VARCHAR(32) NULL COMMENT '轉換後客戶序號',
    converted_date DATETIME NULL COMMENT '轉換時間',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_cl_lead_no UNIQUE (lead_no),
    INDEX idx_cl_company_sid (company_sid),
    INDEX idx_cl_campaign_sid (campaign_sid),
    INDEX idx_cl_source_type (source_type),
    INDEX idx_cl_interested_project_sid (interested_project_sid),
    INDEX idx_cl_assigned_sales_party_sid (assigned_sales_party_sid),
    INDEX idx_cl_status (lead_status),
    CHECK (qualification_score BETWEEN 0 AND 100),
    CHECK (budget_min IS NULL OR budget_min >= 0),
    CHECK (budget_max IS NULL OR budget_max >= 0),
    CHECK (budget_max IS NULL OR budget_min IS NULL OR budget_max >= budget_min),
    CHECK (preferred_area_min IS NULL OR preferred_area_min >= 0),
    CHECK (preferred_area_max IS NULL OR preferred_area_max >= 0),
    CHECK (preferred_area_max IS NULL OR preferred_area_min IS NULL OR preferred_area_max >= preferred_area_min)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案與商品潛在客戶';

CREATE TABLE IF NOT EXISTS crm_customer (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客戶序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    customer_no VARCHAR(100) NOT NULL COMMENT '客戶編號',
    party_sid VARCHAR(32) NOT NULL COMMENT 'PartyDB客戶序號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    customer_type VARCHAR(20) NOT NULL COMMENT 'INDIVIDUAL個人;COMPANY公司;INVESTOR投資人;AGENT仲介',
    customer_level VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL一般;VIP;VVIP;BLACKLIST黑名單',
    primary_contact_sid VARCHAR(32) NULL COMMENT '主要聯絡人序號',
    sales_owner_party_sid VARCHAR(32) NULL COMMENT '負責業務Party序號',
    first_purchase_date DATE NULL COMMENT '首次購買日',
    total_purchase_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '累計購買金額',
    total_contract_count INT NOT NULL DEFAULT 0 COMMENT '累計合約數',
    preferred_contact_channel VARCHAR(20) NULL COMMENT 'PHONE電話;EMAIL郵件;LINE;SMS簡訊;APP;OTHER',
    consent_marketing TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否同意行銷',
    consent_date DATETIME NULL COMMENT '同意時間',
    customer_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;INACTIVE停用;BLACKLIST黑名單;CLOSED關閉',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_cc_customer_no UNIQUE (customer_no),
    CONSTRAINT uk_cc_party_company UNIQUE (party_sid, company_sid),
    INDEX idx_cc_party_sid (party_sid),
    INDEX idx_cc_company_sid (company_sid),
    INDEX idx_cc_sales_owner_party_sid (sales_owner_party_sid),
    INDEX idx_cc_customer_level (customer_level),
    INDEX idx_cc_status (customer_status),
    CHECK (total_purchase_amount >= 0),
    CHECK (total_contract_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶主檔與關係管理';

CREATE TABLE IF NOT EXISTS crm_sales_project (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售建案序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    sales_project_no VARCHAR(100) NOT NULL COMMENT '銷售建案編號',
    sales_project_name VARCHAR(300) NOT NULL COMMENT '銷售建案名稱',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    project_sid VARCHAR(32) NOT NULL COMMENT 'ProjectCostDB工程專案序號',
    property_sid VARCHAR(32) NULL COMMENT 'PropertyFacilityDB物業序號',
    developer_party_sid VARCHAR(32) NULL COMMENT '建設公司Party序號',
    sales_agent_party_sid VARCHAR(32) NULL COMMENT '代銷Party序號',
    address_sid VARCHAR(32) NULL COMMENT 'PartyDB地址序號',
    launch_date DATE NULL COMMENT '開案日',
    sales_start_date DATE NULL COMMENT '銷售開始日',
    expected_completion_date DATE NULL COMMENT '預計完工日',
    expected_handover_date DATE NULL COMMENT '預計交屋日',
    total_unit_count INT NOT NULL DEFAULT 0 COMMENT '總銷售單元數',
    available_unit_count INT NOT NULL DEFAULT 0 COMMENT '可售單元數',
    reserved_unit_count INT NOT NULL DEFAULT 0 COMMENT '保留單元數',
    sold_unit_count INT NOT NULL DEFAULT 0 COMMENT '已售單元數',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    project_status VARCHAR(30) NOT NULL DEFAULT 'PLANNING' COMMENT 'PLANNING規劃;PRE_SALE預售;ON_SALE銷售中;SOLD_OUT完銷;HANDOVER交屋中;CLOSED結案;SUSPENDED暫停',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_csp_sales_project_no UNIQUE (sales_project_no),
    INDEX idx_csp_company_sid (company_sid),
    INDEX idx_csp_project_sid (project_sid),
    INDEX idx_csp_property_sid (property_sid),
    INDEX idx_csp_sales_agent_party_sid (sales_agent_party_sid),
    INDEX idx_csp_status (project_status),
    CHECK (total_unit_count >= 0),
    CHECK (available_unit_count >= 0),
    CHECK (reserved_unit_count >= 0),
    CHECK (sold_unit_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案銷售主檔';

CREATE TABLE IF NOT EXISTS crm_sales_unit (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售單元序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    unit_no VARCHAR(100) NOT NULL COMMENT '戶別或單元編號',
    unit_name VARCHAR(300) NULL COMMENT '戶別名稱',
    product_type VARCHAR(30) NOT NULL COMMENT 'HOUSE住宅;OFFICE辦公;SHOP店面;PARKING車位;LAND土地;STORAGE儲藏室;OTHER',
    building_sid VARCHAR(32) NULL COMMENT 'PropertyFacilityDB棟別序號',
    floor_sid VARCHAR(32) NULL COMMENT '樓層序號',
    space_sid VARCHAR(32) NULL COMMENT '空間序號',
    parent_unit_sid VARCHAR(32) NULL COMMENT '主單元序號',
    orientation VARCHAR(50) NULL COMMENT '座向',
    layout_code VARCHAR(100) NULL COMMENT '格局代碼',
    room_count INT NULL COMMENT '房數',
    hall_count INT NULL COMMENT '廳數',
    bathroom_count INT NULL COMMENT '衛浴數',
    balcony_count INT NULL COMMENT '陽台數',
    registered_area DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '登記面積',
    main_building_area DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '主建物面積',
    accessory_area DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '附屬建物面積',
    common_area DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '共有部分面積',
    land_area DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '土地持分面積',
    unit_sid_area VARCHAR(32) NULL COMMENT '面積單位序號',
    list_price DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '表價',
    minimum_price DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '最低授權價',
    actual_sale_price DECIMAL(20,4) NULL COMMENT '實際成交價',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    release_date DATE NULL COMMENT '釋出銷售日',
    reservation_expiry_date DATETIME NULL COMMENT '保留到期時間',
    unit_status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE' COMMENT 'PLANNED規劃;AVAILABLE可售;RESERVED保留;NEGOTIATING議價中;SOLD已售;HOLD停售;CANCELLED取消;HANDED_OVER已交屋',
    reserved_customer_sid VARCHAR(32) NULL COMMENT '保留客戶序號',
    sales_contract_sid VARCHAR(32) NULL COMMENT '銷售合約序號',
    CONSTRAINT uk_csu_project_unit_no UNIQUE (sales_project_sid, unit_no),
    INDEX idx_csu_sales_project_sid (sales_project_sid),
    INDEX idx_csu_product_type (product_type),
    INDEX idx_csu_building_sid (building_sid),
    INDEX idx_csu_floor_sid (floor_sid),
    INDEX idx_csu_space_sid (space_sid),
    INDEX idx_csu_parent_unit_sid (parent_unit_sid),
    INDEX idx_csu_reserved_customer_sid (reserved_customer_sid),
    INDEX idx_csu_status (unit_status),
    CHECK (room_count IS NULL OR room_count >= 0),
    CHECK (hall_count IS NULL OR hall_count >= 0),
    CHECK (bathroom_count IS NULL OR bathroom_count >= 0),
    CHECK (balcony_count IS NULL OR balcony_count >= 0),
    CHECK (registered_area >= 0),
    CHECK (main_building_area >= 0),
    CHECK (accessory_area >= 0),
    CHECK (common_area >= 0),
    CHECK (land_area >= 0),
    CHECK (list_price >= 0),
    CHECK (minimum_price >= 0),
    CHECK (actual_sale_price IS NULL OR actual_sale_price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房屋、店面、辦公室與車位銷控';

CREATE TABLE IF NOT EXISTS crm_opportunity (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售商機序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    opportunity_no VARCHAR(100) NOT NULL COMMENT '商機編號',
    customer_sid VARCHAR(32) NULL COMMENT '客戶序號',
    lead_sid VARCHAR(32) NULL COMMENT '潛在客戶序號',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    sales_unit_sid VARCHAR(32) NULL COMMENT '目標銷售單元序號',
    sales_owner_party_sid VARCHAR(32) NULL COMMENT '負責業務Party序號',
    opportunity_name VARCHAR(500) NOT NULL COMMENT '商機名稱',
    stage_code VARCHAR(30) NOT NULL COMMENT 'NEW新商機;CONTACTED已接觸;VISITED已賞屋;QUOTED已報價;NEGOTIATING議價;RESERVED已保留;CONTRACTING簽約中;WON成交;LOST失單',
    expected_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '預估成交金額',
    probability_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '成交機率',
    expected_close_date DATE NULL COMMENT '預計成交日',
    actual_close_date DATE NULL COMMENT '實際成交或失單日',
    competitor_information TEXT NULL COMMENT '競品資訊',
    loss_reason VARCHAR(1000) NULL COMMENT '失單原因',
    opportunity_status VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN進行中;WON成交;LOST失單;CANCELLED取消',
    version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    CONSTRAINT uk_co_opportunity_no UNIQUE (opportunity_no),
    INDEX idx_co_customer_sid (customer_sid),
    INDEX idx_co_lead_sid (lead_sid),
    INDEX idx_co_sales_project_sid (sales_project_sid),
    INDEX idx_co_sales_unit_sid (sales_unit_sid),
    INDEX idx_co_sales_owner_party_sid (sales_owner_party_sid),
    INDEX idx_co_stage_code (stage_code),
    INDEX idx_co_expected_close_date (expected_close_date),
    INDEX idx_co_status (opportunity_status),
    CHECK (expected_amount >= 0),
    CHECK (probability_percent BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案銷售商機與銷售漏斗';

CREATE TABLE IF NOT EXISTS crm_interaction (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客戶互動序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    customer_sid VARCHAR(32) NULL COMMENT '客戶序號',
    lead_sid VARCHAR(32) NULL COMMENT '潛在客戶序號',
    opportunity_sid VARCHAR(32) NULL COMMENT '商機序號',
    interaction_type VARCHAR(30) NOT NULL COMMENT 'PHONE電話;EMAIL郵件;LINE;SMS簡訊;MEETING會議;SITE_VISIT賞屋;APP_MESSAGE App訊息;OTHER',
    direction VARCHAR(20) NOT NULL COMMENT 'INBOUND客戶進線;OUTBOUND主動聯繫',
    interaction_date DATETIME NOT NULL COMMENT '互動時間',
    sales_party_sid VARCHAR(32) NULL COMMENT '業務Party序號',
    subject VARCHAR(500) NULL COMMENT '主旨',
    content_summary LONGTEXT NULL COMMENT '互動摘要',
    sentiment VARCHAR(20) NULL COMMENT 'POSITIVE正面;NEUTRAL中立;NEGATIVE負面',
    next_action VARCHAR(1000) NULL COMMENT '下一步行動',
    next_action_date DATETIME NULL COMMENT '下一次聯絡時間',
    file_sid VARCHAR(32) NULL COMMENT 'FileDB錄音或附件序號',
    interaction_status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED' COMMENT 'PLANNED規劃;COMPLETED完成;CANCELLED取消',
    INDEX idx_ci_customer_sid (customer_sid),
    INDEX idx_ci_lead_sid (lead_sid),
    INDEX idx_ci_opportunity_sid (opportunity_sid),
    INDEX idx_ci_interaction_type (interaction_type),
    INDEX idx_ci_interaction_date (interaction_date),
    INDEX idx_ci_sales_party_sid (sales_party_sid),
    INDEX idx_ci_next_action_date (next_action_date),
    INDEX idx_ci_status (interaction_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='電話、訊息、賞屋與客戶互動歷程';

CREATE TABLE IF NOT EXISTS crm_visit_appointment (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '賞屋預約序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    appointment_no VARCHAR(100) NOT NULL COMMENT '預約編號',
    lead_sid VARCHAR(32) NULL COMMENT '潛在客戶序號',
    customer_sid VARCHAR(32) NULL COMMENT '客戶序號',
    opportunity_sid VARCHAR(32) NULL COMMENT '商機序號',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    sales_unit_sid VARCHAR(32) NULL COMMENT '指定銷售單元序號',
    appointment_type VARCHAR(20) NOT NULL COMMENT 'SHOWROOM接待中心;SITE現場;ONLINE線上;MODEL_HOME樣品屋',
    planned_start_date DATETIME NOT NULL COMMENT '預約開始時間',
    planned_end_date DATETIME NULL COMMENT '預約結束時間',
    sales_party_sid VARCHAR(32) NULL COMMENT '接待業務Party序號',
    attendee_count INT NOT NULL DEFAULT 1 COMMENT '來訪人數',
    actual_arrival_date DATETIME NULL COMMENT '實際到場時間',
    actual_leave_date DATETIME NULL COMMENT '實際離場時間',
    customer_feedback TEXT NULL COMMENT '客戶回饋',
    appointment_status VARCHAR(20) NOT NULL DEFAULT 'BOOKED' COMMENT 'BOOKED已預約;CONFIRMED已確認;ARRIVED已到場;COMPLETED完成;NO_SHOW未到;CANCELLED取消',
    CONSTRAINT uk_cva_appointment_no UNIQUE (appointment_no),
    INDEX idx_cva_lead_sid (lead_sid),
    INDEX idx_cva_customer_sid (customer_sid),
    INDEX idx_cva_opportunity_sid (opportunity_sid),
    INDEX idx_cva_sales_project_sid (sales_project_sid),
    INDEX idx_cva_sales_unit_sid (sales_unit_sid),
    INDEX idx_cva_planned_start_date (planned_start_date),
    INDEX idx_cva_sales_party_sid (sales_party_sid),
    INDEX idx_cva_status (appointment_status),
    CHECK (planned_end_date IS NULL OR planned_end_date >= planned_start_date),
    CHECK (actual_leave_date IS NULL OR actual_arrival_date IS NULL OR actual_leave_date >= actual_arrival_date),
    CHECK (attendee_count > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='接待中心、樣品屋與現場賞屋預約';

CREATE TABLE IF NOT EXISTS crm_quotation (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售報價序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    quotation_no VARCHAR(100) NOT NULL COMMENT '報價單號',
    opportunity_sid VARCHAR(32) NOT NULL COMMENT '商機序號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '銷售單元序號',
    quotation_date DATE NOT NULL COMMENT '報價日期',
    expiry_date DATE NULL COMMENT '報價有效日',
    list_price DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '表價',
    discount_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '折讓金額',
    promotion_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '促銷優惠',
    other_charge_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '其他費用',
    tax_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '稅額',
    total_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '報價總額',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    payment_plan_sid VARCHAR(32) NULL COMMENT '付款方案序號',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需價格核准',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    quotation_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;APPROVED核准;SENT已送客戶;ACCEPTED接受;REJECTED拒絕;EXPIRED過期;CANCELLED取消',
    CONSTRAINT uk_cq_quotation_no UNIQUE (quotation_no),
    INDEX idx_cq_opportunity_sid (opportunity_sid),
    INDEX idx_cq_customer_sid (customer_sid),
    INDEX idx_cq_sales_project_sid (sales_project_sid),
    INDEX idx_cq_sales_unit_sid (sales_unit_sid),
    INDEX idx_cq_quotation_date (quotation_date),
    INDEX idx_cq_expiry_date (expiry_date),
    INDEX idx_cq_status (quotation_status),
    CHECK (expiry_date IS NULL OR expiry_date >= quotation_date),
    CHECK (list_price >= 0),
    CHECK (discount_amount >= 0),
    CHECK (promotion_amount >= 0),
    CHECK (other_charge_amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案單元報價與價格核准';

CREATE TABLE IF NOT EXISTS crm_reservation (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售保留序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    reservation_no VARCHAR(100) NOT NULL COMMENT '保留編號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    opportunity_sid VARCHAR(32) NULL COMMENT '商機序號',
    quotation_sid VARCHAR(32) NULL COMMENT '報價序號',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '銷售單元序號',
    reservation_date DATETIME NOT NULL COMMENT '保留時間',
    expiry_date DATETIME NOT NULL COMMENT '保留到期時間',
    reservation_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '保留金',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    payment_sid VARCHAR(32) NULL COMMENT 'AccountingDB收款序號',
    sales_party_sid VARCHAR(32) NULL COMMENT '承辦業務Party序號',
    reservation_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE保留中;PAID已收保留金;CONVERTED已轉合約;EXPIRED逾期;CANCELLED取消;REFUNDED已退款',
    CONSTRAINT uk_cr_reservation_no UNIQUE (reservation_no),
    INDEX idx_cr_customer_sid (customer_sid),
    INDEX idx_cr_opportunity_sid (opportunity_sid),
    INDEX idx_cr_quotation_sid (quotation_sid),
    INDEX idx_cr_sales_project_sid (sales_project_sid),
    INDEX idx_cr_sales_unit_sid (sales_unit_sid),
    INDEX idx_cr_expiry_date (expiry_date),
    INDEX idx_cr_status (reservation_status),
    CHECK (expiry_date > reservation_date),
    CHECK (reservation_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房屋與車位銷售保留';

CREATE TABLE IF NOT EXISTS crm_payment_plan (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '付款方案序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    payment_plan_code VARCHAR(100) NOT NULL COMMENT '付款方案代碼',
    payment_plan_name VARCHAR(300) NOT NULL COMMENT '付款方案名稱',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    plan_type VARCHAR(30) NOT NULL COMMENT 'STANDARD標準;CONSTRUCTION_PROGRESS工程期;INSTALLMENT分期;MORTGAGE房貸;CUSTOM自訂',
    description TEXT NULL COMMENT '方案說明',
    deposit_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '訂金比例',
    contract_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '簽約金比例',
    construction_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '工程款比例',
    handover_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '交屋款比例',
    mortgage_percent DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '貸款比例',
    installment_rule JSON NULL COMMENT '分期規則',
    plan_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_cpp_payment_plan_code UNIQUE (payment_plan_code),
    INDEX idx_cpp_sales_project_sid (sales_project_sid),
    INDEX idx_cpp_plan_type (plan_type),
    INDEX idx_cpp_status (plan_status),
    CHECK (deposit_percent BETWEEN 0 AND 100),
    CHECK (contract_percent BETWEEN 0 AND 100),
    CHECK (construction_percent BETWEEN 0 AND 100),
    CHECK (handover_percent BETWEEN 0 AND 100),
    CHECK (mortgage_percent BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案訂金、簽約款、工程款與交屋款方案';

CREATE TABLE IF NOT EXISTS crm_sales_contract (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售合約序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    sales_contract_no VARCHAR(100) NOT NULL COMMENT '銷售合約編號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_project_sid VARCHAR(32) NOT NULL COMMENT '銷售建案序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '主銷售單元序號',
    quotation_sid VARCHAR(32) NULL COMMENT '報價序號',
    reservation_sid VARCHAR(32) NULL COMMENT '保留序號',
    contract_sid VARCHAR(32) NULL COMMENT 'ContractDB正式合約序號',
    signing_date DATE NOT NULL COMMENT '簽約日期',
    contract_amount DECIMAL(20,4) NOT NULL COMMENT '合約金額',
    tax_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '稅額',
    total_amount DECIMAL(20,4) NOT NULL COMMENT '合約總額',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    payment_plan_sid VARCHAR(32) NULL COMMENT '付款方案序號',
    expected_handover_date DATE NULL COMMENT '預計交屋日',
    actual_handover_date DATE NULL COMMENT '實際交屋日',
    mortgage_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否申請房貸',
    mortgage_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '房貸金額',
    contract_file_sid VARCHAR(32) NULL COMMENT 'FileDB合約文件序號',
    contract_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;SIGNED已簽約;ACTIVE生效;CANCELLED解除;DEFAULTED違約;HANDED_OVER已交屋;CLOSED結案',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '樂觀鎖版本',
    CONSTRAINT uk_csc_contract_no UNIQUE (sales_contract_no),
    CONSTRAINT uk_csc_sales_unit UNIQUE (sales_unit_sid),
    INDEX idx_csc_customer_sid (customer_sid),
    INDEX idx_csc_sales_project_sid (sales_project_sid),
    INDEX idx_csc_sales_unit_sid (sales_unit_sid),
    INDEX idx_csc_contract_sid (contract_sid),
    INDEX idx_csc_signing_date (signing_date),
    INDEX idx_csc_expected_handover_date (expected_handover_date),
    INDEX idx_csc_status (contract_status),
    CHECK (contract_amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (total_amount >= 0),
    CHECK (mortgage_amount >= 0),
    CHECK (actual_handover_date IS NULL OR actual_handover_date >= signing_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房屋、店面、辦公室與車位銷售合約';

CREATE TABLE IF NOT EXISTS crm_sales_contract_item (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售合約明細序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    sales_contract_nid BIGINT UNSIGNED NOT NULL COMMENT '銷售合約流水號',
    line_no INT NOT NULL COMMENT '明細行號',
    sales_unit_sid VARCHAR(32) NULL COMMENT '銷售單元序號',
    item_type VARCHAR(30) NOT NULL COMMENT 'HOUSE房屋;PARKING車位;STORAGE儲藏室;DECORATION裝修;UPGRADE升級;FEE費用;DISCOUNT折讓;OTHER',
    item_name VARCHAR(500) NOT NULL COMMENT '合約項目名稱',
    quantity DECIMAL(20,6) NOT NULL DEFAULT 1 COMMENT '數量',
    unit_price DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '單價',
    amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '金額',
    tax_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '稅額',
    total_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '總額',
    CONSTRAINT fk_csci_contract FOREIGN KEY (sales_contract_nid) REFERENCES crm_sales_contract(nid),
    CONSTRAINT uk_csci_contract_line UNIQUE (sales_contract_nid, line_no),
    INDEX idx_csci_sales_unit_sid (sales_unit_sid),
    INDEX idx_csci_item_type (item_type),
    CHECK (line_no > 0),
    CHECK (quantity > 0),
    CHECK (unit_price >= 0),
    CHECK (amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (total_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房屋、車位、裝修與優惠合約明細';

CREATE TABLE IF NOT EXISTS crm_receivable_schedule (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '收款期程序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    schedule_no VARCHAR(100) NOT NULL COMMENT '收款期程編號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    installment_no INT NOT NULL COMMENT '期數',
    installment_type VARCHAR(30) NOT NULL COMMENT 'RESERVATION保留金;DEPOSIT訂金;CONTRACT簽約金;CONSTRUCTION工程款;MORTGAGE房貸;HANDOVER交屋款;OTHER',
    due_date DATE NOT NULL COMMENT '應收日期',
    amount DECIMAL(20,4) NOT NULL COMMENT '應收金額',
    tax_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '稅額',
    total_amount DECIMAL(20,4) NOT NULL COMMENT '應收總額',
    paid_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '已收金額',
    outstanding_amount DECIMAL(20,4) NOT NULL COMMENT '未收金額',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    milestone_type VARCHAR(30) NULL COMMENT 'DATE日期;CONSTRUCTION_PROGRESS工程進度;DOCUMENT文件;HANDOVER交屋;CUSTOM自訂',
    milestone_sid VARCHAR(32) NULL COMMENT '關聯里程碑序號',
    receivable_sid VARCHAR(32) NULL COMMENT 'AccountingDB應收序號',
    invoice_sid VARCHAR(32) NULL COMMENT 'InvoiceTaxDB發票序號',
    schedule_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING未到期;ISSUED已開帳;PARTIAL_PAID部分收款;PAID已收清;OVERDUE逾期;WAIVED豁免;CANCELLED取消',
    CONSTRAINT uk_crs_schedule_no UNIQUE (schedule_no),
    CONSTRAINT uk_crs_contract_installment UNIQUE (sales_contract_sid, installment_no),
    INDEX idx_crs_sales_contract_sid (sales_contract_sid),
    INDEX idx_crs_due_date (due_date),
    INDEX idx_crs_installment_type (installment_type),
    INDEX idx_crs_receivable_sid (receivable_sid),
    INDEX idx_crs_status (schedule_status),
    CHECK (installment_no > 0),
    CHECK (amount >= 0),
    CHECK (tax_amount >= 0),
    CHECK (total_amount >= 0),
    CHECK (paid_amount >= 0),
    CHECK (outstanding_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='房屋銷售訂金、工程款、貸款與交屋款期程';

CREATE TABLE IF NOT EXISTS crm_payment_receipt (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客戶收款紀錄序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    receipt_no VARCHAR(100) NOT NULL COMMENT '收款編號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    receivable_schedule_sid VARCHAR(32) NULL COMMENT '收款期程序號',
    payment_date DATETIME NOT NULL COMMENT '收款時間',
    payment_method VARCHAR(30) NOT NULL COMMENT 'CASH現金;TRANSFER轉帳;CHECK支票;CARD刷卡;LOAN房貸撥款;ESCROW履保;OTHER',
    amount DECIMAL(20,4) NOT NULL COMMENT '收款金額',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    accounting_receipt_sid VARCHAR(32) NULL COMMENT 'AccountingDB收款序號',
    bank_transaction_sid VARCHAR(32) NULL COMMENT 'BankDB銀行交易序號',
    payer_name VARCHAR(300) NULL COMMENT '付款人名稱',
    reference_no VARCHAR(200) NULL COMMENT '付款參考編號',
    receipt_file_sid VARCHAR(32) NULL COMMENT 'FileDB收據序號',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' COMMENT 'PENDING待確認;RECEIVED已收款;VERIFIED已核對;REVERSED已沖回;REFUNDED已退款',
    CONSTRAINT uk_cpr_receipt_no UNIQUE (receipt_no),
    INDEX idx_cpr_customer_sid (customer_sid),
    INDEX idx_cpr_sales_contract_sid (sales_contract_sid),
    INDEX idx_cpr_schedule_sid (receivable_schedule_sid),
    INDEX idx_cpr_payment_date (payment_date),
    INDEX idx_cpr_payment_method (payment_method),
    INDEX idx_cpr_status (payment_status),
    CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶房款、貸款撥款與收據';

CREATE TABLE IF NOT EXISTS crm_contract_change (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售合約變更序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    change_no VARCHAR(100) NOT NULL COMMENT '合約變更編號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    change_type VARCHAR(30) NOT NULL COMMENT 'PRICE價格;PAYMENT付款;CUSTOMER買方;UNIT戶別;PARKING車位;DESIGN客變;CANCEL解除;OTHER',
    request_date DATE NOT NULL COMMENT '申請日期',
    requested_by_party_sid VARCHAR(32) NULL COMMENT '申請Party序號',
    change_description LONGTEXT NOT NULL COMMENT '變更內容',
    amount_change DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '金額增減，可正可負',
    schedule_change_days INT NOT NULL DEFAULT 0 COMMENT '時程增減天數，可正可負',
    customer_approval_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否需客戶同意',
    document_file_sid VARCHAR(32) NULL COMMENT 'FileDB變更文件序號',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    change_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已申請;REVIEW待審;APPROVED核准;SIGNED已簽署;APPLIED已生效;REJECTED拒絕;CANCELLED取消',
    CONSTRAINT uk_ccc_change_no UNIQUE (change_no),
    INDEX idx_ccc_sales_contract_sid (sales_contract_sid),
    INDEX idx_ccc_change_type (change_type),
    INDEX idx_ccc_request_date (request_date),
    INDEX idx_ccc_status (change_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='售價、付款、戶別與客戶設計變更';

CREATE TABLE IF NOT EXISTS crm_customer_change_request (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客戶客變申請序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    request_no VARCHAR(100) NOT NULL COMMENT '客變申請編號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '銷售單元序號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    request_date DATE NOT NULL COMMENT '申請日期',
    cutoff_date DATE NULL COMMENT '客變截止日',
    change_category VARCHAR(30) NOT NULL COMMENT 'LAYOUT格局;MATERIAL材料;ELECTRICAL電氣;PLUMBING給排水;HVAC空調;FINISH裝修;OTHER',
    change_description LONGTEXT NOT NULL COMMENT '客變內容',
    drawing_document_sid VARCHAR(32) NULL COMMENT 'DocumentDrawingDB客變圖說序號',
    estimated_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '預估增減帳',
    approved_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '核准增減帳',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    project_change_sid VARCHAR(32) NULL COMMENT 'ProjectCostDB工程變更序號',
    contract_change_sid VARCHAR(32) NULL COMMENT '銷售合約變更序號',
    request_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;SUBMITTED已申請;FEASIBILITY_CHECK可行性評估;QUOTED已報價;APPROVED核准;IN_PROGRESS施工中;COMPLETED完成;REJECTED拒絕;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_ccr_request_no UNIQUE (request_no),
    INDEX idx_ccr_sales_contract_sid (sales_contract_sid),
    INDEX idx_ccr_sales_unit_sid (sales_unit_sid),
    INDEX idx_ccr_customer_sid (customer_sid),
    INDEX idx_ccr_request_date (request_date),
    INDEX idx_ccr_category (change_category),
    INDEX idx_ccr_status (request_status),
    CHECK (cutoff_date IS NULL OR cutoff_date >= request_date),
    CHECK (estimated_amount >= 0),
    CHECK (approved_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶格局、材料與設備客變申請';

CREATE TABLE IF NOT EXISTS crm_handover_appointment (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '交屋預約序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    handover_appointment_no VARCHAR(100) NOT NULL COMMENT '交屋預約編號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '銷售單元序號',
    planned_handover_date DATETIME NOT NULL COMMENT '預計交屋時間',
    customer_representative_party_sid VARCHAR(32) NULL COMMENT '客戶代表Party序號',
    company_representative_party_sid VARCHAR(32) NULL COMMENT '公司代表Party序號',
    final_payment_confirmed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '尾款是否確認',
    ownership_document_ready TINYINT(1) NOT NULL DEFAULT 0 COMMENT '權狀文件是否備妥',
    key_ready TINYINT(1) NOT NULL DEFAULT 0 COMMENT '鑰匙是否備妥',
    utility_transfer_ready TINYINT(1) NOT NULL DEFAULT 0 COMMENT '水電移轉是否備妥',
    document_package_sid VARCHAR(32) NULL COMMENT 'DocumentDrawingDB移交文件包序號',
    acceptance_request_sid VARCHAR(32) NULL COMMENT 'CommissioningHandoverDB驗收申請序號',
    actual_handover_date DATETIME NULL COMMENT '實際交屋時間',
    appointment_status VARCHAR(30) NOT NULL DEFAULT 'PLANNED' COMMENT 'PLANNED規劃;CONFIRMED已確認;INSPECTING驗屋中;PUNCH_LIST缺失改善;READY可交屋;HANDED_OVER已交屋;RESCHEDULED改期;CANCELLED取消',
    CONSTRAINT uk_cha_appointment_no UNIQUE (handover_appointment_no),
    INDEX idx_cha_sales_contract_sid (sales_contract_sid),
    INDEX idx_cha_customer_sid (customer_sid),
    INDEX idx_cha_sales_unit_sid (sales_unit_sid),
    INDEX idx_cha_planned_handover_date (planned_handover_date),
    INDEX idx_cha_status (appointment_status),
    CHECK (actual_handover_date IS NULL OR actual_handover_date >= planned_handover_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶驗屋與交屋預約';

CREATE TABLE IF NOT EXISTS crm_handover_defect (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '交屋缺失序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    defect_no VARCHAR(100) NOT NULL COMMENT '交屋缺失編號',
    handover_appointment_sid VARCHAR(32) NOT NULL COMMENT '交屋預約序號',
    sales_contract_sid VARCHAR(32) NOT NULL COMMENT '銷售合約序號',
    sales_unit_sid VARCHAR(32) NOT NULL COMMENT '銷售單元序號',
    defect_category VARCHAR(30) NOT NULL COMMENT 'STRUCTURE結構;WATERPROOF防水;FINISH裝修;DOOR_WINDOW門窗;ELECTRICAL電氣;PLUMBING給排水;EQUIPMENT設備;CLEANING清潔;OTHER',
    severity VARCHAR(20) NOT NULL DEFAULT 'MINOR' COMMENT 'MINOR輕微;MAJOR重大;CRITICAL嚴重',
    location_description VARCHAR(1000) NULL COMMENT '缺失位置',
    description LONGTEXT NOT NULL COMMENT '缺失內容',
    raised_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提出時間',
    raised_by_party_sid VARCHAR(32) NULL COMMENT '提出Party序號',
    responsible_party_sid VARCHAR(32) NULL COMMENT '改善責任Party序號',
    due_date DATE NULL COMMENT '改善期限',
    correction TEXT NULL COMMENT '改善內容',
    evidence_file_sid VARCHAR(32) NULL COMMENT 'FileDB改善照片序號',
    verified_by_party_sid VARCHAR(32) NULL COMMENT '驗證Party序號',
    verified_date DATETIME NULL COMMENT '驗證時間',
    warranty_request_sid VARCHAR(32) NULL COMMENT 'WarrantyMaintenanceDB報修序號',
    defect_status VARCHAR(30) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN未處理;ASSIGNED已指派;IN_PROGRESS改善中;WAITING_VERIFICATION待複驗;VERIFIED已確認;CLOSED結案;REJECTED退回;VOID作廢',
    CONSTRAINT uk_chd_defect_no UNIQUE (defect_no),
    INDEX idx_chd_handover_appointment_sid (handover_appointment_sid),
    INDEX idx_chd_sales_contract_sid (sales_contract_sid),
    INDEX idx_chd_sales_unit_sid (sales_unit_sid),
    INDEX idx_chd_category (defect_category),
    INDEX idx_chd_severity (severity),
    INDEX idx_chd_responsible_party_sid (responsible_party_sid),
    INDEX idx_chd_due_date (due_date),
    INDEX idx_chd_status (defect_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶驗屋與交屋缺失';

CREATE TABLE IF NOT EXISTS crm_complaint (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客訴序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    complaint_no VARCHAR(100) NOT NULL COMMENT '客訴編號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    sales_contract_sid VARCHAR(32) NULL COMMENT '銷售合約序號',
    sales_unit_sid VARCHAR(32) NULL COMMENT '銷售單元序號',
    complaint_type VARCHAR(30) NOT NULL COMMENT 'SALES銷售;CONTRACT合約;PAYMENT收款;CONSTRUCTION施工;QUALITY品質;HANDOVER交屋;SERVICE服務;OTHER',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW低;NORMAL一般;HIGH高;URGENT緊急;CRITICAL重大',
    subject VARCHAR(500) NOT NULL COMMENT '客訴主旨',
    description LONGTEXT NOT NULL COMMENT '客訴內容',
    reported_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '客訴時間',
    channel_type VARCHAR(20) NOT NULL COMMENT 'PHONE電話;EMAIL郵件;LINE;APP;PORTAL;IN_PERSON現場;OTHER',
    assigned_party_sid VARCHAR(32) NULL COMMENT '承辦Party序號',
    response_due_date DATETIME NULL COMMENT '回覆期限',
    first_response_date DATETIME NULL COMMENT '首次回覆時間',
    resolution TEXT NULL COMMENT '處理結果',
    resolved_date DATETIME NULL COMMENT '解決時間',
    warranty_request_sid VARCHAR(32) NULL COMMENT 'WarrantyMaintenanceDB報修序號',
    risk_incident_sid VARCHAR(32) NULL COMMENT 'RiskComplianceDB合規事件序號',
    complaint_status VARCHAR(30) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN已建立;ASSIGNED已指派;IN_PROGRESS處理中;WAITING_CUSTOMER待客戶;RESOLVED已解決;CLOSED結案;REJECTED不成立;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_ccomp_complaint_no UNIQUE (complaint_no),
    INDEX idx_ccomp_customer_sid (customer_sid),
    INDEX idx_ccomp_sales_project_sid (sales_project_sid),
    INDEX idx_ccomp_sales_contract_sid (sales_contract_sid),
    INDEX idx_ccomp_sales_unit_sid (sales_unit_sid),
    INDEX idx_ccomp_complaint_type (complaint_type),
    INDEX idx_ccomp_priority (priority),
    INDEX idx_ccomp_reported_date (reported_date),
    INDEX idx_ccomp_assigned_party_sid (assigned_party_sid),
    INDEX idx_ccomp_status (complaint_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='銷售、合約、付款、施工與交屋客訴';

CREATE TABLE IF NOT EXISTS crm_satisfaction_survey (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '客戶滿意度序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    survey_no VARCHAR(100) NOT NULL COMMENT '問卷編號',
    customer_sid VARCHAR(32) NOT NULL COMMENT '客戶序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    sales_contract_sid VARCHAR(32) NULL COMMENT '銷售合約序號',
    survey_type VARCHAR(30) NOT NULL COMMENT 'SALES銷售體驗;CONTRACT簽約;CONSTRUCTION施工資訊;HANDOVER交屋;AFTER_SALES售後;OVERALL整體',
    survey_date DATE NOT NULL COMMENT '問卷日期',
    survey_data JSON NOT NULL COMMENT '問卷答案',
    overall_score DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '整體滿意度',
    nps_score INT NULL COMMENT 'NPS分數',
    comment_text LONGTEXT NULL COMMENT '客戶意見',
    follow_up_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需追蹤',
    assigned_party_sid VARCHAR(32) NULL COMMENT '追蹤Party序號',
    survey_status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED' COMMENT 'SENT已寄送;COMPLETED已完成;FOLLOW_UP追蹤中;CLOSED結案',
    CONSTRAINT uk_css_survey_no UNIQUE (survey_no),
    INDEX idx_css_customer_sid (customer_sid),
    INDEX idx_css_sales_project_sid (sales_project_sid),
    INDEX idx_css_sales_contract_sid (sales_contract_sid),
    INDEX idx_css_survey_type (survey_type),
    INDEX idx_css_survey_date (survey_date),
    INDEX idx_css_follow_up_required (follow_up_required),
    INDEX idx_css_status (survey_status),
    CHECK (overall_score BETWEEN 0 AND 100),
    CHECK (nps_score IS NULL OR nps_score BETWEEN 0 AND 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='銷售、交屋與售後滿意度';

CREATE TABLE IF NOT EXISTS crm_sales_kpi_snapshot (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '銷售CRM KPI序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    snapshot_no VARCHAR(100) NOT NULL COMMENT '快照編號',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    sales_party_sid VARCHAR(32) NULL COMMENT '業務Party序號',
    period_start_date DATE NOT NULL COMMENT '期間開始日',
    period_end_date DATE NOT NULL COMMENT '期間結束日',
    lead_count INT NOT NULL DEFAULT 0 COMMENT '潛客數',
    qualified_lead_count INT NOT NULL DEFAULT 0 COMMENT '有效潛客數',
    opportunity_count INT NOT NULL DEFAULT 0 COMMENT '商機數',
    visit_count INT NOT NULL DEFAULT 0 COMMENT '賞屋次數',
    quotation_count INT NOT NULL DEFAULT 0 COMMENT '報價次數',
    reservation_count INT NOT NULL DEFAULT 0 COMMENT '保留數',
    contract_count INT NOT NULL DEFAULT 0 COMMENT '簽約數',
    sold_unit_count INT NOT NULL DEFAULT 0 COMMENT '成交戶數',
    sales_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '成交金額',
    collected_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '已收款金額',
    outstanding_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '未收款金額',
    conversion_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '轉換率',
    average_unit_price DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '平均成交單價',
    cancellation_count INT NOT NULL DEFAULT 0 COMMENT '解約數',
    complaint_count INT NOT NULL DEFAULT 0 COMMENT '客訴數',
    customer_satisfaction_score DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '客戶滿意度',
    snapshot_status VARCHAR(20) NOT NULL DEFAULT 'FINAL' COMMENT 'DRAFT草稿;FINAL正式;ARCHIVED封存',
    CONSTRAINT uk_csks_snapshot_no UNIQUE (snapshot_no),
    INDEX idx_csks_company_sid (company_sid),
    INDEX idx_csks_sales_project_sid (sales_project_sid),
    INDEX idx_csks_sales_party_sid (sales_party_sid),
    INDEX idx_csks_period (period_start_date, period_end_date),
    INDEX idx_csks_status (snapshot_status),
    CHECK (period_end_date >= period_start_date),
    CHECK (lead_count >= 0),
    CHECK (qualified_lead_count >= 0),
    CHECK (opportunity_count >= 0),
    CHECK (visit_count >= 0),
    CHECK (quotation_count >= 0),
    CHECK (reservation_count >= 0),
    CHECK (contract_count >= 0),
    CHECK (sold_unit_count >= 0),
    CHECK (sales_amount >= 0),
    CHECK (collected_amount >= 0),
    CHECK (outstanding_amount >= 0),
    CHECK (conversion_rate BETWEEN 0 AND 100),
    CHECK (average_unit_price >= 0),
    CHECK (cancellation_count >= 0),
    CHECK (complaint_count >= 0),
    CHECK (customer_satisfaction_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='潛客、商機、簽約、收款與滿意度KPI';

CREATE TABLE IF NOT EXISTS crm_status_history (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT 'CRM狀態歷程序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type VARCHAR(30) NOT NULL COMMENT 'LEAD;CUSTOMER;SALES_PROJECT;SALES_UNIT;OPPORTUNITY;VISIT;QUOTATION;RESERVATION;CONTRACT;RECEIVABLE;PAYMENT;CHANGE;CUSTOMER_CHANGE;HANDOVER;DEFECT;COMPLAINT;SURVEY',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    old_status VARCHAR(30) NULL COMMENT '原狀態',
    new_status VARCHAR(30) NOT NULL COMMENT '新狀態',
    event_code VARCHAR(100) NULL COMMENT '觸發事件代碼',
    operator_user_sid VARCHAR(32) NULL COMMENT '操作人員序號',
    reason TEXT NULL COMMENT '原因說明',
    correlation_id VARCHAR(100) NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_csh_entity (entity_type, entity_sid),
    INDEX idx_csh_new_status (new_status),
    INDEX idx_csh_event_code (event_code),
    INDEX idx_csh_operator_user_sid (operator_user_sid),
    INDEX idx_csh_correlation_id (correlation_id),
    INDEX idx_csh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='潛客、銷售、合約、交屋與客訴狀態歷程';

CREATE TABLE IF NOT EXISTS crm_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT 'CRM領域事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type VARCHAR(30) NOT NULL COMMENT 'LEAD;CUSTOMER;SALES_PROJECT;SALES_UNIT;OPPORTUNITY;INTERACTION;VISIT;QUOTATION;RESERVATION;CONTRACT;RECEIVABLE;PAYMENT;CHANGE;HANDOVER;DEFECT;COMPLAINT;SURVEY;KPI',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    event_code VARCHAR(120) NOT NULL COMMENT '事件代碼',
    event_version INT NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data JSON NULL COMMENT '事件內容',
    source_event_id VARCHAR(100) NULL COMMENT '來源事件ID',
    correlation_id VARCHAR(100) NULL COMMENT '關聯識別碼',
    causation_id VARCHAR(100) NULL COMMENT '因果事件ID',
    outbox_event_sid VARCHAR(32) NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date DATETIME NULL COMMENT '處理時間',
    error_message TEXT NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_ce_source_event_id (source_event_id),
    INDEX idx_ce_entity (entity_type, entity_sid),
    INDEX idx_ce_event_code (event_code),
    INDEX idx_ce_correlation_id (correlation_id),
    INDEX idx_ce_outbox_event_sid (outbox_event_sid),
    INDEX idx_ce_status (process_status),
    INDEX idx_ce_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶、銷售、收款、交屋與售後領域事件';
SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
