namespace B2bOrder.Resources.eCommerce
{
    /// <summary>
    /// MarketingCampaignDB V2 Shared Core Schema
    /// 支援行銷活動、投放管道、廣告素材、落地頁、表單、流量追蹤、轉換歸因、促銷、優惠券、推薦、訊息與成效分析。
    /// nid：資料庫內部主鍵；sid：跨服務/API 對外識別碼。
    /// avalible：Y可用；W停用；D刪除。
    /// 適用 MySQL 8.x / InnoDB / utf8mb4。
    /// </summary>
    internal static class MarketingCampaignDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS mkt_campaign (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷活動序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    campaign_no VARCHAR(100) NOT NULL COMMENT '活動編號',
    campaign_name VARCHAR(300) NOT NULL COMMENT '活動名稱',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    sales_project_sid VARCHAR(32) NULL COMMENT 'CustomerSalesCRMDB銷售建案序號',
    campaign_type VARCHAR(30) NOT NULL COMMENT 'BRAND品牌;LEAD_GENERATION名單;SALES_PROMOTION促銷;EVENT活動;CONTENT內容;REFERRAL推薦;RETARGETING再行銷;OTHER',
    objective_type VARCHAR(30) NOT NULL COMMENT 'AWARENESS曝光;TRAFFIC流量;LEAD名單;VISIT賞屋;RESERVATION保留;CONTRACT簽約;REVENUE營收',
    planned_start_date DATETIME NOT NULL COMMENT '預計開始時間',
    planned_end_date DATETIME NOT NULL COMMENT '預計結束時間',
    actual_start_date DATETIME NULL COMMENT '實際開始時間',
    actual_end_date DATETIME NULL COMMENT '實際結束時間',
    budget_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '活動預算',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    owner_party_sid VARCHAR(32) NULL COMMENT '活動負責Party序號',
    target_audience JSON NULL COMMENT '目標客群條件',
    campaign_description LONGTEXT NULL COMMENT '活動說明',
    campaign_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;APPROVED核准;SCHEDULED已排程;ACTIVE執行中;PAUSED暫停;COMPLETED完成;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_mc_campaign_no UNIQUE (campaign_no),
    INDEX idx_mc_company_sid (company_sid),
    INDEX idx_mc_sales_project_sid (sales_project_sid),
    INDEX idx_mc_campaign_type (campaign_type),
    INDEX idx_mc_objective_type (objective_type),
    INDEX idx_mc_planned_start_date (planned_start_date),
    INDEX idx_mc_owner_party_sid (owner_party_sid),
    INDEX idx_mc_status (campaign_status),
    CHECK (planned_end_date >= planned_start_date),
    CHECK (actual_end_date IS NULL OR actual_start_date IS NULL OR actual_end_date >= actual_start_date),
    CHECK (budget_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='品牌、名單、促銷與銷售行銷活動';

CREATE TABLE IF NOT EXISTS mkt_channel (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷管道序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    channel_code VARCHAR(100) NOT NULL COMMENT '管道代碼',
    channel_name VARCHAR(200) NOT NULL COMMENT '管道名稱',
    channel_type VARCHAR(30) NOT NULL COMMENT 'WEBSITE官網;SEARCH搜尋;SOCIAL社群;DISPLAY聯播網;EMAIL郵件;LINE;SMS簡訊;APP推播;OFFLINE線下;AGENT代銷;REFERRAL推薦;OTHER',
    platform_name VARCHAR(200) NULL COMMENT '平台名稱',
    account_reference VARCHAR(300) NULL COMMENT '廣告帳戶或平台帳號',
    default_currency_sid VARCHAR(32) NULL COMMENT '預設幣別序號',
    tracking_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否啟用追蹤',
    channel_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE啟用;INACTIVE停用',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_mch_channel_code UNIQUE (channel_code),
    INDEX idx_mch_channel_type (channel_type),
    INDEX idx_mch_platform_name (platform_name),
    INDEX idx_mch_status (channel_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='官網、搜尋、社群、LINE與線下行銷管道';

CREATE TABLE IF NOT EXISTS mkt_campaign_channel (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '活動管道序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    campaign_sid VARCHAR(32) NOT NULL COMMENT '行銷活動序號',
    channel_sid VARCHAR(32) NOT NULL COMMENT '行銷管道序號',
    channel_campaign_id VARCHAR(200) NULL COMMENT '外部平台活動ID',
    planned_budget DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '管道預算',
    actual_spend DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '實際花費',
    start_date DATETIME NULL COMMENT '管道開始時間',
    end_date DATETIME NULL COMMENT '管道結束時間',
    landing_page_url VARCHAR(1000) NULL COMMENT '活動落地頁',
    tracking_code VARCHAR(200) NULL COMMENT '追蹤代碼',
    channel_status VARCHAR(20) NOT NULL DEFAULT 'PLANNED' COMMENT 'PLANNED規劃;ACTIVE執行中;PAUSED暫停;COMPLETED完成;CANCELLED取消',
    CONSTRAINT uk_mcc_campaign_channel UNIQUE (campaign_sid, channel_sid),
    INDEX idx_mcc_campaign_sid (campaign_sid),
    INDEX idx_mcc_channel_sid (channel_sid),
    INDEX idx_mcc_channel_campaign_id (channel_campaign_id),
    INDEX idx_mcc_status (channel_status),
    CHECK (planned_budget >= 0),
    CHECK (actual_spend >= 0),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行銷活動與投放管道配置';

CREATE TABLE IF NOT EXISTS mkt_ad_group (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '廣告群組序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    campaign_channel_sid VARCHAR(32) NOT NULL COMMENT '活動管道序號',
    ad_group_code VARCHAR(100) NOT NULL COMMENT '廣告群組代碼',
    ad_group_name VARCHAR(300) NOT NULL COMMENT '廣告群組名稱',
    external_ad_group_id VARCHAR(200) NULL COMMENT '外部平台群組ID',
    audience_definition JSON NULL COMMENT '受眾條件',
    bid_strategy VARCHAR(50) NULL COMMENT '出價策略',
    daily_budget DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '每日預算',
    start_date DATETIME NULL COMMENT '開始時間',
    end_date DATETIME NULL COMMENT '結束時間',
    ad_group_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;ACTIVE執行中;PAUSED暫停;COMPLETED完成;CANCELLED取消',
    CONSTRAINT uk_mag_channel_group_code UNIQUE (campaign_channel_sid, ad_group_code),
    INDEX idx_mag_campaign_channel_sid (campaign_channel_sid),
    INDEX idx_mag_external_ad_group_id (external_ad_group_id),
    INDEX idx_mag_status (ad_group_status),
    CHECK (daily_budget >= 0),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='數位廣告群組與受眾';

CREATE TABLE IF NOT EXISTS mkt_creative (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '廣告素材序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    creative_no VARCHAR(100) NOT NULL COMMENT '素材編號',
    campaign_sid VARCHAR(32) NOT NULL COMMENT '行銷活動序號',
    ad_group_sid VARCHAR(32) NULL COMMENT '廣告群組序號',
    creative_type VARCHAR(30) NOT NULL COMMENT 'IMAGE圖片;VIDEO影片;TEXT文字;CAROUSEL輪播;BANNER橫幅;LANDING_PAGE落地頁;PRINT印刷;OTHER',
    creative_name VARCHAR(300) NOT NULL COMMENT '素材名稱',
    headline VARCHAR(500) NULL COMMENT '主標題',
    body_text LONGTEXT NULL COMMENT '文案內容',
    call_to_action VARCHAR(100) NULL COMMENT '行動按鈕',
    destination_url VARCHAR(1000) NULL COMMENT '目的網址',
    file_sid VARCHAR(32) NULL COMMENT 'FileDB素材檔案序號',
    thumbnail_file_sid VARCHAR(32) NULL COMMENT 'FileDB縮圖序號',
    external_creative_id VARCHAR(200) NULL COMMENT '外部平台素材ID',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需審核',
    creative_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;APPROVED核准;ACTIVE上線;PAUSED暫停;REJECTED退回;ARCHIVED封存',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_mcr_creative_no UNIQUE (creative_no),
    INDEX idx_mcr_campaign_sid (campaign_sid),
    INDEX idx_mcr_ad_group_sid (ad_group_sid),
    INDEX idx_mcr_creative_type (creative_type),
    INDEX idx_mcr_external_creative_id (external_creative_id),
    INDEX idx_mcr_status (creative_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='數位、印刷與活動廣告素材';

CREATE TABLE IF NOT EXISTS mkt_landing_page (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '落地頁序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    page_no VARCHAR(100) NOT NULL COMMENT '落地頁編號',
    page_name VARCHAR(300) NOT NULL COMMENT '落地頁名稱',
    campaign_sid VARCHAR(32) NOT NULL COMMENT '行銷活動序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    page_url VARCHAR(1000) NOT NULL COMMENT '頁面網址',
    page_version VARCHAR(50) NOT NULL DEFAULT '1' COMMENT '頁面版本',
    template_code VARCHAR(100) NULL COMMENT '頁面範本代碼',
    form_sid VARCHAR(32) NULL COMMENT '名單表單序號',
    publish_start_date DATETIME NULL COMMENT '發布開始時間',
    publish_end_date DATETIME NULL COMMENT '發布結束時間',
    seo_title VARCHAR(500) NULL COMMENT 'SEO標題',
    seo_description VARCHAR(1000) NULL COMMENT 'SEO描述',
    page_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;PUBLISHED已發布;PAUSED暫停;ARCHIVED封存',
    CONSTRAINT uk_mlp_page_no UNIQUE (page_no),
    CONSTRAINT uk_mlp_page_url UNIQUE (page_url),
    INDEX idx_mlp_campaign_sid (campaign_sid),
    INDEX idx_mlp_sales_project_sid (sales_project_sid),
    INDEX idx_mlp_form_sid (form_sid),
    INDEX idx_mlp_status (page_status),
    CHECK (publish_end_date IS NULL OR publish_start_date IS NULL OR publish_end_date >= publish_start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案與活動落地頁';

CREATE TABLE IF NOT EXISTS mkt_lead_form (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '名單表單序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    form_code VARCHAR(100) NOT NULL COMMENT '表單代碼',
    form_name VARCHAR(300) NOT NULL COMMENT '表單名稱',
    company_sid VARCHAR(32) NOT NULL COMMENT '公司序號',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    form_type VARCHAR(30) NOT NULL COMMENT 'CONTACT聯絡;REGISTER活動報名;DOWNLOAD下載;VISIT賞屋;QUOTE詢價;SURVEY問卷;OTHER',
    field_schema JSON NOT NULL COMMENT '表單欄位定義',
    consent_text LONGTEXT NULL COMMENT '個資與行銷同意文字',
    privacy_policy_url VARCHAR(1000) NULL COMMENT '隱私權政策網址',
    success_message VARCHAR(1000) NULL COMMENT '送出成功訊息',
    redirect_url VARCHAR(1000) NULL COMMENT '送出後導向網址',
    form_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'DRAFT草稿;ACTIVE啟用;INACTIVE停用;ARCHIVED封存',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    CONSTRAINT uk_mlf_form_code UNIQUE (form_code),
    INDEX idx_mlf_company_sid (company_sid),
    INDEX idx_mlf_campaign_sid (campaign_sid),
    INDEX idx_mlf_sales_project_sid (sales_project_sid),
    INDEX idx_mlf_form_type (form_type),
    INDEX idx_mlf_status (form_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='官網、廣告與活動名單表單';

CREATE TABLE IF NOT EXISTS mkt_form_submission (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '表單送出序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    submission_no VARCHAR(100) NOT NULL COMMENT '送出編號',
    form_sid VARCHAR(32) NOT NULL COMMENT '名單表單序號',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    landing_page_sid VARCHAR(32) NULL COMMENT '落地頁序號',
    submitted_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '送出時間',
    form_data JSON NOT NULL COMMENT '表單內容',
    contact_name VARCHAR(300) NULL COMMENT '聯絡人名稱快照',
    contact_phone VARCHAR(100) NULL COMMENT '電話快照',
    contact_email VARCHAR(300) NULL COMMENT '信箱快照',
    consent_marketing TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否同意行銷',
    consent_privacy TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否同意個資政策',
    source_channel_sid VARCHAR(32) NULL COMMENT '來源行銷管道序號',
    source_tracking_sid VARCHAR(32) NULL COMMENT '流量追蹤序號',
    ip_address VARCHAR(50) NULL COMMENT 'IP位址',
    user_agent VARCHAR(1000) NULL COMMENT '使用者代理',
    duplicate_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重複名單',
    spam_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否垃圾資料',
    converted_lead_sid VARCHAR(32) NULL COMMENT '轉換後CRM潛客序號',
    conversion_date DATETIME NULL COMMENT '轉換時間',
    submission_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' COMMENT 'RECEIVED已收件;VALIDATED已驗證;CONVERTED已轉潛客;REJECTED拒絕;SPAM垃圾;DUPLICATE重複',
    CONSTRAINT uk_mfs_submission_no UNIQUE (submission_no),
    INDEX idx_mfs_form_sid (form_sid),
    INDEX idx_mfs_campaign_sid (campaign_sid),
    INDEX idx_mfs_landing_page_sid (landing_page_sid),
    INDEX idx_mfs_submitted_date (submitted_date),
    INDEX idx_mfs_source_channel_sid (source_channel_sid),
    INDEX idx_mfs_converted_lead_sid (converted_lead_sid),
    INDEX idx_mfs_status (submission_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='名單表單送出與CRM潛客轉換';

CREATE TABLE IF NOT EXISTS mkt_tracking_session (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷追蹤工作階段序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    session_id VARCHAR(150) NOT NULL COMMENT '網站或App工作階段ID',
    visitor_id VARCHAR(150) NULL COMMENT '訪客識別碼',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    channel_sid VARCHAR(32) NULL COMMENT '行銷管道序號',
    landing_page_sid VARCHAR(32) NULL COMMENT '落地頁序號',
    first_touch_date DATETIME NOT NULL COMMENT '首次接觸時間',
    last_touch_date DATETIME NOT NULL COMMENT '最後接觸時間',
    utm_source VARCHAR(200) NULL COMMENT 'UTM Source',
    utm_medium VARCHAR(200) NULL COMMENT 'UTM Medium',
    utm_campaign VARCHAR(300) NULL COMMENT 'UTM Campaign',
    utm_term VARCHAR(300) NULL COMMENT 'UTM Term',
    utm_content VARCHAR(300) NULL COMMENT 'UTM Content',
    referrer_url VARCHAR(1000) NULL COMMENT '來源網址',
    landing_url VARCHAR(1000) NULL COMMENT '首次落地網址',
    device_type VARCHAR(30) NULL COMMENT 'DESKTOP桌機;MOBILE手機;TABLET平板;OTHER',
    browser_name VARCHAR(100) NULL COMMENT '瀏覽器',
    operating_system VARCHAR(100) NULL COMMENT '作業系統',
    country_code VARCHAR(10) NULL COMMENT '國家代碼',
    region_name VARCHAR(200) NULL COMMENT '地區名稱',
    page_view_count INT NOT NULL DEFAULT 0 COMMENT '瀏覽頁數',
    conversion_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否轉換',
    CONSTRAINT uk_mts_session_id UNIQUE (session_id),
    INDEX idx_mts_visitor_id (visitor_id),
    INDEX idx_mts_campaign_sid (campaign_sid),
    INDEX idx_mts_channel_sid (channel_sid),
    INDEX idx_mts_landing_page_sid (landing_page_sid),
    INDEX idx_mts_first_touch_date (first_touch_date),
    INDEX idx_mts_conversion_mark (conversion_mark),
    CHECK (last_touch_date >= first_touch_date),
    CHECK (page_view_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='網站、App與廣告流量追蹤';

CREATE TABLE IF NOT EXISTS mkt_conversion_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷轉換事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    conversion_no VARCHAR(100) NOT NULL COMMENT '轉換事件編號',
    tracking_session_sid VARCHAR(32) NULL COMMENT '追蹤工作階段序號',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    channel_sid VARCHAR(32) NULL COMMENT '行銷管道序號',
    conversion_type VARCHAR(30) NOT NULL COMMENT 'FORM_SUBMIT表單;LEAD潛客;VISIT賞屋;QUOTATION報價;RESERVATION保留;CONTRACT簽約;PAYMENT收款;OTHER',
    conversion_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '轉換時間',
    reference_type VARCHAR(30) NULL COMMENT 'FORM_SUBMISSION;LEAD;OPPORTUNITY;VISIT;QUOTATION;RESERVATION;CONTRACT;PAYMENT',
    reference_sid VARCHAR(32) NULL COMMENT '轉換資料序號',
    customer_sid VARCHAR(32) NULL COMMENT 'CRM客戶序號',
    lead_sid VARCHAR(32) NULL COMMENT 'CRM潛客序號',
    conversion_value DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '轉換價值',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    attributed_mark TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已完成歸因',
    CONSTRAINT uk_mce_conversion_no UNIQUE (conversion_no),
    INDEX idx_mce_tracking_session_sid (tracking_session_sid),
    INDEX idx_mce_campaign_sid (campaign_sid),
    INDEX idx_mce_channel_sid (channel_sid),
    INDEX idx_mce_conversion_type (conversion_type),
    INDEX idx_mce_conversion_date (conversion_date),
    INDEX idx_mce_reference (reference_type, reference_sid),
    INDEX idx_mce_customer_sid (customer_sid),
    INDEX idx_mce_lead_sid (lead_sid),
    CHECK (conversion_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='名單、賞屋、保留、簽約與收款轉換事件';

CREATE TABLE IF NOT EXISTS mkt_attribution (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷歸因序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    conversion_event_sid VARCHAR(32) NOT NULL COMMENT '轉換事件序號',
    attribution_model VARCHAR(30) NOT NULL COMMENT 'FIRST_TOUCH首次;LAST_TOUCH最後;LINEAR線性;TIME_DECAY時間衰減;POSITION_BASED位置;DATA_DRIVEN資料驅動;CUSTOM自訂',
    campaign_sid VARCHAR(32) NULL COMMENT '歸因活動序號',
    channel_sid VARCHAR(32) NULL COMMENT '歸因管道序號',
    creative_sid VARCHAR(32) NULL COMMENT '歸因素材序號',
    tracking_session_sid VARCHAR(32) NULL COMMENT '歸因工作階段序號',
    attribution_percent DECIMAL(8,4) NOT NULL COMMENT '歸因比例',
    attributed_value DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '歸因價值',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    model_version VARCHAR(50) NULL COMMENT '歸因模型版本',
    calculation_data JSON NULL COMMENT '歸因計算資料',
    CONSTRAINT uk_ma_conversion_touch UNIQUE (conversion_event_sid, attribution_model, campaign_sid, channel_sid, creative_sid, tracking_session_sid),
    INDEX idx_ma_conversion_event_sid (conversion_event_sid),
    INDEX idx_ma_attribution_model (attribution_model),
    INDEX idx_ma_campaign_sid (campaign_sid),
    INDEX idx_ma_channel_sid (channel_sid),
    INDEX idx_ma_creative_sid (creative_sid),
    CHECK (attribution_percent BETWEEN 0 AND 100),
    CHECK (attributed_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='首次、最後、線性與資料驅動銷售歸因';

CREATE TABLE IF NOT EXISTS mkt_promotion (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '促銷方案序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    promotion_no VARCHAR(100) NOT NULL COMMENT '促銷編號',
    promotion_name VARCHAR(300) NOT NULL COMMENT '促銷名稱',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    promotion_type VARCHAR(30) NOT NULL COMMENT 'DISCOUNT折扣;FIXED_REDUCTION定額減免;GIFT贈品;UPGRADE升級;FEE_WAIVER費用減免;BUNDLE組合;OTHER',
    start_date DATETIME NOT NULL COMMENT '開始時間',
    end_date DATETIME NOT NULL COMMENT '結束時間',
    eligibility_rule JSON NULL COMMENT '適用資格',
    benefit_rule JSON NOT NULL COMMENT '優惠內容',
    budget_limit DECIMAL(20,4) NULL COMMENT '優惠預算上限',
    usage_limit INT NULL COMMENT '總使用次數上限',
    per_customer_limit INT NULL COMMENT '每客戶使用上限',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需核准',
    promotion_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;ACTIVE生效;PAUSED暫停;EXPIRED到期;CANCELLED取消',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_mp_promotion_no UNIQUE (promotion_no),
    INDEX idx_mp_campaign_sid (campaign_sid),
    INDEX idx_mp_sales_project_sid (sales_project_sid),
    INDEX idx_mp_promotion_type (promotion_type),
    INDEX idx_mp_start_date (start_date),
    INDEX idx_mp_end_date (end_date),
    INDEX idx_mp_status (promotion_status),
    CHECK (end_date >= start_date),
    CHECK (budget_limit IS NULL OR budget_limit >= 0),
    CHECK (usage_limit IS NULL OR usage_limit > 0),
    CHECK (per_customer_limit IS NULL OR per_customer_limit > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='折扣、贈品、升級與費用減免促銷';

CREATE TABLE IF NOT EXISTS mkt_coupon (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '優惠券序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    coupon_code VARCHAR(100) NOT NULL COMMENT '優惠券代碼',
    promotion_sid VARCHAR(32) NOT NULL COMMENT '促銷方案序號',
    coupon_type VARCHAR(20) NOT NULL COMMENT 'PUBLIC公用;UNIQUE單次;CUSTOMER_SPECIFIC指定客戶;BATCH批次',
    customer_sid VARCHAR(32) NULL COMMENT '指定CRM客戶序號',
    issue_date DATETIME NULL COMMENT '發券時間',
    valid_start_date DATETIME NOT NULL COMMENT '有效開始時間',
    valid_end_date DATETIME NOT NULL COMMENT '有效結束時間',
    usage_limit INT NOT NULL DEFAULT 1 COMMENT '可使用次數',
    used_count INT NOT NULL DEFAULT 0 COMMENT '已使用次數',
    coupon_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE可用;USED已使用;EXPIRED過期;SUSPENDED暫停;CANCELLED取消',
    CONSTRAINT uk_mcoupon_coupon_code UNIQUE (coupon_code),
    INDEX idx_mcoupon_promotion_sid (promotion_sid),
    INDEX idx_mcoupon_customer_sid (customer_sid),
    INDEX idx_mcoupon_valid_end_date (valid_end_date),
    INDEX idx_mcoupon_status (coupon_status),
    CHECK (valid_end_date >= valid_start_date),
    CHECK (usage_limit > 0),
    CHECK (used_count >= 0),
    CHECK (used_count <= usage_limit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='建案促銷優惠券與代碼';

CREATE TABLE IF NOT EXISTS mkt_coupon_redemption (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '優惠券使用序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    coupon_sid VARCHAR(32) NOT NULL COMMENT '優惠券序號',
    customer_sid VARCHAR(32) NULL COMMENT 'CRM客戶序號',
    lead_sid VARCHAR(32) NULL COMMENT 'CRM潛客序號',
    redemption_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '使用時間',
    reference_type VARCHAR(30) NOT NULL COMMENT 'QUOTATION報價;RESERVATION保留;CONTRACT合約;PAYMENT付款;OTHER',
    reference_sid VARCHAR(32) NOT NULL COMMENT '使用資料序號',
    benefit_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '優惠金額',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    redemption_status VARCHAR(20) NOT NULL DEFAULT 'APPLIED' COMMENT 'APPLIED已套用;VERIFIED已驗證;REVERSED已沖回;REJECTED拒絕',
    CONSTRAINT uk_mcred_coupon_reference UNIQUE (coupon_sid, reference_type, reference_sid),
    INDEX idx_mcred_coupon_sid (coupon_sid),
    INDEX idx_mcred_customer_sid (customer_sid),
    INDEX idx_mcred_lead_sid (lead_sid),
    INDEX idx_mcred_redemption_date (redemption_date),
    INDEX idx_mcred_status (redemption_status),
    CHECK (benefit_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='優惠券於報價、保留與合約的使用紀錄';

CREATE TABLE IF NOT EXISTS mkt_referral_program (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '推薦活動序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    program_no VARCHAR(100) NOT NULL COMMENT '推薦活動編號',
    program_name VARCHAR(300) NOT NULL COMMENT '推薦活動名稱',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    sales_project_sid VARCHAR(32) NULL COMMENT '銷售建案序號',
    start_date DATETIME NOT NULL COMMENT '開始時間',
    end_date DATETIME NOT NULL COMMENT '結束時間',
    referrer_rule JSON NULL COMMENT '推薦人資格',
    referee_rule JSON NULL COMMENT '被推薦人資格',
    reward_rule JSON NOT NULL COMMENT '獎勵規則',
    reward_trigger VARCHAR(30) NOT NULL COMMENT 'LEAD潛客;VISIT賞屋;RESERVATION保留;CONTRACT簽約;PAYMENT收款',
    budget_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '推薦獎勵預算',
    currency_sid VARCHAR(32) NOT NULL COMMENT '幣別序號',
    program_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;ACTIVE生效;PAUSED暫停;EXPIRED到期;CANCELLED取消',
    CONSTRAINT uk_mrp_program_no UNIQUE (program_no),
    INDEX idx_mrp_campaign_sid (campaign_sid),
    INDEX idx_mrp_sales_project_sid (sales_project_sid),
    INDEX idx_mrp_start_date (start_date),
    INDEX idx_mrp_end_date (end_date),
    INDEX idx_mrp_status (program_status),
    CHECK (end_date >= start_date),
    CHECK (budget_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客戶、員工與合作夥伴推薦活動';

CREATE TABLE IF NOT EXISTS mkt_referral (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '推薦紀錄序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    referral_no VARCHAR(100) NOT NULL COMMENT '推薦編號',
    referral_program_sid VARCHAR(32) NOT NULL COMMENT '推薦活動序號',
    referrer_type VARCHAR(20) NOT NULL COMMENT 'CUSTOMER客戶;EMPLOYEE員工;PARTNER合作夥伴;AGENT仲介;OTHER',
    referrer_sid VARCHAR(32) NOT NULL COMMENT '推薦人序號',
    referee_name VARCHAR(300) NOT NULL COMMENT '被推薦人名稱',
    referee_phone VARCHAR(100) NULL COMMENT '電話',
    referee_email VARCHAR(300) NULL COMMENT '信箱',
    referral_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '推薦時間',
    converted_lead_sid VARCHAR(32) NULL COMMENT '轉換後CRM潛客序號',
    converted_customer_sid VARCHAR(32) NULL COMMENT '轉換後CRM客戶序號',
    trigger_reference_type VARCHAR(30) NULL COMMENT 'LEAD;VISIT;RESERVATION;CONTRACT;PAYMENT',
    trigger_reference_sid VARCHAR(32) NULL COMMENT '獎勵觸發資料序號',
    reward_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待達成;ELIGIBLE符合;APPROVED核准;PAID已發放;REJECTED拒絕;CANCELLED取消',
    reward_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '獎勵金額',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    payment_sid VARCHAR(32) NULL COMMENT 'AccountingDB獎勵付款序號',
    referral_status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED' COMMENT 'SUBMITTED已推薦;VALIDATED已驗證;CONVERTED已轉換;INVALID無效;DUPLICATE重複;CLOSED結案',
    CONSTRAINT uk_mr_referral_no UNIQUE (referral_no),
    INDEX idx_mr_program_sid (referral_program_sid),
    INDEX idx_mr_referrer (referrer_type, referrer_sid),
    INDEX idx_mr_converted_lead_sid (converted_lead_sid),
    INDEX idx_mr_converted_customer_sid (converted_customer_sid),
    INDEX idx_mr_reward_status (reward_status),
    INDEX idx_mr_status (referral_status),
    CHECK (reward_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='推薦名單、轉換與獎勵';

CREATE TABLE IF NOT EXISTS mkt_message_template (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷訊息範本序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    template_code VARCHAR(100) NOT NULL COMMENT '範本代碼',
    template_name VARCHAR(300) NOT NULL COMMENT '範本名稱',
    channel_type VARCHAR(20) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;OTHER',
    message_type VARCHAR(30) NOT NULL COMMENT 'CAMPAIGN活動;LEAD_NURTURE培育;REMINDER提醒;PROMOTION促銷;EVENT活動;FOLLOW_UP追蹤;OTHER',
    language_code VARCHAR(20) NOT NULL DEFAULT 'zh-TW' COMMENT '語系',
    subject_template VARCHAR(500) NULL COMMENT '主旨範本',
    body_template LONGTEXT NOT NULL COMMENT '內容範本',
    variable_schema JSON NULL COMMENT '可用變數定義',
    external_template_id VARCHAR(200) NULL COMMENT '外部服務範本ID',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需審核',
    template_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;ACTIVE生效;INACTIVE停用;ARCHIVED封存',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_mmt_template_code UNIQUE (template_code),
    INDEX idx_mmt_channel_type (channel_type),
    INDEX idx_mmt_message_type (message_type),
    INDEX idx_mmt_language_code (language_code),
    INDEX idx_mmt_status (template_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Email、簡訊、LINE與App行銷範本';

CREATE TABLE IF NOT EXISTS mkt_message_campaign (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '訊息活動序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    message_campaign_no VARCHAR(100) NOT NULL COMMENT '訊息活動編號',
    message_campaign_name VARCHAR(300) NOT NULL COMMENT '訊息活動名稱',
    campaign_sid VARCHAR(32) NULL COMMENT '行銷活動序號',
    template_sid VARCHAR(32) NOT NULL COMMENT '訊息範本序號',
    channel_type VARCHAR(20) NOT NULL COMMENT 'EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;WEBHOOK;OTHER',
    audience_rule JSON NOT NULL COMMENT '收件人條件',
    scheduled_date DATETIME NULL COMMENT '排程時間',
    actual_start_date DATETIME NULL COMMENT '實際開始時間',
    actual_end_date DATETIME NULL COMMENT '實際完成時間',
    sender_name VARCHAR(300) NULL COMMENT '寄件人名稱',
    sender_address VARCHAR(300) NULL COMMENT '寄件地址或帳號',
    total_recipient_count INT NOT NULL DEFAULT 0 COMMENT '總收件人數',
    sent_count INT NOT NULL DEFAULT 0 COMMENT '送出數',
    delivered_count INT NOT NULL DEFAULT 0 COMMENT '送達數',
    opened_count INT NOT NULL DEFAULT 0 COMMENT '開啟數',
    clicked_count INT NOT NULL DEFAULT 0 COMMENT '點擊數',
    failed_count INT NOT NULL DEFAULT 0 COMMENT '失敗數',
    unsubscribed_count INT NOT NULL DEFAULT 0 COMMENT '退訂數',
    message_campaign_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;REVIEW待審;SCHEDULED已排程;SENDING發送中;COMPLETED完成;PAUSED暫停;CANCELLED取消;FAILED失敗',
    workflow_instance_sid VARCHAR(32) NULL COMMENT 'WorkflowDB流程實例序號',
    CONSTRAINT uk_mmc_campaign_no UNIQUE (message_campaign_no),
    INDEX idx_mmc_campaign_sid (campaign_sid),
    INDEX idx_mmc_template_sid (template_sid),
    INDEX idx_mmc_channel_type (channel_type),
    INDEX idx_mmc_scheduled_date (scheduled_date),
    INDEX idx_mmc_status (message_campaign_status),
    CHECK (total_recipient_count >= 0),
    CHECK (sent_count >= 0),
    CHECK (delivered_count >= 0),
    CHECK (opened_count >= 0),
    CHECK (clicked_count >= 0),
    CHECK (failed_count >= 0),
    CHECK (unsubscribed_count >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='批次Email、簡訊、LINE與推播活動';

CREATE TABLE IF NOT EXISTS mkt_message_recipient (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '訊息收件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    message_campaign_sid VARCHAR(32) NOT NULL COMMENT '訊息活動序號',
    recipient_type VARCHAR(20) NOT NULL COMMENT 'LEAD潛客;CUSTOMER客戶;PARTY對象;CONTACT聯絡人',
    recipient_sid VARCHAR(32) NULL COMMENT '收件人序號',
    recipient_name VARCHAR(300) NULL COMMENT '收件人名稱快照',
    recipient_address VARCHAR(500) NOT NULL COMMENT 'Email、電話、LINE或推播Token',
    personalized_subject VARCHAR(500) NULL COMMENT '個人化主旨',
    personalized_body LONGTEXT NULL COMMENT '個人化內容',
    provider_message_id VARCHAR(300) NULL COMMENT '外部服務訊息ID',
    scheduled_date DATETIME NULL COMMENT '預計發送時間',
    sent_date DATETIME NULL COMMENT '實際送出時間',
    delivered_date DATETIME NULL COMMENT '送達時間',
    opened_date DATETIME NULL COMMENT '首次開啟時間',
    clicked_date DATETIME NULL COMMENT '首次點擊時間',
    failed_date DATETIME NULL COMMENT '失敗時間',
    failure_reason VARCHAR(1000) NULL COMMENT '失敗原因',
    unsubscribe_date DATETIME NULL COMMENT '退訂時間',
    recipient_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待發送;SENT已送出;DELIVERED已送達;OPENED已開啟;CLICKED已點擊;FAILED失敗;UNSUBSCRIBED退訂;CANCELLED取消',
    CONSTRAINT uk_mmr_campaign_recipient UNIQUE (message_campaign_sid, recipient_address),
    INDEX idx_mmr_message_campaign_sid (message_campaign_sid),
    INDEX idx_mmr_recipient (recipient_type, recipient_sid),
    INDEX idx_mmr_provider_message_id (provider_message_id),
    INDEX idx_mmr_sent_date (sent_date),
    INDEX idx_mmr_status (recipient_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行銷訊息個別收件與開啟點擊紀錄';

CREATE TABLE IF NOT EXISTS mkt_consent (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷同意序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    subject_type VARCHAR(20) NOT NULL COMMENT 'LEAD潛客;CUSTOMER客戶;PARTY對象;CONTACT聯絡人',
    subject_sid VARCHAR(32) NOT NULL COMMENT '同意主體序號',
    consent_type VARCHAR(30) NOT NULL COMMENT 'MARKETING行銷;EMAIL郵件;SMS簡訊;LINE;APP_PUSH推播;PERSONALIZATION個人化;THIRD_PARTY第三方',
    consent_status VARCHAR(20) NOT NULL COMMENT 'GRANTED同意;WITHDRAWN撤回;EXPIRED到期;PENDING待確認',
    consent_date DATETIME NOT NULL COMMENT '同意或異動時間',
    expiry_date DATETIME NULL COMMENT '同意到期時間',
    source_type VARCHAR(30) NOT NULL COMMENT 'FORM表單;CONTRACT合約;PORTAL平台;APP;CALL電話;IMPORT匯入;OTHER',
    source_reference_sid VARCHAR(32) NULL COMMENT '來源資料序號',
    consent_text_version VARCHAR(50) NULL COMMENT '同意文字版本',
    ip_address VARCHAR(50) NULL COMMENT 'IP位址',
    evidence_file_sid VARCHAR(32) NULL COMMENT 'FileDB同意證據序號',
    CONSTRAINT uk_mconsent_subject_type UNIQUE (subject_type, subject_sid, consent_type, consent_date),
    INDEX idx_mconsent_subject (subject_type, subject_sid),
    INDEX idx_mconsent_consent_type (consent_type),
    INDEX idx_mconsent_status (consent_status),
    INDEX idx_mconsent_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行銷、Email、簡訊、LINE與推播同意紀錄';

CREATE TABLE IF NOT EXISTS mkt_campaign_daily_metric (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '活動每日成效序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    campaign_sid VARCHAR(32) NOT NULL COMMENT '行銷活動序號',
    channel_sid VARCHAR(32) NULL COMMENT '行銷管道序號',
    ad_group_sid VARCHAR(32) NULL COMMENT '廣告群組序號',
    creative_sid VARCHAR(32) NULL COMMENT '廣告素材序號',
    metric_date DATE NOT NULL COMMENT '成效日期',
    impressions BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '曝光數',
    reach BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '觸及數',
    clicks BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '點擊數',
    sessions BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '工作階段數',
    form_submissions BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '表單數',
    leads BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '潛客數',
    visits BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '賞屋數',
    reservations BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '保留數',
    contracts BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '簽約數',
    revenue_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '歸因營收',
    spend_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT '花費金額',
    currency_sid VARCHAR(32) NULL COMMENT '幣別序號',
    ctr DECIMAL(12,6) NOT NULL DEFAULT 0 COMMENT '點擊率',
    cpc DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '單次點擊成本',
    cpl DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '單一潛客成本',
    cac DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '獲客成本',
    roas DECIMAL(20,6) NOT NULL DEFAULT 0 COMMENT '廣告投資報酬',
    CONSTRAINT uk_mcdm_dimension_date UNIQUE (campaign_sid, channel_sid, ad_group_sid, creative_sid, metric_date),
    INDEX idx_mcdm_campaign_sid (campaign_sid),
    INDEX idx_mcdm_channel_sid (channel_sid),
    INDEX idx_mcdm_ad_group_sid (ad_group_sid),
    INDEX idx_mcdm_creative_sid (creative_sid),
    INDEX idx_mcdm_metric_date (metric_date),
    CHECK (revenue_amount >= 0),
    CHECK (spend_amount >= 0),
    CHECK (ctr >= 0),
    CHECK (cpc >= 0),
    CHECK (cpl >= 0),
    CHECK (cac >= 0),
    CHECK (roas >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='曝光、點擊、名單、簽約、營收與獲客成本';

CREATE TABLE IF NOT EXISTS mkt_status_history (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷狀態歷程序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '異動時間',
    entity_type VARCHAR(30) NOT NULL COMMENT 'CAMPAIGN;CHANNEL;AD_GROUP;CREATIVE;LANDING_PAGE;FORM;SUBMISSION;PROMOTION;COUPON;REFERRAL_PROGRAM;REFERRAL;MESSAGE_TEMPLATE;MESSAGE_CAMPAIGN;RECIPIENT;CONSENT',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    old_status VARCHAR(30) NULL COMMENT '原狀態',
    new_status VARCHAR(30) NOT NULL COMMENT '新狀態',
    event_code VARCHAR(100) NULL COMMENT '觸發事件代碼',
    operator_user_sid VARCHAR(32) NULL COMMENT '操作人員序號',
    reason TEXT NULL COMMENT '原因說明',
    correlation_id VARCHAR(100) NULL COMMENT '跨服務關聯識別碼',
    INDEX idx_msh_entity (entity_type, entity_sid),
    INDEX idx_msh_new_status (new_status),
    INDEX idx_msh_event_code (event_code),
    INDEX idx_msh_operator_user_sid (operator_user_sid),
    INDEX idx_msh_correlation_id (correlation_id),
    INDEX idx_msh_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行銷活動、素材、促銷與訊息狀態歷程';

CREATE TABLE IF NOT EXISTS mkt_event (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '行銷領域事件序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    entity_type VARCHAR(30) NOT NULL COMMENT 'CAMPAIGN;CHANNEL;AD_GROUP;CREATIVE;LANDING_PAGE;FORM;SUBMISSION;TRACKING;CONVERSION;ATTRIBUTION;PROMOTION;COUPON;REFERRAL;MESSAGE;CONSENT;METRIC',
    entity_sid VARCHAR(32) NOT NULL COMMENT '實體序號',
    event_code VARCHAR(120) NOT NULL COMMENT '事件代碼',
    event_version INT NOT NULL DEFAULT 1 COMMENT '事件版本',
    event_data JSON NULL COMMENT '事件內容',
    source_event_id VARCHAR(100) NULL COMMENT '來源事件ID',
    correlation_id VARCHAR(100) NULL COMMENT '關聯識別碼',
    causation_id VARCHAR(100) NULL COMMENT '因果事件ID',
    outbox_event_sid VARCHAR(32) NULL COMMENT 'IntegrationDB Outbox事件序號',
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;SUCCESS成功;FAILED失敗;IGNORED忽略',
    processed_date DATETIME NULL COMMENT '處理時間',
    error_message TEXT NULL COMMENT '錯誤訊息',
    UNIQUE KEY uk_me_source_event_id (source_event_id),
    INDEX idx_me_entity (entity_type, entity_sid),
    INDEX idx_me_event_code (event_code),
    INDEX idx_me_correlation_id (correlation_id),
    INDEX idx_me_outbox_event_sid (outbox_event_sid),
    INDEX idx_me_status (process_status),
    INDEX idx_me_create_date (create_date),
    CHECK (event_version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行銷、流量、轉換、歸因與訊息領域事件';
SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
