namespace B2bOrder.Resources.eCommerce
{
    /// <summary>
    /// StoreDB Core Schema
    /// 規範：
    /// 1. nid：資料庫內部主鍵與外鍵
    /// 2. sid：Web / APP / API 對外識別碼
    /// 3. avalible：Y可用；W停用；D刪除
    /// 4. MasterDB、CatalogDB、ShoppingDB、IdentityDB 跨資料庫參照使用 sid
    /// 5. 支援多商店、商店員工、商店商品、商店價格與結算設定
    /// 6. 適用 MySQL 8.x / InnoDB / utf8mb4
    /// </summary>
    internal static class StoreDB
    {
        public static readonly string CreateTables = @"
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS sto_store (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_no VARCHAR(50) NOT NULL COMMENT '商店編號',
    store_type_sid VARCHAR(32) NOT NULL COMMENT 'MasterDB商店類型序號',
    owner_member_sid VARCHAR(32) NULL COMMENT 'ShoppingDB店主會員序號',
    company_sid VARCHAR(32) NULL COMMENT 'MasterDB公司序號',
    store_name VARCHAR(200) NOT NULL COMMENT '商店名稱',
    store_short_name VARCHAR(100) NULL COMMENT '商店簡稱',
    logo_url VARCHAR(500) NULL COMMENT '商店Logo',
    banner_url VARCHAR(500) NULL COMMENT '商店Banner',
    description LONGTEXT NULL COMMENT '商店介紹',
    tax_no VARCHAR(20) NULL COMMENT '統一編號',
    representative VARCHAR(100) NULL COMMENT '負責人',
    contact_name VARCHAR(100) NULL COMMENT '聯絡人',
    phone VARCHAR(30) NULL COMMENT '電話',
    mobile VARCHAR(30) NULL COMMENT '手機',
    email VARCHAR(200) NULL COMMENT '電子信箱',
    website VARCHAR(500) NULL COMMENT '網站',
    country_sid VARCHAR(32) NULL COMMENT 'MasterDB國家序號',
    city_sid VARCHAR(32) NULL COMMENT 'MasterDB縣市序號',
    district_sid VARCHAR(32) NULL COMMENT 'MasterDB行政區序號',
    postal_code VARCHAR(10) NULL COMMENT '郵遞區號',
    address VARCHAR(500) NULL COMMENT '商店地址',
    default_warehouse_sid VARCHAR(32) NULL COMMENT 'MasterDB預設倉庫序號',
    default_currency_sid VARCHAR(32) NULL COMMENT 'MasterDB預設幣別序號',
    default_tax_sid VARCHAR(32) NULL COMMENT 'MasterDB預設稅別序號',
    settlement_cycle VARCHAR(30) NOT NULL DEFAULT 'MONTHLY' COMMENT 'DAILY每日;WEEKLY每週;BIWEEKLY雙週;MONTHLY每月',
    platform_fee_rate DECIMAL(8,4) NOT NULL DEFAULT 0 COMMENT '平台服務費率百分比',
    store_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待審;ACTIVE營運中;SUSPENDED停權;CLOSED結束',
    approved_date DATETIME NULL COMMENT '核准時間',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT uk_ss_store_no UNIQUE (store_no),
    INDEX idx_ss_store_type_sid (store_type_sid),
    INDEX idx_ss_owner_member_sid (owner_member_sid),
    INDEX idx_ss_company_sid (company_sid),
    INDEX idx_ss_default_warehouse_sid (default_warehouse_sid),
    INDEX idx_ss_status (store_status),
    INDEX idx_ss_avalible (avalible),
    CHECK (platform_fee_rate >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店主檔';

CREATE TABLE IF NOT EXISTS sto_store_setting (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店設定序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    setting_key VARCHAR(100) NOT NULL COMMENT '設定鍵值',
    setting_value LONGTEXT NULL COMMENT '設定內容',
    setting_type VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT;NUMBER;BOOLEAN;JSON',
    category VARCHAR(50) NULL COMMENT 'BASIC;ORDER;SHIPPING;PAYMENT;DISPLAY',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_sss_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_sss_store_key UNIQUE (store_nid, setting_key),
    INDEX idx_sss_store_nid (store_nid),
    INDEX idx_sss_category (category),
    INDEX idx_sss_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店設定';

CREATE TABLE IF NOT EXISTS sto_store_bank (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店銀行帳戶序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    bank_code VARCHAR(20) NOT NULL COMMENT '銀行代碼',
    bank_name VARCHAR(100) NOT NULL COMMENT '銀行名稱',
    branch_code VARCHAR(20) NULL COMMENT '分行代碼',
    branch_name VARCHAR(100) NULL COMMENT '分行名稱',
    account_name VARCHAR(200) NOT NULL COMMENT '戶名',
    account_no_encrypted VARCHAR(500) NOT NULL COMMENT '帳號加密值',
    currency_sid VARCHAR(32) NULL COMMENT 'MasterDB幣別序號',
    is_default TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否預設結算帳戶',
    verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待驗證;VERIFIED已驗證;REJECTED駁回',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_ssb_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    INDEX idx_ssb_store_nid (store_nid),
    INDEX idx_ssb_bank_code (bank_code),
    INDEX idx_ssb_default (is_default),
    INDEX idx_ssb_status (verification_status),
    INDEX idx_ssb_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店銀行帳戶';

CREATE TABLE IF NOT EXISTS sto_staff (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店員工序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    user_sid VARCHAR(32) NOT NULL COMMENT 'IdentityDB帳號序號',
    employee_no VARCHAR(50) NULL COMMENT '商店員工編號',
    staff_name VARCHAR(100) NOT NULL COMMENT '員工姓名',
    email VARCHAR(200) NULL COMMENT '電子信箱',
    mobile VARCHAR(30) NULL COMMENT '手機',
    join_date DATE NULL COMMENT '加入日期',
    leave_date DATE NULL COMMENT '離開日期',
    staff_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE在職;SUSPENDED停權;LEFT離開',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_ssf_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_ssf_store_user UNIQUE (store_nid, user_sid),
    INDEX idx_ssf_store_nid (store_nid),
    INDEX idx_ssf_user_sid (user_sid),
    INDEX idx_ssf_status (staff_status),
    INDEX idx_ssf_avalible (avalible),
    CHECK (leave_date IS NULL OR join_date IS NULL OR leave_date >= join_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店員工';

CREATE TABLE IF NOT EXISTS sto_staff_role (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店員工角色關聯序號',
    staff_nid BIGINT UNSIGNED NOT NULL COMMENT '商店員工流水號',
    role_sid VARCHAR(32) NOT NULL COMMENT 'IdentityDB角色序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    start_date DATETIME NULL COMMENT '生效時間',
    end_date DATETIME NULL COMMENT '失效時間',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_ssr_staff FOREIGN KEY (staff_nid) REFERENCES sto_staff(nid),
    CONSTRAINT uk_ssr_staff_role UNIQUE (staff_nid, role_sid),
    INDEX idx_ssr_staff_nid (staff_nid),
    INDEX idx_ssr_role_sid (role_sid),
    INDEX idx_ssr_date (start_date, end_date),
    INDEX idx_ssr_avalible (avalible),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店員工角色';

CREATE TABLE IF NOT EXISTS sto_product (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店商品序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    product_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB商品序號',
    store_product_no VARCHAR(80) NULL COMMENT '商店自訂商品編號',
    store_category_code VARCHAR(100) NULL COMMENT '商店內部分類代碼',
    store_product_name VARCHAR(255) NULL COMMENT '商店自訂商品名稱',
    shelf_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;PENDING待審;ONLINE上架;OFFLINE下架',
    start_date DATETIME NULL COMMENT '上架開始時間',
    end_date DATETIME NULL COMMENT '上架結束時間',
    is_featured TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否精選商品',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stp_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_stp_store_product UNIQUE (store_nid, product_sid),
    INDEX idx_stp_store_nid (store_nid),
    INDEX idx_stp_product_sid (product_sid),
    INDEX idx_stp_shelf_status (shelf_status),
    INDEX idx_stp_featured (is_featured),
    INDEX idx_stp_date (start_date, end_date),
    INDEX idx_stp_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店商品';

CREATE TABLE IF NOT EXISTS sto_product_sku (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店SKU序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_product_nid BIGINT UNSIGNED NOT NULL COMMENT '商店商品流水號',
    sku_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB SKU序號',
    store_sku_no VARCHAR(100) NULL COMMENT '商店自訂SKU編號',
    sale_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE販售中;INACTIVE停用;OUT_OF_STOCK缺貨;DISCONTINUED停售',
    max_sale_qty DECIMAL(20,6) NULL COMMENT '單筆最大銷售量',
    sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stps_store_product FOREIGN KEY (store_product_nid) REFERENCES sto_product(nid),
    CONSTRAINT uk_stps_store_product_sku UNIQUE (store_product_nid, sku_sid),
    INDEX idx_stps_store_product_nid (store_product_nid),
    INDEX idx_stps_sku_sid (sku_sid),
    INDEX idx_stps_sale_status (sale_status),
    INDEX idx_stps_avalible (avalible),
    CHECK (max_sale_qty IS NULL OR max_sale_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店SKU設定';

CREATE TABLE IF NOT EXISTS sto_product_price (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店商品價格序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    store_product_nid BIGINT UNSIGNED NOT NULL COMMENT '商店商品流水號',
    sku_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB SKU序號',
    price_group_sid VARCHAR(32) NOT NULL COMMENT 'MasterDB價格群組序號',
    currency_sid VARCHAR(32) NOT NULL COMMENT 'MasterDB幣別序號',
    price DECIMAL(18,4) NOT NULL COMMENT '商店售價',
    start_date DATETIME NULL COMMENT '生效開始時間',
    end_date DATETIME NULL COMMENT '生效結束時間',
    priority INT NOT NULL DEFAULT 0 COMMENT '優先順序',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stpp_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT fk_stpp_store_product FOREIGN KEY (store_product_nid) REFERENCES sto_product(nid),
    CONSTRAINT uk_stpp_price UNIQUE (store_nid, sku_sid, price_group_sid, currency_sid, start_date),
    INDEX idx_stpp_store_nid (store_nid),
    INDEX idx_stpp_store_product_nid (store_product_nid),
    INDEX idx_stpp_sku_sid (sku_sid),
    INDEX idx_stpp_price_group_sid (price_group_sid),
    INDEX idx_stpp_effective (start_date, end_date),
    INDEX idx_stpp_priority (priority),
    INDEX idx_stpp_avalible (avalible),
    CHECK (price >= 0),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店商品價格';

CREATE TABLE IF NOT EXISTS sto_product_warehouse (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店商品倉庫關聯序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    sku_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB SKU序號',
    warehouse_sid VARCHAR(32) NOT NULL COMMENT 'MasterDB倉庫序號',
    is_primary TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主要出貨倉庫',
    allocation_priority INT NOT NULL DEFAULT 0 COMMENT '配貨優先順序',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stpw_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_stpw_store_sku_warehouse UNIQUE (store_nid, sku_sid, warehouse_sid),
    INDEX idx_stpw_store_nid (store_nid),
    INDEX idx_stpw_sku_sid (sku_sid),
    INDEX idx_stpw_warehouse_sid (warehouse_sid),
    INDEX idx_stpw_primary (is_primary),
    INDEX idx_stpw_avalible (avalible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店SKU可用倉庫';

CREATE TABLE IF NOT EXISTS sto_order (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店訂單序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    shopping_order_sid VARCHAR(32) NOT NULL COMMENT 'ShoppingDB平台訂單序號',
    store_order_no VARCHAR(60) NOT NULL COMMENT '商店子訂單編號',
    order_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING待處理;PROCESSING處理中;READY_TO_SHIP待出貨;SHIPPED已出貨;COMPLETED完成;CANCELLED取消',
    subtotal_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '商品小計',
    discount_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '商店折扣金額',
    freight_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '商店運費',
    platform_fee_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '平台服務費',
    payable_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '商店應收結算金額',
    warehouse_sid VARCHAR(32) NULL COMMENT '主要出貨倉庫序號',
    accepted_date DATETIME NULL COMMENT '接單時間',
    processing_user_sid VARCHAR(32) NULL COMMENT '處理人員序號',
    completed_date DATETIME NULL COMMENT '完成時間',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_sto_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_sto_store_order_no UNIQUE (store_order_no),
    CONSTRAINT uk_sto_store_shopping_order UNIQUE (store_nid, shopping_order_sid),
    INDEX idx_sto_store_nid (store_nid),
    INDEX idx_sto_shopping_order_sid (shopping_order_sid),
    INDEX idx_sto_order_status (order_status),
    INDEX idx_sto_warehouse_sid (warehouse_sid),
    INDEX idx_sto_create_date (create_date),
    INDEX idx_sto_avalible (avalible),
    CHECK (subtotal_amount >= 0),
    CHECK (discount_amount >= 0),
    CHECK (freight_amount >= 0),
    CHECK (platform_fee_amount >= 0),
    CHECK (payable_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店子訂單';

CREATE TABLE IF NOT EXISTS sto_order_item (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店訂單明細序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    store_order_nid BIGINT UNSIGNED NOT NULL COMMENT '商店訂單流水號',
    shopping_order_item_sid VARCHAR(32) NOT NULL COMMENT 'ShoppingDB訂單明細序號',
    product_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB商品序號',
    sku_sid VARCHAR(32) NOT NULL COMMENT 'CatalogDB SKU序號',
    quantity DECIMAL(20,6) NOT NULL COMMENT '數量',
    unit_price DECIMAL(18,4) NOT NULL COMMENT '成交單價',
    discount_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '折扣金額',
    line_amount DECIMAL(18,4) NOT NULL COMMENT '明細金額',
    platform_fee_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '平台費用分攤',
    settlement_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '結算金額',
    item_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE有效;CANCELLED取消;SHIPPED已出貨;RETURNED已退貨',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stoi_store_order FOREIGN KEY (store_order_nid) REFERENCES sto_order(nid),
    CONSTRAINT uk_stoi_order_item UNIQUE (store_order_nid, shopping_order_item_sid),
    INDEX idx_stoi_store_order_nid (store_order_nid),
    INDEX idx_stoi_shopping_order_item_sid (shopping_order_item_sid),
    INDEX idx_stoi_product_sid (product_sid),
    INDEX idx_stoi_sku_sid (sku_sid),
    INDEX idx_stoi_status (item_status),
    CHECK (quantity > 0),
    CHECK (unit_price >= 0),
    CHECK (discount_amount >= 0),
    CHECK (line_amount >= 0),
    CHECK (platform_fee_amount >= 0),
    CHECK (settlement_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店訂單明細';

CREATE TABLE IF NOT EXISTS sto_settlement (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店結算序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    modify_date DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改日期',
    settlement_no VARCHAR(60) NOT NULL COMMENT '結算單號',
    store_nid BIGINT UNSIGNED NOT NULL COMMENT '商店流水號',
    period_start_date DATE NOT NULL COMMENT '結算期間開始日',
    period_end_date DATE NOT NULL COMMENT '結算期間結束日',
    currency_sid VARCHAR(32) NOT NULL COMMENT 'MasterDB幣別序號',
    gross_sales_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '銷售總額',
    refund_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '退款金額',
    discount_share_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '商店負擔優惠金額',
    platform_fee_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '平台服務費',
    payment_fee_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '金流手續費',
    shipping_fee_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '物流費',
    adjustment_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '調整金額',
    payable_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '應付商店金額',
    paid_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '已付款金額',
    settlement_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT草稿;CONFIRMED確認;APPROVED核准;PAID已付款;CANCELLED取消',
    approved_user_sid VARCHAR(32) NULL COMMENT '核准人員序號',
    approved_date DATETIME NULL COMMENT '核准時間',
    paid_date DATETIME NULL COMMENT '付款時間',
    payment_reference_sid VARCHAR(32) NULL COMMENT 'AccountingDB付款單序號',
    avalible VARCHAR(2) NOT NULL DEFAULT 'Y' COMMENT 'Y可用;D刪除;W停用',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_sts_store FOREIGN KEY (store_nid) REFERENCES sto_store(nid),
    CONSTRAINT uk_sts_settlement_no UNIQUE (settlement_no),
    CONSTRAINT uk_sts_store_period UNIQUE (store_nid, period_start_date, period_end_date),
    INDEX idx_sts_store_nid (store_nid),
    INDEX idx_sts_period (period_start_date, period_end_date),
    INDEX idx_sts_status (settlement_status),
    INDEX idx_sts_paid_date (paid_date),
    INDEX idx_sts_avalible (avalible),
    CHECK (period_end_date >= period_start_date),
    CHECK (gross_sales_amount >= 0),
    CHECK (refund_amount >= 0),
    CHECK (discount_share_amount >= 0),
    CHECK (platform_fee_amount >= 0),
    CHECK (payment_fee_amount >= 0),
    CHECK (shipping_fee_amount >= 0),
    CHECK (payable_amount >= 0),
    CHECK (paid_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店結算單';

CREATE TABLE IF NOT EXISTS sto_settlement_item (
    nid BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    sid VARCHAR(32) NOT NULL UNIQUE COMMENT '商店結算明細序號',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立日期',
    settlement_nid BIGINT UNSIGNED NOT NULL COMMENT '商店結算單流水號',
    store_order_sid VARCHAR(32) NULL COMMENT '商店訂單序號',
    source_type VARCHAR(30) NOT NULL COMMENT 'ORDER訂單;REFUND退款;FEE費用;ADJUSTMENT調整',
    source_sid VARCHAR(32) NOT NULL COMMENT '來源資料序號',
    source_no VARCHAR(60) NULL COMMENT '來源單號',
    transaction_date DATETIME NOT NULL COMMENT '交易日期',
    gross_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '交易總額',
    deduction_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '扣除金額',
    settlement_amount DECIMAL(18,4) NOT NULL DEFAULT 0 COMMENT '結算金額',
    remark TEXT NULL COMMENT '備註',
    CONSTRAINT fk_stsi_settlement FOREIGN KEY (settlement_nid) REFERENCES sto_settlement(nid),
    CONSTRAINT uk_stsi_source UNIQUE (settlement_nid, source_type, source_sid),
    INDEX idx_stsi_settlement_nid (settlement_nid),
    INDEX idx_stsi_store_order_sid (store_order_sid),
    INDEX idx_stsi_source (source_type, source_sid),
    INDEX idx_stsi_transaction_date (transaction_date),
    CHECK (gross_amount >= 0),
    CHECK (deduction_amount >= 0),
    CHECK (settlement_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商店結算明細';

SET FOREIGN_KEY_CHECKS = 1;
";
    }
}
